### ISSUE TITLE
lotus v1.10.0

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#6185] opened 2021-05-04 19:26 UTC
# Lotus v1.10.0 Release

## 🗺 What's left for the release
https://github.com/filecoin-project/lotus/milestone/16

## 🚢 Estimated shipping date

Please see https://github.com/filecoin-project/lotus/discussions/6283

## ✅ Release Checklist

**Note for whomever is owning the release:** please capture notes as comments in this issue for anything you noticed that could be improved for future releases.  There is a *Post Release* step below for incorporating changes back into the [RELEASE_ISSUE_TEMPLATE](https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md), and this is easier done by collecting notes from along the way rather than just thinking about it at the end.

First steps:

  - [x] Fork a new branch (`release/vX.Y.Z`) from `master` and make any further release related changes to this branch. If any "non-trivial" changes get added to the release, uncheck all the checkboxes and return to this stage.
  - [x] Prep the changelog using `scripts/mkreleaselog`, and add it to `CHANGELOG.md`
  - [x] Bump the version in `version.go` in the `master` branch to `vX.(Y+1).0-dev`.

Tracking items for rc2:
- [x] Butterfly testing
- [x] #6338
- [x] #6394
- [x] #6407
- [x] #6412
- [x] #6423
- [x] Integrate updated actor

Tracking items for rc3:
- [x] #6431 
- [x] #6450

rc4 contained no new fixes but fixed an issue with how rc3 was cut 
rc5 contained a minor fix that would affect miners during the upgrade window (PR #6504)
rc6 contained ...

Tracking items for rc7:
- [x] Any bug fixes from calibration / rc3-6 testing
- [x] #6515
- [x] #6396
- [x] #6380
- [x] #6156
- [x] #6157
- [ ] #6352
- [x] #6422 
- [ ] #3613
- [x] Any bug fixes from running the tests that were created in the issues above
    
Prepping an RC:

- [x] version string in `build/version.go` has been updated (in the `release/vX.Y.Z` branch).
- [x] tag commit with `vX.Y.Z-rcN`
- [x] cut a pre-release [here](https://github.com/filecoin-project/lotus/releases/new?prerelease=true)

Testing an RC:

- [x] **Stage 0 - Automated Testing**
  - Automated Testing
    - [x] CI: Ensure that all tests are passing.
    - [x] Testground tests

- [x] **Stage 1 - Internal Testing**
  - Binaries
    - [x] Ensure the RC release has downloadable binaries
    - [x] Validate the binary is able to run on at least one platform  
  - Upgrade our testnet infra
    - [x] 1 bootstrap node
    - [x] 1 miner
    - [x] Scratch nodes
    - [x] Wait 24 hours, confirm nodes stay in sync
    - [x] Remaining testnet infra
  -  Upgrade our mainnet infra
    - [x] Subset of development full archival nodes
    - [x] Subset of bootstrappers (1 per region)
    - [x] Confirm nodes stay in sync
    - Metrics report
        - Block validation time
        - Memory / CPU usage
        - Number of goroutines
        - IPLD block read latency
        - Bandwidth usage
    - [x] If anything has worsened significantly, investigate + fix
  - Confirm the following work (some combination of Testground / Calibnet / Mainnet / beta users)
    - [x] Seal a sector
    - [x] make a deal
    - [x] Submit a PoSt
    - [x] (optional) let a sector go faulty, and see it be recovered
    
- [x] **Stage 2 - Community Testing**
  - [x] Inform beta miners (@lotus-early-testers-miner in Filecoin Slack #fil-lotus)
  - [x] Ask close ecosystem partners to test their projects (@lotus-early-testers-eco-dev in Filecoin slack #fil-lotus)
    - [x] Powergate
    - [x] Glif
    - [x] Zondax
    - [x] Stats dashboard
    - [ ] Community dashboards
    - [x] Infura
    - [x] Sentinel
    - [x] Protofire
    - [ ] Fleek

- [x] **Stage 3 - Community Prod Testing**
  - [x] Documentation
    - [x] Ensure that [CHANGELOG.md](https://github.com/filecoin-project/lotus/blob/master/CHANGELOG.md) is up to date
    - [x] Check if any [config](https://docs.filecoin.io/get-started/lotus/configuration-and-advanced-usage/#configuration) updates are needed
  - [x] Invite the wider community through (link to the release issue):
    - [x] Check `Create a discussion for this release` when tagging for the major rcs(new features, hot-fixes) release 
    - [x] Link the disucssion in #fil-lotus on Filecoin slack
    
- [x] **Stage 4 - Release**
  - [x] Final preparation
    - [x] Verify that version string in [`version.go`](https://github.com/ipfs/go-ipfs/tree/master/version.go) has been updated.
    - [x] Ensure that [CHANGELOG.md](https://github.com/filecoin-project/lotus/blob/master/CHANGELOG.md) is up to date
    - [x] Ensure that [README.md](https://github.com/filecoin-project/lotus/blob/master/README.md) is up to date
    - [x] Merge `release-vX.Y.Z` into the `releases` branch.
    - [x] Tag this merge commit (on the `releases` branch) with `vX.Y.Z`
    - [x] Cut the release [here](https://github.com/filecoin-project/lotus/releases/new?prerelease=true&target=releases).
        - [x]  Check `Create a discussion for this release` when tagging the release 
    - [x] Final announcements
        - [x] Update network.filecoin.io for mainnet, calib and nerpa.
        - [x] repost in #fil-lotus in filecoin slack
        - [x] Inform node provides (Protofire, Digital Ocean..)

- [x] **Post-Release**
  - [x] Merge the `releases` branch back into `master`, ignoring the changes to `version.go` (keep the `-dev` version from master). Do NOT delete the `releases` branch when doing so!
  - [x] Update [RELEASE_ISSUE_TEMPLATE.md](https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md) with any improvements determined from this latest release iteration.
  - [x] Create an issue using [RELEASE_ISSUE_TEMPLATE.md](https://github.com/filecoin-project/lotus/blob/master/documentation/misc/RELEASE_ISSUE_TEMPLATE.md) for the _next_ release.

## ❤️ Contributors

💙Thank you to all the contributors!

| Contributor        | Commits | Lines ±     | Files Changed |
|--------------------|---------|-------------|---------------|
| @magik6k    | 81      | +9606/-1536 | 361           |
| @arajasek  | 41      | +6543/-679  | 189           |
| @ZenGround0         | 11      | +4074/-727  | 110           |
| @anorth                | 10      | +2035/-1177 | 55            |
| @iand           | 1       | +779/-12    | 5             |
| @frrist             | 2       | +722/-6     | 6             |
| @Stebalien       | 6       | +368/-24    | 15            |
| @jennijuju      | 11      | +204/-111   | 19            |
| @vyzo               | 6       | +155/-66    | 13            |
| @coryschwartz      | 10      | +171/-27    | 14            |
| @Kubuxu    | 4       | +177/-13    | 7             |
| @ribasushi    | 4       | +65/-42     | 5             |
| @travisperson      | 2       | +11/-11     | 4             |
| @kirk-baird | 1       | +1/-5       | 1             |
| @wangchao           | 2       | +3/-2       | 2             |

## ⁉️ Do you have questions?

Leave a comment [here](<link to release discussion>) if you have any questions.

**Comment by Fatman13** [comment] 2021-05-14 03:20
> This is an optional Lotus release that introduces various improvements to the sealing, mining, and deal-making processes.

Is this a typo?

**Comment by ROXtiGerf** [comment] 2021-05-17 08:37
does all the box need to be ticked to finish this release?

**Comment by BigLep** [comment] 2021-05-28 23:10
We're planning to do initiate an RC on Tuesday, 2021-06-01.  The final release date is still TBD.  We'll update here when the RC is available.

**Comment by BigLep** [comment] 2021-06-04 22:17
I specified in the description above what tasks we're waiting on before rc2 and rc3.

**Comment by arajasek** [comment] 2021-06-22 23:46
There will be no RC7, since no real code changes have landed since RC6.

**Comment by jennijuju** [comment] 2021-06-24 18:15
https://github.com/filecoin-project/lotus/releases/tag/v1.10.0

**Comment by BigLep** [comment] 2021-06-24 19:36
Per 2021-06-24 standup, reopening until we have gone through and confirmed that all the items (including post release items) are done.

**Closed** 2021-07-05 16:41 UTC
Labels: release
