### ISSUE TITLE
Unsealed file readers keep references to moved out files

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#10935] opened 2023-05-31 16:54 UTC
This causes sealing disk space to never be freed, which may block sealing pipelines

![2023-05-31-184201_889x572_scrot](https://github.com/filecoin-project/lotus/assets/3867941/57b70641-1757-40f5-b13d-1ed04e217902)

**Comment by bobdubois** [comment] 2023-09-19 07:48
Currently (and most of the time) it's the PC1 worker who locks the deleted files, which is the most annoying one to restart. I've had (once) the AP worker locking the files, which was less painful because it's easy to restart AP.
If by means of a quick workaround this lock could be forced to happen on any other worker than PC1, that would be very helpful already.

**Comment by yann-y** [comment] 2023-09-21 08:15
boost obtains unsealed generated，HTTP not closed

**Comment by yann-y** [comment] 2023-09-21 08:24
stopped boostd   all locked unsealed files were released!

**Comment by rjan90** [comment] 2023-09-22 05:49
This can probably be closed as https://github.com/filecoin-project/boost/pull/1707 has been confirmed to fix the issue.

**Closed** 2023-09-22 13:29 UTC
Labels: kind/bug, area/sealing
