### ISSUE TITLE
chainwatch err

### ISSUE THREAD

**Issue by wei-jianlin** [filecoin-project/lotus#1206] opened 2020-02-04 02:36 UTC
**Describe the bug**
chainwatch run err

**To Reproduce**
1.chainwatch run
2.tail -f chainwatch.log

**Expected behavior**

**Screenshots**

**Version (run `lotus --version`):**
lotus: 0.2.7
psql:  psql (PostgreSQL) 12.1 (Ubuntu 12.1-1.pgdg18.04+1)
**Additional context**

root@hos:/home/ars# tail -f lotus-watch.log
2020-02-04T02:08:30.736Z INFO chainwatch lotus-chainwatch/sync.go:372 Storing message inclusions
2020-02-04T02:08:30.757Z INFO chainwatch lotus-chainwatch/sync.go:379 Storing parent receipts
2020-02-04T02:08:30.795Z INFO chainwatch lotus-chainwatch/sync.go:385 Sync stage done
2020-02-04T02:08:30.795Z INFO chainwatch lotus-chainwatch/sync.go:404 Refresh views
2020-02-04T02:08:30.921Z ERROR chainwatch lotus-chainwatch/sync.go:407 pq: could not create unique index "state_heights_uindex"
main.syncHead
/home/john/go/src/github.com/filecoin-project/lotus/cmd/lotus-chainwatch/sync.go:407
main.runSyncer.func1
/home/john/go/src/github.com/filecoin-project/lotus/cmd/lotus-chainwatch/sync.go:35
2020-02-04T02:08:32.341Z INFO chainwatch lotus-chainwatch/mpool.go:49 Processing 1 mpool updates
2020-02-04T02:08:34.037Z INFO chainwatch lotus-chainwatch/mpool.go:49 Processing 1 mpool updates
^C
root@hos:/home/ars# psql --version
psql (PostgreSQL) 12.1 (Ubuntu 12.1-1.pgdg18.04+1)

But I'm going into the database right now

chainwatch=# create unique index if not exists state_heights_uindex on state_heights (height);
NOTICE: relation "state_heights_uindex" already exists, skipping
CREATE INDEX
chainwatch=# select * from state_heights;
height | parentstateroot
--------+----------------------------------------------------------------
0 | bafy2bzaceboghf2ktc667z66nm23h7birr4gup5fcdjwspegdxdwry4h2xqmy
(1 row)

chainwatch=#

**Comment by wei-jianlin** [comment] 2020-02-04 05:54
REFRESH MATERIALIZED VIEW "public.state_heights"

ERROR : ERROR:  could not create unique index "state_heights_uindex"
DETAIL:  Key (height)=(38534) is duplicated.

**Comment by magik6k** [comment] 2020-06-17 14:25
Duplicate of https://github.com/filecoin-project/lotus/issues/1199

**Closed by magik6k** 2020-06-17 14:25 UTC
