### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by shishi614** [filecoin-project/lotus#1998] opened 2020-06-12 04:15 UTC
When the program starts, Panic

![image](https://user-images.githubusercontent.com/20469171/84464150-50e5af80-aca6-11ea-85c7-9d3ddbc500be.png)

~/sealinterop/bin$ ./lotus-storage-miner -v
lotus-storage-miner version 0.4.0+git.96a5e579.dirty

**Comment by arajasek** [comment] 2020-06-12 04:19
Did this just happen the once, or is it reproducible?

**Comment by shishi614** [comment] 2020-06-12 04:21
it reproducible，It's gonna crash all the time

**Comment by whyrusleeping** [comment] 2020-06-12 16:08
it looks like this has been resolved in a recent change to the storage-fsm

**Comment by daviddias** [comment] 2020-08-04 17:00
Closing. @shishi614 let us know if you still find the issue and we will reopen if necessary

**Closed by daviddias** 2020-08-04 17:00 UTC
