### ISSUE TITLE
can't go build on windows

### ISSUE THREAD

**Issue by jiyilanzhou** [filecoin-project/lotus#2168] opened 2020-06-29 08:17 UTC
**Describe the bug**
when i build this project in my windows computor, build failed with undefined: syscall.Statfs_t

**To Reproduce**
1. Run '...'
2. See error
```
D:\goSpace\pkg\mod\github.com\filecoin-project\sector-storage@v0.0.0-20200625154333-98ef8e4ef246\stores\interface.go:41:11: undefined: syscall.Statfs_t
D:\goSpace\pkg\mod\github.com\filecoin-project\sector-storage@v0.0.0-20200625154333-98ef8e4ef246\stores\interface.go:42:12: undefined: syscall.Statfs
# pkg-config --cflags  -- D:/goSpace/src/github.com/filecoin-project/lotus/extern/filecoin-ffi/generated/../filcrypto.pc D:/goSpace/src/github.com/filecoin-project/lotus/extern/filecoin-ffi/generated/../filcrypto.pc D:/goSpace/src/github.com/filecoin-project/lotus/extern/filecoin-ffi/generated/../filcrypto.pc D:/goSpace/src/github.com/filecoin-project/lotus/extern/filecoin-ffi/generated/../filcrypto.pc D:/goSpace/src/github.com/filecoin-project/lotus/extern/filecoin-ffi/generated/../filcrypto.pc
pkg-config: exit status 3221225781
```

**Expected behavior**
build success

**Screenshots**

**Version (run `lotus --version`):**

**Additional context**

**Comment by RobQuistNL** [comment] 2020-06-29 08:21
On windows the `syscall.statfs` should probably be replaced with `syscall.MustLoadDLL("kernel32.dll")` 

Windows is not officially supported so it might take while for this to be fixed - and there will probably be many more errors when compiling on windows.

**Comment by Kubuxu** [comment] 2020-06-29 12:17
The bigger problem will be the lack of `filecoin-ffi` for Windows.

**Comment by magik6k** [comment] 2020-06-29 17:02
Duplicate of https://github.com/filecoin-project/lotus/issues/2133

**Closed by magik6k** 2020-06-29 17:02 UTC
