### ISSUE TITLE
mining block failed: failed to get mining base info

### ISSUE THREAD

**Issue by rocqina** [filecoin-project/lotus#2621] opened 2020-07-28 01:50 UTC
![image](https://user-images.githubusercontent.com/15166591/88609754-82300880-d0b7-11ea-9dbd-de0cf8afcbf5.png)

When I run lotus-storage-miner run, I get last error info.

What means about that?

**Comment by arajasek** [comment] 2020-08-04 16:50
Duplicate of #2226

**Closed by arajasek** 2020-08-04 16:50 UTC
Labels: kind/bug
