### ISSUE TITLE
interopnet can't sync

### ISSUE THREAD

**Issue by gavin-ygy** [filecoin-project/lotus#1598] opened 2020-04-24 06:37 UTC
lotus version 0.3.0+git1f6ef376.
./lotus sync wait , always stuck at hight 279.And the status errer " collectChain syncMessages: message processing failed: validating block bafy2bzacedbrx36mfrc5jswe2lz3pznwkqqsvxiqfhwtkbdy5my5eg4p4o7ly: parent state root did not match computed state (bafy2bzacedhchlfcqpgcfczkcwmzbclaytwesoaaw6lbxfm27rsqntvr6cg6q != bafy2bzaceaexfchpuzcrlhminbtg3kgm4o3aan5r2oopqu6deaxkfk6glm32w)"

I have tested in different node, the error is as same as above.
==============
sk@square:~/log$ ./lotus sync wait
Worker 0: Target: []    State: <unknown: 0>     Height: 0
Worker 0: Target: []    State: <unknown: 0>     Height: 0^[[A
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 3804
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 3804
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 3804
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 3804
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 3804
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 3804
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 3804
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 3804
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 3804
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 3304
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 3304
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 3304
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 2804
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 2804
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 2804
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 2804
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 2804
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 2304
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 2304
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 2304
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 2304
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 2304
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 2304
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 1802
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 1227
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 1227
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 1227
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 1227
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 1227
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 1227
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 1227
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 1227
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 727
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 727
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 727
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 727
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 227
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: header sync      Height: 227
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 0
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 0
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 0
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 11
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 41
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 68
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 69
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 70
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 70
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 71
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 71
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 71
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 72
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 81
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 95
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 109
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 111
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 111
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 111
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 112
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 112
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 123
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 147
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 160
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 173
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 185
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 198
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 211
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 214
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 226
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 238
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 250
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 261
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: message sync     Height: 272
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: error    Height: 279
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: error    Height: 279
Worker 0: Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu]       State: error    Height: 279^C
Exit by user
sk@square:~/log$
sk@square:~/log$ ./lotus sync status
sync status:
worker 0:
        Base:   [bafy2bzacec6t4zow2gnatt42mmvdsu3665xgbzqqyklip4stqqoceqflvdvls]
        Target: [bafy2bzacecysdo4d67r6zpqlpdk4da3fqnkqba23hr6fwstdoy76njacsg3x2 bafy2bzacebbcqsqdphqnbudjvvprlyezprzqiin7aixbdx5jpilfppnu4s4fu] (3804)
        Height diff:    3804
        Stage: error
        Height: 279
        Elapsed: 1m31.864542391s
        Error: collectChain syncMessages: message processing failed: validating block bafy2bzacedbrx36mfrc5jswe2lz3pznwkqqsvxiqfhwtkbdy5my5eg4p4o7ly: parent state root did not match computed state (bafy2bzacedhchlfcqpgcfczkcwmzbclaytwesoaaw6lbxfm27rsqntvr6cg6q != bafy2bzaceaexfchpuzcrlhminbtg3kgm4o3aan5r2oopqu6deaxkfk6glm32w)
worker 1:
        Base:   []
        Target: [] (0)
        Height diff:    0
        Stage: <unknown: 0>
        Height: 0
worker 2:
        Base:   []
        Target: [] (0)
        Height diff:    0
        Stage: <unknown: 0>
        Height: 0
-----------------------

**Comment by gavin-ygy** [comment] 2020-04-24 06:39
the cpu is AMD 3950. env RUSTFLAGS="-C target-cpu=native -g" FFI_BUILD_FROM_SOURCE=1 make all .

**Comment by gavin-ygy** [comment] 2020-04-24 07:21
sorry, the cpu is AMD３９６０ｘ

**Comment by gavin-ygy** [comment] 2020-04-24 08:55
lotus log:
2020-04-24T14:30:56.929+0800    ^[[33mWARN^[[0m chain   chain/sync.go:588       Message[0]: from=t3qtcyugfxmlthbqfckjiicmzxr6le3lg6k4k7kkflsbxwitmdemprsrotiy6xvgnaugakh5ehrvv6soy54bla to=t01850 method=7 params=820058c094b345af192d70e7f081a71080eedc1b4a5b103aed31e255a9af15bcaf5b60330d5e0118df270ab17b5db0cd1a64b417b8d1353ca46f67f08a94a7baabd00831127ec7a913c43774a8a8d2c98ae7c9473ebc43eaccf641dd3eab0e9e1af2d57e04c31be253bd646fe0e57ee1d01fa5ba3e3614222faa049ee5c02dc513643fc980526b5d4fabf8c83b0958598f4362339540cdcbf4bc16b2dc3106c4a5057bdef0e63e27259fbc1da3e2b4ea76c2bc4d8a772c26a42a17db105dc927c56360b0
2020-04-24T14:30:56.929+0800    ^[[31mERROR^[[0m        chain   chain/sync.go:1131      failed to validate tipset: validating block bafy2bzacedbrx36mfrc5jswe2lz3pznwkqqsvxiqfhwtkbdy5my5eg4p4o7ly:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateTipSet
        /home/sk/lotus/chain/sync.go:472
  - parent state root did not match computed state (bafy2bzacedhchlfcqpgcfczkcwmzbclaytwesoaaw6lbxfm27rsqntvr6cg6q != bafy2bzaceaexfchpuzcrlhminbtg3kgm4o3aan5r2oopqu6deaxkfk6glm32w):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock
        /home/sk/lotus/chain/sync.go:592
github.com/filecoin-project/lotus/chain.(*Syncer).syncMessagesAndCheckState.func1
        /home/sk/lotus/chain/sync.go:1131
github.com/filecoin-project/lotus/chain.(*Syncer).iterFullTipsets
        /home/sk/lotus/chain/sync.go:1200
github.com/filecoin-project/lotus/chain.(*Syncer).syncMessagesAndCheckState
        /home/sk/lotus/chain/sync.go:1128
github.com/filecoin-project/lotus/chain.(*Syncer).collectChain
        /home/sk/lotus/chain/sync.go:1274
github.com/filecoin-project/lotus/chain.(*Syncer).Sync
        /home/sk/lotus/chain/sync.go:422
github.com/filecoin-project/lotus/chain.(*SyncManager).syncWorker
        /home/sk/lotus/chain/sync_manager.go:386
2020-04-24T14:30:56.929+0800    ^[[31mERROR^[[0m        chain   chain/sync_manager.go:388       sync error: collectChain failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).Sync
        /home/sk/lotus/chain/sync.go:428
  - collectChain syncMessages:
    github.com/filecoin-project/lotus/chain.(*Syncer).collectChain
        /home/sk/lotus/chain/sync.go:1275
  - message processing failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).syncMessagesAndCheckState.func1
        /home/sk/lotus/chain/sync.go:1132
  - validating block bafy2bzacedbrx36mfrc5jswe2lz3pznwkqqsvxiqfhwtkbdy5my5eg4p4o7ly:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateTipSet
        /home/sk/lotus/chain/sync.go:472
  - parent state root did not match computed state (bafy2bzacedhchlfcqpgcfczkcwmzbclaytwesoaaw6lbxfm27rsqntvr6cg6q != bafy2bzaceaexfchpuzcrlhminbtg3kgm4o3aan5r2oopqu6deaxkfk6glm32w):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock
        /home/sk/lotus/chain/sync.go:592
github.com/filecoin-project/lotus/chain.(*SyncManager).syncWorker
        /home/sk/lotus/chain/sync_manager.go:388

**Comment by gavin-ygy** [comment] 2020-04-26 02:24
lotus version 0.3.0+git1bfa2311 still has the same error in AMD 3960x which can't sync .
sk@square:~/log$ ./lotus sync status
sync status:
worker 0:
        Base:   [bafy2bzaceccu5vqn5xw2morrqa2wtah3w6cs2rnmv64w3ry6st7uelnhxkg6w]
        Target: [bafy2bzacebixzncyrw37d6d6nmx3k5ju22gf672rcedgfv3fykaogre5atmzy] (3737)
        Height diff:    3737
        Stage: error
        Height: 3737
        Elapsed: 21.324934ms
        Error: chain contained block marked previously as bad ([bafy2bzacebixzncyrw37d6d6nmx3k5ju22gf672rcedgfv3fykaogre5atmzy], bafy2bzaceadtb2pckmlruuvrsyrtettnkvcub2e3qo5dottmlie7kv7q6gl6c) (reason: parent state root did not match computed state (bafy2bzacedg2zxhg3islwohkympv4xycl6r47ml7zknlay5fdxi5kmdkmpv4e != bafy2bzaceald5wa4yeycq6mblb7p4mz6vweuzxvsm7i7ljys626yotpexd6mu))
worker 1:
        Base:   []
        Target: [] (0)
        Height diff:    0
        Stage: <unknown: 0>
        Height: 0
worker 2:
        Base:   [bafy2bzaceccu5vqn5xw2morrqa2wtah3w6cs2rnmv64w3ry6st7uelnhxkg6w]
        Target: [bafy2bzacebixzncyrw37d6d6nmx3k5ju22gf672rcedgfv3fykaogre5atmzy] (3737)
        Height diff:    3737
        Stage: error
        Height: 64
        Elapsed: 3.580154013s
        Error: collectChain syncMessages: message processing failed: validating block bafy2bzaceadtb2pckmlruuvrsyrtettnkvcub2e3qo5dottmlie7kv7q6gl6c: parent state root did not match computed state (bafy2bzacedg2zxhg3islwohkympv4xycl6r47ml7zknlay5fdxi5kmdkmpv4e != bafy2bzaceald5wa4yeycq6mblb7p4mz6vweuzxvsm7i7ljys626yotpexd6mu)

**Comment by arajasek** [comment] 2020-05-14 21:27
Duplicate of #1599, unless I'm mistaken.

**Closed by arajasek** 2020-05-14 21:27 UTC
