### ISSUE TITLE
Retrieval failed with zero bytes

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#1794] opened 2020-05-19 16:46 UTC
Asked for more details from reporter, but here's another "hmm, that's a retrieval issue". 

![image](https://user-images.githubusercontent.com/6530144/82354291-a17f2b00-99ce-11ea-9a2c-1084020558b2.png)

**Comment by hannahhoward** [comment] 2020-05-19 19:05
This error comes from:
https://github.com/filecoin-project/lotus/blob/master/node/impl/client/client.go#L316
which happens before even starting the retrieval.

The offer comes from the results of querying miners the client stored data with (ClientFindData). 

However, one thing that seems very odd:
https://github.com/filecoin-project/lotus/blob/master/node/impl/client/client.go#L206

If the miner responds with an error, it gets put in the offer list, but then the retrieve CLI just picks the first offer, even if it’s an error:
https://github.com/filecoin-project/lotus/blob/master/cli/client.go#L391

It seems like the first thing to figuring out what is going wrong is rather than just check that there are >0 offers:
https://github.com/filecoin-project/lotus/blob/master/cli/client.go#L382

It should check that there are greater than >0 offers w/o errors, and if not, print out the errors on the offers.

**Comment by hannahhoward** [comment] 2020-05-19 19:05
My guess is that the root cause is for whatever reason the miner went offline, but we can't really tell till we can inspect this.

**Comment by jennijuju** [comment] 2021-02-11 08:24
Seems like there is no way we can inspect this, closing for now

**Closed by jennijuju** 2021-02-11 08:24 UTC
Labels: area/markets
