### ISSUE TITLE
WinningPost problem: mined new block but no rewards

### ISSUE THREAD

**Issue by coinmini** [filecoin-project/lotus#4300] opened 2020-10-10 14:21 UTC
Hi, need help about WinningPost, we have not mined new blocks for newly one week. our power is 40T.  miner.log  shows totally 36  mined blocks by now.   6 of mined blocks do not get the rewards and cannot find the block cid at explorer. one of the logs is like the normal one :  
```
{"level":"info","ts":"2020-10-09T22:34:06.308+0800","logger":"storageminer","caller":"storage/miner.go:243","msg":"Computing WinningPoSt ;[{SealProof:3 SectorNumber:1062 SealedCID:bagboea4b5abcbiue4ocnck6h7jqbswaw7qpzrqwpct3diailesudlryzgsd3vmiy}]; [69 233 141 49 24 154 33 9 229 151 87 241 185 88 147 236 251 122 52 255 37 95 225 103 228 57 222 177 55 189 50 80]"}
{"level":"info","ts":"2020-10-09T22:34:10.213+0800","logger":"storageminer","caller":"storage/miner.go:250","msg":"GenerateWinningPoSt took 3.904633021s"}
{"level":"info","ts":"2020-10-09T22:34:10.611+0800","logger":"miner","caller":"miner/miner.go:442","msg":"mined new block","cid":"bafy2bzacebp7hxsgwzfged75lq2c6kskdho5iuskskuv3a2pxxycyu44cjizs","height":"131589","miner":"f08157","parents":["f02633"],"took":4.336271034} 
```
need help thanks  by the way, our lotus version is always set for  new one

**Comment by hyunmoon** [comment] 2020-10-11 23:26
Same issue. This is a very urgent one.

**Comment by whyrusleeping** [comment] 2020-10-11 23:49
@coinmini if you mined a block but it doesnt show up in the chain explorer, that means your block didnt get included in the chain by other miners. When you notice this happen, check `lotus chain list --height=HEIGHTYOUMINED`.

Looking for just the block that you pasted the log for, I see only two blocks in the main chain at that height:
```
131589: (Oct  9 07:34:30) [ bafy2bzacedgpjhstr3rjchet6xj2qjmikzdqb5wgn72sw4nsw26goyissfug4: f020330,bafy2bzaceax5tdsew676budwni4d3a2yffriwp562x6o7kmzorndgfjmibp52: f01235, ]
```

This means that the next miners to create a tipset did not include your block, the following tipset is:
```
131590: (Oct  9 07:35:00) [ bafy2bzacebkjvyqao2jqhfvy4fnucizd2vwt4zmtvxmlq52vq47zonpz4j6du: f02609,bafy2bzacedmpl2otkzsh7sywixamsw2lmxcfrxdcvhgq5uxb22nto3plpfwc4: f010493,bafy2bzaced6cjyaqltos6gkijq3up2lcfky7zecls7irbjprkv2tcsakx3gfw: f02775,bafy2bzaceconv5t4mkv5sstl77zxgjto547dkwgwlb5myhrp4axz52luktwnc: f02528,bafy2bzacebh2yqmre2nx6wyjqv57jgrqvrzxnx2ejjdvgeaq5vdi2mplyjss2: f014569, ]
```

Most of the time, I see this because of bad network propagation. If youre sure your internet connection is good, then I would check to see if your lotus daemon has a negative gossip score. You can do this by looking for your lotus nodes (not your miners) peer ID in the output of `lotus net scores` on a different node. If you find your peer ID in the output of this command and it has a negative score, this means that your node is getting penalized in the gossip mesh for some reason, This can happen for a few different reasons, all related to spam prevention (remember all the spam we used to have? Its mostly gone now because of this...).
The first thing to check is to make sure that you don't have multiple lotus nodes running under the same IP address. Once you have 5 lotus nodes on the same IP address, other peers in the network will start to think you are trying to sybil attack the network, and penalize you in their mesh.
You might also get penalized if you send lots of bad messages, so check to make sure you don't have anything weird going on thats sending bad messages.

**Comment by mostcute** [comment] 2020-10-12 18:15
> @coinmini if you mined a block but it doesnt show up in the chain explorer, that means your block didnt get included in the chain by other miners. When you notice this happen, check `lotus chain list --height=HEIGHTYOUMINED`.
> 
> Looking for just the block that you pasted the log for, I see only two blocks in the main chain at that height:
> 
> ```
> 131589: (Oct  9 07:34:30) [ bafy2bzacedgpjhstr3rjchet6xj2qjmikzdqb5wgn72sw4nsw26goyissfug4: f020330,bafy2bzaceax5tdsew676budwni4d3a2yffriwp562x6o7kmzorndgfjmibp52: f01235, ]
> ```
> 
> This means that the next miners to create a tipset did not include your block, the following tipset is:
> 
> ```
> 131590: (Oct  9 07:35:00) [ bafy2bzacebkjvyqao2jqhfvy4fnucizd2vwt4zmtvxmlq52vq47zonpz4j6du: f02609,bafy2bzacedmpl2otkzsh7sywixamsw2lmxcfrxdcvhgq5uxb22nto3plpfwc4: f010493,bafy2bzaced6cjyaqltos6gkijq3up2lcfky7zecls7irbjprkv2tcsakx3gfw: f02775,bafy2bzaceconv5t4mkv5sstl77zxgjto547dkwgwlb5myhrp4axz52luktwnc: f02528,bafy2bzacebh2yqmre2nx6wyjqv57jgrqvrzxnx2ejjdvgeaq5vdi2mplyjss2: f014569, ]
> ```
> 
> Most of the time, I see this because of bad network propagation. If youre sure your internet connection is good, then I would check to see if your lotus daemon has a negative gossip score. You can do this by looking for your lotus nodes (not your miners) peer ID in the output of `lotus net scores` on a different node. If you find your peer ID in the output of this command and it has a negative score, this means that your node is getting penalized in the gossip mesh for some reason, This can happen for a few different reasons, all related to spam prevention (remember all the spam we used to have? Its mostly gone now because of this...).
> The first thing to check is to make sure that you don't have multiple lotus nodes running under the same IP address. Once you have 5 lotus nodes on the same IP address, other peers in the network will start to think you are trying to sybil attack the network, and penalize you in their mesh.
> You might also get penalized if you send lots of bad messages, so check to make sure you don't have anything weird going on thats sending bad messages.

can chage the ip for a daemon fix the problem? i have two daemon and two miner in the same network. your word "nodes" doesn't include miner right?

**Comment by coinmini** [comment] 2020-10-13 07:32
@whyrusleeping  i checked after your words.  Its true that daemon node was penalized  since lotus net scores was negative before. We mined normally these 4 days and the net scores is 0.000000.  we only have one daemon node under one ip at the beginning of the sr1. lets see next days. Thanks man.

**Comment by irocn** [comment] 2020-10-21 13:37
@whyrusleeping Thanks for your comments, I have same problem. I found some "mined new block"  and don't get reward. I also find `lotus net score` output some negative score. then how to improve the score? I still don't get reward after I power off miner for 1 hours and power on.

**Comment by whyrusleeping** [comment] 2020-10-21 17:25
@irocn usually the score gets penalized because youre running too many lotus nodes behind the same IP address. The solution is to run fewer lotus nodes behind the same IP address.

**Comment by irocn** [comment] 2020-10-22 05:57
@whyrusleeping Actually only one lotus nodes behind the IP address. I found some negative score after run **lotus net score**, miner's power > 200T but more than 5 days I don't get reward. like @coinmini some log of miner is below.
```
17999678:2020-10-19T17:45:48.648+0800   INFO    miner   miner/miner.go:444      mined new block {"cid": "bafy2bzacedlke744on7jmmxkk7yxleokrmmxq2ztqihx63usuuxcmh57zpkjs", "height": "159812", "miner": "f010010", "parents": ["f02490","f05316","f01231","f01235"], "took": 12.645046879}
18067893:2020-10-19T18:50:48.430+0800   INFO    miner   miner/miner.go:444      mined new block {"cid": "bafy2bzaceab3qulps6raxk5rvh7g5iejs2gsyhufoo5qayqgyfpkanb6iof2e", "height": "159942", "miner": "f010010", "parents": ["f02775","f01782","f02614","f02626"], "took": 12.426256843}
21408355:2020-10-21T13:04:48.050+0800   INFO    miner   miner/miner.go:444      mined new block {"cid": "bafy2bzacebhecrj3an4orppwx5fgd3vg7w45q254ixzmpzwlkq6p6zqkgbefa", "height": "165010", "miner": "f010010", "parents": ["f03275","f02520","f014386","f01248","f020522"], "took": 11.760752827}
21875199:2020-10-21T17:16:48.806+0800   INFO    miner   miner/miner.go:444      mined new block {"cid": "bafy2bzaceaqfq5mzt7py4la7xrb2zidi2xgu6i4k2yrjoa7jbqn7nezaao56y", "height": "165514", "miner": "f010010", "parents": ["f020330","f017242","f024137"], "took": 12.4011113}
22619655:2020-10-21T23:42:21.289+0800   INFO    miner   miner/miner.go:444      mined new block {"cid": "bafy2bzacecihuczyh6e5tgeui3lb2irgpjo6eymxrf6meyoeg4q5tbmdshlm4", "height": "166285", "miner": "f010010", "parents": ["f02770","f01248","f02838","f02416"], "took": 15.151637043}
23642422:2020-10-22T08:49:48.046+0800   INFO    miner   miner/miner.go:444      mined new block {"cid": "bafy2bzaceddkf7zfxlkfsy26zishuw6xizvcptivwlz4gvgl2zjxd4ykegnri", "height": "167380", "miner": "f010010", "parents": ["f02303","f02770","f08025"], "took": 12.042230837}
```

**Comment by rjan90** [comment] 2022-04-14 07:16
Hey!

Most of the time when the miner-logs indicate that you have mined a block - but it its not included by the chain (and you get no reward), it is most likely because you where missing a parent block.

Closing this issue now as it´s a duplicate of https://github.com/filecoin-project/lotus/issues/5128#issuecomment-746751808

**Closed by rjan90** 2022-04-14 07:16 UTC
