### ISSUE TITLE
Update from v0.10.0 to v0.10.1 panics

### ISSUE THREAD

**Issue by jsign** [filecoin-project/lotus#4400] opened 2020-10-14 18:51 UTC
Log:
```
Oct 14 18:46:13 spaceracetwo30 lotus[11929]: 2020-10-14T18:46:13.947Z        INFO        markets        loggers/loggers.go:14        storage event        {"name": "ClientEventRestart", "proposal CID": "bafyreibfktn5urhqyhbmoxsnvmjgxmwhmlvs3gjnwsfst4vt7yy5myzj2u", "state": "StorageDealActive", "message": ""}
Oct 14 18:46:13 spaceracetwo30 lotus[11929]: 2020-10-14T18:46:13.947Z        INFO        markets        loggers/loggers.go:14        storage event        {"name": "ClientEventRestart", "proposal CID": "bafyreibmbnnuglrzhn27jvkap6y2p5knan3gjnnbkaxv6ao3hioycolh4e", "state": "StorageDealActive", "message": ""}
Oct 14 18:46:13 spaceracetwo30 lotus[11929]: 2020-10-14T18:46:13.948Z        INFO        markets        loggers/loggers.go:14        storage event        {"name": "ClientEventRestart", "proposal CID": "bafyreibncqapiwyvattftvfprmp74vmu47t5jycyvs7ktkejok57dv4maa", "state": "StorageDealActive", "message": ""}
Oct 14 18:46:13 spaceracetwo30 lotus[11929]: 2020-10-14T18:46:13.948Z        INFO        markets        loggers/loggers.go:14        storage event        {"name": "ClientEventRestart", "proposal CID": "bafyreicgx5dtvoyjegid2rvojrbnhxpy2cbcse2uxls7iryuir3mgruv5m", "state": "StorageDealActive", "message": ""}
Oct 14 18:46:13 spaceracetwo30 lotus[11929]: 2020-10-14T18:46:13.949Z        INFO        markets        loggers/loggers.go:14        storage event        {"name": "ClientEventRestart", "proposal CID": "bafyreicset5s5f6q2yxr5iickgyp6zbcggoq4inolbzvti3glncyhfsxcu", "state": "StorageDealClientTransferRestart", "message": ""}
Oct 14 18:46:13 spaceracetwo30 lotus[11929]: 2020-10-14T18:46:13.949Z        INFO        markets        loggers/loggers.go:14        storage event        {"name": "ClientEventRestart", "proposal CID": "bafyreiehyatemezpembvwhgmzgpbssfmuwjmsuzhbp4barj3cmx76rz3pi", "state": "StorageDealActive", "message": ""}
Oct 14 18:46:13 spaceracetwo30 lotus[11929]: 2020-10-14T18:46:13.950Z        INFO        markets        loggers/loggers.go:14        storage event        {"name": "ClientEventRestart", "proposal CID": "bafyreifbiln3jaqi7znryc5vehggsqgb6p27qlgclrgysgfihimfq66unm", "state": "StorageDealActive", "message": ""}
Oct 14 18:46:13 spaceracetwo30 lotus[11929]: 2020-10-14T18:46:13.950Z        INFO        markets        loggers/loggers.go:14        storage event        {"name": "ClientEventRestart", "proposal CID": "bafyreigtuke24ml7lsf276676yubcwzswfifgveiaq4l5bvwbgwvofusze", "state": "StorageDealActive", "message": ""}
Oct 14 18:46:13 spaceracetwo30 lotus[11929]: 2020-10-14T18:46:13.954Z        INFO        storagemarket_impl        clientstates/client_states.go:146        restarting data transfer for deal deal bafyreicset5s5f6q2yxr5iickgyp6zbcggoq4inolbzvti3glncyhfsxcu
Oct 14 18:46:13 spaceracetwo30 lotus[11929]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 14 18:46:13 spaceracetwo30 lotus[11929]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17e964d]
Oct 14 18:46:13 spaceracetwo30 lotus[11929]: goroutine 28408 [running]:
Oct 14 18:46:13 spaceracetwo30 lotus[11929]: github.com/filecoin-project/go-fil-markets/storagemarket/impl/clientstates.RestartDataTransfer(0x7fc22c6b33a8, 0xc09cc82000, 0x7fc22c6b33d0, 0xc000631ca0, 0xc09c99b620, 0x27, 0x4000000, 0x0, 0xc09c743480, 0x31, ...)
Oct 14 18:46:13 spaceracetwo30 lotus[11929]:         /home/azureuser/go/pkg/mod/github.com/filecoin-project/go-fil-markets@v0.9.0/storagemarket/impl/clientstates/client_states.go:151 +0xed
Oct 14 18:46:13 spaceracetwo30 lotus[11929]: reflect.Value.call(0x2ab5000, 0x2f7f918, 0x13, 0x2dc063f, 0x4, 0xc0007bb718, 0x3, 0x3, 0x52555f, 0x2c591e0, ...)
Oct 14 18:46:13 spaceracetwo30 lotus[11929]:         /usr/local/go/src/reflect/value.go:475 +0x8c7
Oct 14 18:46:13 spaceracetwo30 lotus[11929]: reflect.Value.Call(0x2ab5000, 0x2f7f918, 0x13, 0xc0ca095718, 0x3, 0x3, 0xc0ca0956d0, 0x53325e, 0x7fc22fe53000)
Oct 14 18:46:13 spaceracetwo30 lotus[11929]:         /usr/local/go/src/reflect/value.go:336 +0xb9
Oct 14 18:46:13 spaceracetwo30 lotus[11929]: github.com/filecoin-project/go-statemachine/fsm.fsmHandler.handler.func1(0xc09ca7e000, 0x2, 0x2, 0xc09ca7e000, 0x756ea107fbc658, 0x10)
Oct 14 18:46:13 spaceracetwo30 lotus[11929]:         /home/azureuser/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200925024713-05bd7c71fbfe/fsm/fsm.go:170 +0x437
Oct 14 18:46:13 spaceracetwo30 lotus[11929]: reflect.callReflect(0xc09c99d4d0, 0xc0007bb9e0, 0xc0007bb9c8)
Oct 14 18:46:13 spaceracetwo30 lotus[11929]:         /usr/local/go/src/reflect/value.go:564 +0x32a
Oct 14 18:46:13 spaceracetwo30 lotus[11929]: reflect.makeFuncStub(0x31741c0, 0xc00003e030, 0xc0888b6000, 0xc09c99b620, 0x27, 0x4000000, 0x0, 0xc09c743480, 0x31, 0xc09bacd910, ...)
Oct 14 18:46:13 spaceracetwo30 lotus[11929]:         /usr/local/go/src/reflect/asm_amd64.s:20 +0x42
Oct 14 18:46:13 spaceracetwo30 lotus[11929]: reflect.Value.call(0xc09c61d6e0, 0xc09c99d4d0, 0x13, 0x2dc063f, 0x4, 0xc0ca095f70, 0x2, 0x2, 0x52555f, 0x2b8e620, ...)
Oct 14 18:46:13 spaceracetwo30 lotus[11929]:         /usr/local/go/src/reflect/value.go:475 +0x8c7
Oct 14 18:46:13 spaceracetwo30 lotus[11929]: reflect.Value.Call(0xc09c61d6e0, 0xc09c99d4d0, 0x13, 0xc09c4b8f70, 0x2, 0x2, 0x4d4d, 0x656064072002e4a0, 0x2c88bb494d84785f)
Oct 14 18:46:13 spaceracetwo30 lotus[11929]:         /usr/local/go/src/reflect/value.go:336 +0xb9
Oct 14 18:46:13 spaceracetwo30 lotus[11929]: github.com/filecoin-project/go-statemachine.(*StateMachine).run.func3(0xc08ad66990, 0x31741c0, 0xc00003e030, 0xc0888b6000, 0xc08ad669a0, 0xc09c15fda0)
Oct 14 18:46:13 spaceracetwo30 lotus[11929]:         /home/azureuser/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200925024713-05bd7c71fbfe/machine.go:102 +0x2c8
Oct 14 18:46:13 spaceracetwo30 lotus[11929]: created by github.com/filecoin-project/go-statemachine.(*StateMachine).run
Oct 14 18:46:13 spaceracetwo30 lotus[11929]:         /home/azureuser/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200925024713-05bd7c71fbfe/machine.go:100 +0x3f2
```

**Comment by hannahhoward** [comment] 2020-10-14 19:53
hey @jsign can you confirm if this happened immediately on node startup when you upgraded?

**Comment by jsign** [comment] 2020-10-14 19:58
@hannahhoward , yes, right at the start.

**Comment by hannahhoward** [comment] 2020-10-14 20:14
yea, total fail on my part. The issue is you had a deal that was in the middle of transferring at the time you shut down for the upgrade. There is no way to restart it -- we need to fail that deal. But we should should not be panic'ing! Anyway, it's a simple fix that we should not have let get through.

**Comment by jsign** [comment] 2020-10-14 20:21
Cool, no problem. Happy to catch this one pretty quickly on release.
Some new v0.10.2 will be tagged whenever that fix gets in?

**Comment by hannahhoward** [comment] 2020-10-14 20:21
Yep https://github.com/filecoin-project/lotus/pull/4402

**Comment by hannahhoward** [comment] 2020-10-14 20:22
Thank you so much for catching this before we sent out a panic'y release as the last one before mainnet!

**Comment by kenshyx** [comment] 2020-10-14 20:24
see also https://github.com/filecoin-project/lotus/issues/4394

**Closed** 2020-10-24 14:24 UTC
