### ISSUE TITLE
Slow/Stuck response on : Filecoin.ClientRetrieve

### ISSUE THREAD

**Issue by stefangeorgerobert** [filecoin-project/lotus#3813] opened 2020-09-13 16:21 UTC
**Describe the bug**
From some retrieval deals the response of ClientRetrieve is very slow or stuck.

**To Reproduce**
This is reproduced using the deal bot.

**Expected behavior**
N/A

**Screenshots**
2020-09-13T15:50:25.544Z	WARN	rpc	go-jsonrpc@v0.1.2-0.20200822201400-474f4fdccc52/handler.go:241	error in RPC call to 'Filecoin.ClientRetrieve': retrieval failed: Retrieve: Retrieval Error: Provider cancelled retrieval due to error:
    github.com/filecoin-project/lotus/node/impl/client.(*API).ClientRetrieve
        /go/lotus/node/impl/client/client.go:438

**Version (run `lotus version`):**
Daemon:  0.7.0+git.bb1d0d4+api0.14.0
Local: lotus version 0.7.0+git.bb1d0d4

**Additional context**
N/A
[slow.log](https://github.com/filecoin-project/lotus/files/5214547/slow.log)

**Comment by Storage-Hive** [comment] 2020-09-13 17:56
I had same issue happen on Sep 7th with 5 retrievals in a row, details below:

retrieve		bafk2...ayvqg	n/a	100	n/a	{"code":1,"message":"retrieval failed: Retrieve: Retrieval Error: Provider cancelled retrieval due to error"} ClientMinerQueryOffer: {"jsonrpc":"2.0","result":{"Err":"","Root":{"/":"bafk2bzacebtpsvy2gdxke673vpjjxy2r5i65dcmhyioxxrkaspbcgw47ayvqg"},"Piece":null,"Size":131072,"MinPrice":"262144","UnsealPrice":"0","PaymentInterval":1048576,"PaymentIntervalIncrease":1048576,"Miner":"t07849","MinerPeer":{"Address":"t010438","ID":"12D3KooWNhnmMppxhU9nWyn3GeLQEcKrtczdA6tQcrYUh1RrTY5k","PieceCID":null}},"id":0}	Mon, 07 Sep 2020 16:53:00 GMT
retrieve		bafk2...hk7nw	n/a	100	n/a	{"code":1,"message":"retrieval failed: Retrieve: Retrieval Error: Provider cancelled retrieval due to error"} ClientMinerQueryOffer: {"jsonrpc":"2.0","result":{"Err":"","Root":{"/":"bafk2bzacedomruhvcha4hlowj7qudxfquhjyxl7acnxmerrlwwtubv4qhk7nw"},"Piece":null,"Size":131072,"MinPrice":"262144","UnsealPrice":"0","PaymentInterval":1048576,"PaymentIntervalIncrease":1048576,"Miner":"t07849","MinerPeer":{"Address":"t010438","ID":"12D3KooWNhnmMppxhU9nWyn3GeLQEcKrtczdA6tQcrYUh1RrTY5k","PieceCID":null}},"id":0}	Mon, 07 Sep 2020 14:44:34 GMT
retrieve		bafk2...6munk	n/a	100	n/a	{"code":1,"message":"retrieval failed: Retrieve: Retrieval Error: Provider cancelled retrieval due to error"} ClientMinerQueryOffer: {"jsonrpc":"2.0","result":{"Err":"","Root":{"/":"bafk2bzacedzshbw4xkwrvrq4zbxbpecvxvoooaystaxiosapidrafb7u6munk"},"Piece":null,"Size":131072,"MinPrice":"262144","UnsealPrice":"0","PaymentInterval":1048576,"PaymentIntervalIncrease":1048576,"Miner":"t07849","MinerPeer":{"Address":"t010438","ID":"12D3KooWNhnmMppxhU9nWyn3GeLQEcKrtczdA6tQcrYUh1RrTY5k","PieceCID":null}},"id":0}	Mon, 07 Sep 2020 15:47:04 GMT
retrieve		bafk2...3qg5i	n/a	100	n/a	{"code":1,"message":"retrieval failed: Retrieve: Retrieval Error: Provider cancelled retrieval due to error"} ClientMinerQueryOffer: {"jsonrpc":"2.0","result":{"Err":"","Root":{"/":"bafk2bzacebw6kwcowydmiriimkoreejhf5g4d2hvu5hd5ty7i65xxayx3qg5i"},"Piece":null,"Size":131072,"MinPrice":"262144","UnsealPrice":"0","PaymentInterval":1048576,"PaymentIntervalIncrease":1048576,"Miner":"t07849","MinerPeer":{"Address":"t010438","ID":"12D3KooWNhnmMppxhU9nWyn3GeLQEcKrtczdA6tQcrYUh1RrTY5k","PieceCID":null}},"id":0}	Mon, 07 Sep 2020 13:34:04 GMT
retrieve		bafyk...mtxj4	n/a	104857600	n/a	{"code":1,"message":"retrieval failed: Retrieve: Retrieval Error: Provider cancelled retrieval due to error"} ClientMinerQueryOffer: {"jsonrpc":"2.0","result":{"Err":"","Root":{"/":"bafykbzacebd7m5q57v2dq4vs25kytv4rqevminfgkdsj2aw6judho6tcmtxj4"},"Piece":null,"Size":134217728,"MinPrice":"268435456","UnsealPrice":"0","PaymentInterval":1048576,"PaymentIntervalIncrease":1048576,"Miner":"t07849","MinerPeer":{"Address":"t010438","ID":"12D3KooWNhnmMppxhU9nWyn3GeLQEcKrtczdA6tQcrYUh1RrTY5k","PieceCID":null}},"id":0}	Mon, 07 Sep 2020 17:55:42 GMT

**Comment by Reiers** [comment] 2022-04-18 18:51
**Hi @stefangeorgerobert** 

Thanks for the report. The issue is old and things are stable in the[ current release. ](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1)

Closing ticket.

If you are still experiencing problems, open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

**Closed by Reiers** 2022-04-18 18:51 UTC
