### ISSUE TITLE
Error: Message: adding market funds failed: AddFunds err: failed to load message: blockstore: block not found

### ISSUE THREAD

**Issue by dineshshenoy** [filecoin-project/lotus#4828] opened 2020-11-12 16:27 UTC
I was doing release testing for 1.1.3-pre1 and have my deals blocked as "StorageDealClientFunding" and "StorageDealReserveClientFunds".

| DealCid |     DealId |  Provider |  State |                          On Chain? |         Slashed? |  PieceCID |     Size |       Price | Duration |  Verified |  
| ...dra6luoq  | 894696  | f023009   | StorageDealActive             | Y (epoch 167306) |  N |         ...gw663ufi  | 1.984 MiB|  0 FIL |                     523423  |  false |     
| ...5bd5tpsq  | 0       | f02665    | StorageDealClientFunding      | N |                 N |         ...s7gjcidi  | 1.984 MiB|  0.000001016842252814 FIL |  1041247 |   false |     
| ...caajcfte  | 0       | f02665    | StorageDealReserveClientFunds |  N |                 N |         ...ds747why  | 254 MiB|    0.000130155875 FIL |        1041247 |   false |     
| ...jh6vlnti  | 0       | f02665    | StorageDealReserveClientFunds |  N |                 N |         ...5swxloha  | 7.938 GiB|  0.004164988 FIL |           1041247 |   false |     
| ...d3hpci4u  | 0       | f02665    | StorageDealReserveClientFunds |  N |                 N |         ...ezu6f2ka  | 31.75 GiB|  0.016659952 FIL |           1041247 |   false |     

How can i unblock these 4 deals?

**Comment by arajasek** [comment] 2020-11-12 22:31
Caused becuase the daemon in question was not fully synced.

**Comment by dineshshenoy** [comment] 2020-11-13 00:44
I'm still seeing this issue after the chain sync caught up;

DealCid      DealId  Provider  State                          On Chain?         Slashed?  PieceCID     Size       Price                     Duration  Verified  
...5bd5tpsq  0       f02665    StorageDealFailing             N                 N         ...s7gjcidi  1.984 MiB  0.000001016842252814 FIL  1041247   false     
  Message: adding market funds failed: AddFunds err: failed to load message: blockstore: block not found
...caajcfte  0       f02665    StorageDealFailing             N                 N         ...ds747why  254 MiB    0.000130155875 FIL        1041247   false     
  Message: adding market funds failed: AddFunds err: failed to load message: blockstore: block not found
...jh6vlnti  0       f02665    StorageDealClientFunding       N                 N         ...5swxloha  7.938 GiB  0.004164988 FIL           1041247   false     
...d3hpci4u  0       f02665    StorageDealReserveClientFunds  N                 N         ...ezu6f2ka  31.75 GiB  0.016659952 FIL           1041247   false     

The first two led to AddFunds err.  Maybe that's what's blockign the second two deals?

**Comment by jennijuju** [comment] 2020-11-13 01:58
User removed the chain data store which causes the node does not have the receipt state for the ensure fund message that’s why the deal is stuck in this states on the client side.

**Comment by jennijuju** [comment] 2020-11-13 01:58
It will be interesting to see on the miner side what the deal status is tho.

**Comment by hannahhoward** [comment] 2020-11-13 16:58
Guys I caused this issue when I was debugging @dineshshenoy's miner it's not a bug.

It will not be on the miner's side.

**Comment by hannahhoward** [comment] 2020-11-13 17:00
I am concerned about the one stuck in ClientFunding - there's a message in MPool that's stuck there and I don't fully understand why.

That said I ran some commands I probably should have like `lotus mpool clear` so I wouldn't attribute much here.

**Comment by hannahhoward** [comment] 2020-11-13 17:01
i also deleted @dineshshenoy's entire chainstore and reimported from snapshot, FYI.

**Closed** 2020-11-13 17:00 UTC
Labels: area/markets, kind/bug
