### ISSUE TITLE
Storage providers should never accept 540-day deals

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#7093] opened 2021-08-16 18:33 UTC
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated improvement to propose.

### Lotus component

lotus miner/market - storage deal

### Improvement Suggestion

Maybe I'm missing something but because `max sector lifetime = max deal lifetime = 540 days`, it's nearly impossible to ever actually activate a deal of 540 days -- I think your sector has to be activated at precisely the deal start epoch in order to succeed. Any earlier and the sector has an invalidly long lifetime, any later and the deal wasn't activated on time.

If this is true, let's just modify Lotus storage providers to never consider 540 day deals.

**Comment by raulk** [comment] 2021-08-16 19:24
Is this issue significantly different than #6959?

**Comment by raulk** [comment] 2021-08-17 11:36
Closing as a duplicate of #6959, which has a more detailed explanation. Please reopen if this issue is substantially different.

**Closed by raulk** 2021-08-17 11:36 UTC
Labels: need/triage, kind/enhancement
