### ISSUE TITLE
SectorPreCommitBatch fails with _total sector lifetime must exceed_ error

### ISSUE THREAD

**Issue by jburnett** [filecoin-project/lotus#6699] opened 2021-07-08 00:20 UTC
**Describe the problem**
Publishing sectors in SubmitPreCommitBatch state end in PreCommitFailed state with _total sector lifetime must exceed_ error.

**Version**
Daemon:  1.10.0+mainnet+git.764fa9dae.dirty+api1.0.1
Local: lotus-miner version 1.10.0+mainnet+git.764fa9dae.dirty

**Setup**
Lotus node and miner on AMD 7402 w/256 GB RAM + Quadro M5000.  Lotus-worker on AMD 7262 w/384 GB RAM + Quadro M5000.

**Commands**
Sectors in _SubmitPreCommitBatch_; attempt to publish

`lotus-miner sectors batching precommit --publish-now`

Same sectors go to _PreCommitFailed_, then back to _SubmitPreCommitBatch_

**Sectors status**
```
20.	2021-07-07 19:20:45 -0400 EDT:	[event;sealing.SectorRetryPreCommit]	{"User":{}}
21.	2021-07-07 19:20:45 -0400 EDT:	[event;sealing.SectorPreCommitBatch]	{"User":{}}
22.	2021-07-07 20:02:58 -0400 EDT:	[event;sealing.SectorChainPreCommitFailed]	{"User":{}}
	precommit batch error: sending message failed: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 16, reason: invalid expiration 1518081, total sector lifetime (518326) must exceed 518400 after activation 999755 (RetCode=16)
23.	2021-07-07 20:03:58 -0400 EDT:	[event;sealing.SectorRetryPreCommit]	{"User":{}}
24.	2021-07-07 20:03:58 -0400 EDT:	[event;sealing.SectorPreCommitBatch]	{"User":{}}
```

**Lotus miner logs**

`# grep " 191" /lotus-log/miner.log `

```
{"level":"debug","ts":"2021-07-07T10:22:12.010-0400","logger":"advmgr","caller":"sector-storage/sched.go:465","msg":"SCHED try assign sqi:3 sector 191 to window 0"}
{"level":"debug","ts":"2021-07-07T10:22:12.010-0400","logger":"advmgr","caller":"sector-storage/sched.go:472","msg":"SCHED ASSIGNED sqi:3 sector 191 task seal/v0/precommit/1 to window 0"}
{"level":"debug","ts":"2021-07-07T10:22:12.010-0400","logger":"advmgr","caller":"sector-storage/sched_worker.go:368","msg":"assign worker sector 191"}
{"level":"debug","ts":"2021-07-07T10:22:58.534-0400","logger":"advmgr","caller":"sector-storage/worker_local.go:129","msg":"acquired sector {{221135 191} 8} (e:1; a:0): {{0 0} /mnt/scratch1/fcseal1/unsealed/s-t0221135-191  }"}
{"level":"warn","ts":"2021-07-07T10:23:09.416-0400","logger":"sectors","caller":"storage-sealing/fsm.go:607","msg":"sector 191 got error event sealing.SectorSealPreCommit1Failed: seal pre commit(1) failed: storage call error 0: acquiring sector paths: local acquire error: couldn't find a suitable path for a sector"}
{"level":"debug","ts":"2021-07-07T12:30:06.546-0400","logger":"advmgr","caller":"sector-storage/sched.go:465","msg":"SCHED try assign sqi:3 sector 191 to window 2"}
{"level":"debug","ts":"2021-07-07T12:30:06.546-0400","logger":"advmgr","caller":"sector-storage/sched.go:472","msg":"SCHED ASSIGNED sqi:3 sector 191 task seal/v0/precommit/1 to window 2"}
{"level":"debug","ts":"2021-07-07T12:30:06.546-0400","logger":"advmgr","caller":"sector-storage/sched_worker.go:368","msg":"assign worker sector 191"}
{"level":"debug","ts":"2021-07-07T17:40:43.734-0400","logger":"advmgr","caller":"sector-storage/sched.go:465","msg":"SCHED try assign sqi:3 sector 191 to window 1"}
{"level":"debug","ts":"2021-07-07T17:40:43.734-0400","logger":"advmgr","caller":"sector-storage/sched.go:472","msg":"SCHED ASSIGNED sqi:3 sector 191 task seal/v0/precommit/2 to window 1"}
{"level":"debug","ts":"2021-07-07T17:40:43.734-0400","logger":"advmgr","caller":"sector-storage/sched_worker.go:368","msg":"assign worker sector 191"}
{"level":"warn","ts":"2021-07-07T19:19:45.042-0400","logger":"sectors","caller":"storage-sealing/fsm.go:607","msg":"sector 191 got error event sealing.SectorChainPreCommitFailed: precommit batch error: sending message failed: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 16, reason: invalid expiration 1518028, total sector lifetime (518359) must exceed 518400 after activation 999669 (RetCode=16)"}
{"level":"warn","ts":"2021-07-07T20:02:58.158-0400","logger":"sectors","caller":"storage-sealing/fsm.go:607","msg":"sector 191 got error event sealing.SectorChainPreCommitFailed: precommit batch error: sending message failed: GasEstimateMessageGas error: estimating gas used: message execution failed: exit 16, reason: invalid expiration 1518081, total sector lifetime (518326) must exceed 518400 after activation 999755 (RetCode=16)"}

```

**Lotus miner diagnostic info**

[lotus-miner diagnostic info](https://github.com/GranaryTree/community/blob/e021bf9f8c6684294f14290c121dd8b13835b569/issues/20210707%20allinfo.txt)

** Code modifications **
none

**Comment by Reiers** [comment] 2022-04-11 19:12
Hi @jburnett 

At first glance it looks like your `BatchGasFee` is set to low in your `config.toml`, and Im not able to reproduce the issue here.

- Also I noticed that you are running a `.dirty` version of lotus - this is not something we can take a closer look at with changes done to the code. 
```
Daemon: 1.10.0+mainnet+git.764fa9dae.dirty+api1.0.1
Local: lotus-miner version 1.10.0+mainnet+git.764fa9dae.dirty
```

**Please upgrade to stock Lotus**

Closing issue ticket.

If you are still experiencing this problem in current release, open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

Many thanks !!

**Closed by Reiers** 2022-04-11 19:12 UTC
Labels: need/triage, area/sealing
