### ISSUE TITLE
lotus-miner keeps crashing

### ISSUE THREAD

**Issue by Jason-Cui** [filecoin-project/lotus#9039] opened 2022-07-14 22:54 UTC
lotus-miner process v1.16.0 crashed twice in 10 days since the upgrade.

2022-07-11T06:42:48.491 INFO storage_proofs_post::fallback::vanilla > proving partition range 0
2022-07-11T06:42:48.630 INFO storage_proofs_post::fallback::vanilla > proving partition range 1
2022-07-11T06:42:48.764 INFO storage_proofs_post::fallback::vanilla > proving partition range 2
memory allocation of 11316800 bytes failed
SIGABRT: abort
PC=0x7f38d0d7018b m=217 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 19890425 [syscall, 2 minutes]:
runtime.cgocall(0x22ccaa0, 0xc002b40e98)
	/snap/go/9848/src/runtime/cgocall.go:157 +0x5c fp=0xc002b40e60 sp=0xc002b40e28 pc=0x6fbb7c
github.com/filecoin-project/filecoin-ffi/cgo._Cfunc_generate_window_post(0xc02e801e60, {0xc044080000, 0x1ba1}, 0xc02e801e40)
	_cgo_gotypes.go:1258 +0x4d fp=0xc002b40e98 sp=0xc002b40e60 pc=0x155e06d
github.com/filecoin-project/filecoin-ffi/cgo.GenerateWindowPoSt.func1(0xb828ce?, {0xc044080000?, 0xc037693bc8?}, 0x7058e5?)
	/home/gc/lotus/lotus-gn/lotus/extern/filecoin-ffi/cgo/proofs.go:170 +0x8b fp=0xc002b40f00 sp=0xc002b40e98 pc=0x1565c8b
github.com/filecoin-project/filecoin-ffi/cgo.GenerateWindowPoSt(0x5b8d0?, {0xc044080000?, 0x0?}, 0x0?)
	/home/gc/lotus/lotus-gn/lotus/extern/filecoin-ffi/cgo/proofs.go:170 +0x74 fp=0xc002b40fc0 sp=0xc002b40f00 pc=0x15658f4
github.com/filecoin-project/filecoin-ffi.GenerateWindowPoSt(0x0?, {{0xc043f6e000, 0x1ba1, 0x1e38}}, {0xc03e67b100, 0x20, 0x15c50?})
	/home/gc/lotus/lotus-gn/lotus/extern/filecoin-ffi/proofs.go:586 +0x327 fp=0xc002b410e8 sp=0xc002b40fc0 pc=0x1573627
github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*Sealer).GenerateWindowPoSt(0xc0005ba840?, {0x494afd0?, 0xc18e799860?}, 0x15c50, {0xc04235e000?, 0x1?, 0x1?}, {0xc03e67b100, 0x20, 0x20})
	/home/gc/lotus/lotus-gn/lotus/extern/sector-storage/ffiwrapper/verifier_cgo.go:50 +0x11a fp=0xc002b41218 sp=0xc002b410e8 pc=0x15859ba
github.com/filecoin-project/lotus/extern/sector-storage.(*Manager).GenerateWindowPoSt(0xc00de1c500, {0x494afd0, 0xc18e799860}, 0x13?, {0xc04235e000, 0x1ba1, 0x1c00}, {0xc03e67b100, 0x20, 0x20})
	/home/gc/lotus/lotus-gn/lotus/extern/sector-storage/manager_post.go:82 +0x178 fp=0xc002b41290 sp=0xc002b41218 pc=0x16745b8
github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runPoStCycle(0xc001dd4000, {0x494afd0?, 0xc18e799830?}, 0x0, {0x1e1e4f, 0x1e18c2, 0x18, 0x1e1e62, 0x1e1e9e, 0x1e1e4e, ...}, ...)
	/home/gc/lotus/lotus-gn/lotus/storage/wdpost_run.go:662 +0x1115 fp=0xc002b41da8 sp=0xc002b41290 pc=0x1dbb175
github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runGeneratePoST(0xc00180c050?, {0x494af28?, 0xc047c44740?}, 0x4200535?, 0xc3f4857c80)
	/home/gc/lotus/lotus-gn/lotus/storage/wdpost_run.go:98 +0x150 fp=0xc002b41f30 sp=0xc002b41da8 pc=0x1db5590
github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).startGeneratePoST.func1()
	/home/gc/lotus/lotus-gn/lotus/storage/wdpost_run.go:82 +0x149 fp=0xc002b41fe0 sp=0xc002b41f30 pc=0x1db52a9
runtime.goexit()
	/snap/go/9848/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc002b41fe8 sp=0xc002b41fe0 pc=0x764601
created by github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).startGeneratePoST
	/home/gc/lotus/lotus-gn/lotus/storage/wdpost_run.go:72 +0x11f

Note: The physical server has plenty memory available.

**Comment by rjan90** [comment] 2022-07-15 09:52
Hey! Thanks for the issue report, this might be related to the issue posted here: https://github.com/filecoin-project/filecoin-ffi/issues/307

**Comment by Jason-Cui** [comment] 2022-07-15 10:28
Thanks, we’ll give it a try.

Regards

**Comment by rjan90** [comment] 2022-07-18 06:13
Hey @Jason-Cui! Have you been able to try out the fix? And if so, have you seen any OOM issues after that?

**Comment by Jason-Cui** [comment] 2022-07-18 08:36
Hi, we are still monitoring after applying the patch. The issue will be closed tomorrow if no crashed is observed by then.

Thanks.

**Comment by Jason-Cui** [comment] 2022-08-02 03:50
The patch does not solve the problem permanently. It happened again today. Lotus-miner process immediatelly quit after logging "memory allocation of 67108864 bytes failed"

**Comment by Jason-Cui** [comment] 2022-08-02 03:51
It seems the root cause is still unclear.

**Comment by Reiers** [comment] 2022-10-31 13:48
Hi @Jason-Cui 

Thanks for the report. The issue is starting to be outdated, and probably belongs in the discussion forum. 
If the issue persist on the latest stable release, please open a new issue or ask for help in our [Discussion forum.
](https://github.com/filecoin-project/lotus/discussions)
Thanks again !

_Not seen any recent reports that lotus-miner crashes so it may be local issue thats why Im closing this ticket._

**Closed by Reiers** 2022-10-31 13:48 UTC
Labels: area/proving
