### ISSUE TITLE
Data Transfers are RAM hungry

### ISSUE THREAD

**Issue by dineshshenoy** [filecoin-project/lotus#4877] opened 2020-11-16 21:32 UTC
The memory usage when creating client deals is very high.  @jsign created 5 deals (40 GB total) which increased RAM usage by 15GB until transfers finished.  Lotus total peak RAM usage = 40GB for these 5 concurrent-ish deals

cc: @hannahhoward

**Comment by Stebalien** [comment] 2020-11-21 00:35
Which version?

**Comment by dineshshenoy** [comment] 2020-11-21 02:51
@jsign do you know what version this is happening?  I thjnk this was 1.1.3 but maybe a diff commit

**Comment by jsign** [comment] 2020-11-21 19:06
This was with official v1.1.3.

**Comment by jsign** [comment] 2020-11-25 18:24
I had the opportunity to get into this situation again:
```
Daemon:  1.2.1+git.97a76a4b9+api1.0.0
Local: lotus version 1.2.1+git.97a76a4b9
```
Now having 4 sending data transfers of 4GiB to miners.
![image](https://user-images.githubusercontent.com/6136245/100267482-435d7280-2f32-11eb-8ff4-a9029560dce2.png)

Here some pprof of the heap and goroutines running:
[pprofs.zip](https://github.com/filecoin-project/lotus/files/5598560/pprofs.zip)

cc @hannahhoward  @Stebalien @dirkmc

**Comment by kernelogic** [comment] 2020-11-25 18:30
So is this proportional to the number of deals or the size of the deals?

**Comment by jsign** [comment] 2020-11-27 12:27
Some other profile with full ram and 21GiB of swap:
[pprof20201127.zip](https://github.com/filecoin-project/lotus/files/5607818/pprof20201127.zip)

**Comment by Stebalien** [comment] 2020-11-30 17:50
graphsync 0.5.1 (the version you're using) should max out at 6 requests and 256MiB of memory so something is definitely funny here. In theory, it could be that GC is falling behind (especially if you're using swap) but really, if you're just sending a few deals as a client, we should never get to that point.

**Comment by dineshshenoy** [comment] 2020-11-30 17:53
The max of 6 requests was relaxed recently which may be why this issue came up.  cc: @dirkmc

**Comment by Stebalien** [comment] 2020-11-30 18:05
That _shouldn't_ matter _too_ much (I only bring it up because there may be some per-request overhead or over-allocation, not sure). However, the version @jsign is using has that restriction.

**Comment by hannahhoward** [comment] 2020-12-02 16:59
goodness I wish go had better ref-count diagnostics for catching memory leaks. It will be interesting with the memory watchdog, which can help us remove GC as a cause. We identified a particular memory leak -- but there may be others. We also probably need to look at the IPFS Block Store code cause it may be written so that its hold a reference in a way it should.

**Comment by raulk** [comment] 2020-12-03 15:20
Memory watchdog is now merged. You can set a maximum heap limit through the `LOTUS_MAX_HEAP` env variable. Docs here: https://github.com/filecoin-project/filecoin-docs/pull/609

Could you also follow the steps here? https://github.com/filecoin-project/lotus/issues/4445#issuecomment-737995590

And also throw in a `gctrace=1` into that `GODEBUG` env variable (comma-separated).

**Comment by dirkmc** [comment] 2020-12-07 14:52
It looks like the problem is somewhere in this code path:
https://github.com/ipfs/go-graphsync/blob/11d30c607e3f9062b1a3755dba34f6abcb9eaf85/responsemanager/runtraversal/runtraversal.go#L21-L56

![image](https://user-images.githubusercontent.com/169124/101365477-2450d000-38a4-11eb-8a4e-d46404c4202a.png)

My guess is that either `Traverser.Advance(blockBuffer)` or `sendResponse(lnk, data)` is keeping a reference to the data slice that never gets cleaned up.

I dug around in the code but I wasn't able to figure out exactly where that might be happening. @hannahhoward do you have an idea where it might occur?

**Comment by jsign** [comment] 2020-12-21 12:47
Leaving here some story of a thing happening while upgrading the Lotus node we are using for deal-success tests. 

This node had ~8 in-progress 16GiB (padded) deals, with many of them still pending the data-transfer stage (so, many things pending to transfer). When I updated to v1.4.0, I saw the node was struggling a lot with syncing. 

A further inspection showed that using a lot of RAM, better described:
```
 |        Memory         |    SWAP
 | used  free  buff  cach| used  free>
 |30.7G  273M 2836k  260M|  24G   26G>
 ```
 So ~54GiB of RAM used. I was pretty sure this was related to data-transfers.
  
 
 I restarted with:
 ```
LOTUS_MAX_HEAP=30GiB
GODEBUG=madvdontneed=1
```
as to be quite aggressive on discarding some possible situations from the Go GC implementation.
After restarting, the same RAM behavior happened... so sounded like `in_use` memory reported by the Go runtime should be high.

I took some profile, and this is further confirmation of some things:
![image](https://user-images.githubusercontent.com/6136245/102778126-be1e7f80-4370-11eb-9dc9-b7bf074c4351.png)
- `in_use` space 54GiB, so this explains why the watchdog max heap or forcing returning freed mem pages to the kernel didn't help.
- confirms again the path of memory references being investigated.

The only way I could get out of this situation was by `SimultaneousTransfers = 1`, since I was fearing getting out of SWAP and being OOM killed risking some data corruption. This worked to avoid memory ramp-up, so it all makes sense.

**Comment by kernelogic** [comment] 2020-12-21 18:47
SimultaneousTransfers where do you set this variable? If you limit it to 1 and that deal got stuck you are stuck forever?

**Comment by jsign** [comment] 2020-12-21 19:30
> SimultaneousTransfers where do you set this variable?
In `[Client]` section.

> If you limit it to 1 and that deal got stuck you are stuck forever?
AFAIK, yes, so it's mostly a workaround.

**Comment by raulk** [comment] 2021-03-11 10:30
[go-graphsync v0.6.0](https://github.com/ipfs/go-graphsync/blob/master/CHANGELOG.md#go-graphsync-060) fixed the memory scaling issues with graphsync transfers, by moving the memory allocation to the message queue.  It was first integrated in Lotus v1.5.1. All our reports indicate that data transfer no longer allocates memory linearly with the file size.

Please open new issues if you find other issues with memory footprint during data transfer.

**Closed by raulk** 2021-03-11 10:30 UTC
Labels: P2, area/markets/client, area/markets/storage, x/ignite
