### ISSUE TITLE
no schedule for task 

### ISSUE THREAD

**Issue by RustMan88** [filecoin-project/lotus#2938] opened 2020-08-10 08:00 UTC
**Describe the bug**
When the scheduling is busy, the work be quickly reconnect after disconnection, and then the scheduling will not work for task.
Like deallock.
This is a serious bug, especially for a large number of tasks and worker clusters

**To Reproduce**
1.killall lotus-worker and immediately ./lotus-worker
2.Or occur the program's own reconnection 。

**Expected behavior**
normal schedule for task, expected  step 2, eg ====2=====>SealCommit1

**Screenshots**
`2020-08-09T22:24:59.226+0800	INFO	sectors	storage-fsm@v0.0.0-20200805013058-9d9ea4e6331f/states_sealing.go:273	KOMIT 559 7c6406259d258592f18e99999f2210ea64879cf8c6578b462d25f0475c860d76(1591); 6291e349383f1add4d85d90e55e98445bbd4bb2ae9c792a10e18dff4bdfec8ce(4282); [{34359738368 baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq}]; r:626167626f6561346235616263626f75326179646a7578786b696e3437366873706e776a376c32623561626674356570716f6575756f6d766a6f32667768787a79; d:626167613665613473656171616f377337337932346b637574616f7376616370646a67666535707737366f6f65666e79717734796e72336432793678326d7071
2020-08-09T22:24:59.226+0800	INFO	advmgr	sector-storage/manager.go:384	Schedule tasks ===========1=======>SealCommit1, sector :{1328 559}
2020-08-09T22:24:59.234+0800	INFO	sectors	storage-fsm@v0.0.0-20200805013058-9d9ea4e6331f/states_sealing.go:271	scheduling seal proof computation...
2020-08-09T22:24:59.234+0800	INFO	sectors	storage-fsm@v0.0.0-20200805013058-9d9ea4e6331f/states_sealing.go:273	KOMIT 504 f93924413490b84f737c9685a3fbebb0a3a038d48e4c235c2db191ff208a4b0e(1316); 6291e349383f1add4d85d90e55e98445bbd4bb2ae9c792a10e18dff4bdfec8ce(4282); [{34359738368 baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq}]; r:626167626f656134623561626361336d7132647078687a3472336876376932696e756b33376b647a6266346f6a726d6e6e6b737a3533737a3633726e7832336366; d:626167613665613473656171616f377337337932346b637574616f7376616370646a67666535707737366f6f65666e79717734796e72336432793678326d7071
2020-08-09T22:24:59.234+0800	INFO	advmgr	sector-storage/manager.go:384	Schedule tasks ===========1=======>SealCommit1, sector :{1328 504}
2020-08-09T22:24:59.234+0800	INFO	sectors	storage-fsm@v0.0.0-20200805013058-9d9ea4e6331f/states_sealing.go:271	scheduling seal proof computation...
2020-08-09T22:24:59.234+0800	INFO	sectors	storage-fsm@v0.0.0-20200805013058-9d9ea4e6331f/states_sealing.go:273	KOMIT 382 821596146867c58f2a577b27b973047d2df59787921fff6ebd3967f3976c758f(852); 6291e349383f1add4d85d90e55e98445bbd4bb2ae9c792a10e18dff4bdfec8ce(4282); [{34359738368 baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq}]; r:626167626f6561346235616263627a626933726767696273776166376b75766367613276796637756e6d736f7a66767033716177736e77326c626776686567636f; d:626167613665613473656171616f377337337932346b637574616f7376616370646a67666535707737366f6f65666e79717734796e72336432793678326d7071

**Version (run `lotus version`):**
lotus-miner v0.4.3

**Additional context**

**Comment by magik6k** [comment] 2020-08-10 09:15
When that happens, can you get `curl http://[miner api address]/debug/pprof/goroutine?debug=2 > goroutines`, and the same for the worker (default worker api port is 3456 IIRC)

`lotus-miner info all > minerinfo` would also be very useful

**Comment by yaohcn** [comment] 2020-08-13 04:12
related issues: #2729 #3001

**Comment by rjan90** [comment] 2022-03-28 08:24
Hi @RustMan88!

Thanks for the report. The issue is outdated, and a number of scheduler-improvements has been merged since this release. If you see this issue in a current release please open a new ticket.

Thanks again !

**Closed by rjan90** 2022-03-28 08:24 UTC
Labels: help wanted, need/community-input, need/analysis
