### ISSUE TITLE
Continous stream of drand failure in miner log

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/lotus#3593] opened 2020-09-06 12:25 UTC
**Describe the bug**
Since about an hour ago my miner keeps pumping out lines like these:
```
2020-09-06T12:22:40.810Z	ERROR	miner	miner/miner.go:189	failed getting beacon entry: drand failed Get request: not supported
```

They are appearing with about 300 per second;
```
2020-09-06T12:22:40.814Z	ERROR	miner	miner/miner.go:189	failed getting beacon entry: drand failed Get request: not supported
2020-09-06T12:22:40.819Z	ERROR	miner	miner/miner.go:189	failed getting beacon entry: drand failed Get request: not supported
2020-09-06T12:22:40.829Z	ERROR	miner	miner/miner.go:189	failed getting beacon entry: drand failed Get request: not supported
2020-09-06T12:22:40.832Z	ERROR	miner	miner/miner.go:189	failed getting beacon entry: drand failed Get request: not supported
2020-09-06T12:22:40.836Z	ERROR	miner	miner/miner.go:189	failed getting beacon entry: drand failed Get request: not supported
2020-09-06T12:22:40.845Z	ERROR	miner	miner/miner.go:189	failed getting beacon entry: drand failed Get request: not supported
2020-09-06T12:22:40.854Z	ERROR	miner	miner/miner.go:189	failed getting beacon entry: drand failed Get request: not supported
2020-09-06T12:22:40.857Z	ERROR	miner	miner/miner.go:189	failed getting beacon entry: drand failed Get request: not supported
2020-09-06T12:22:40.865Z	ERROR	miner	miner/miner.go:189	failed getting beacon entry: drand failed Get request: not supported
2020-09-06T12:22:40.869Z	ERROR	miner	miner/miner.go:189	failed getting beacon entry: drand failed Get request: not supported
2020-09-06T12:22:40.878Z	ERROR	miner	miner/miner.go:189	failed getting beacon entry: drand failed Get request: not supported
2020-09-06T12:22:40.905Z	ERROR	miner	miner/miner.go:189	failed getting beacon entry: drand failed Get request: not supported
2020-09-06T12:22:40.909Z	ERROR	miner	miner/miner.go:189	failed getting beacon entry: drand failed Get request: not supported
2020-09-06T12:22:40.913Z	ERROR	miner	miner/miner.go:189	failed getting beacon entry: drand failed Get request: not supported
2020-09-06T12:22:40.917Z	ERROR	miner	miner/miner.go:189	failed getting beacon entry: drand failed Get request: not supported
2020-09-06T12:22:40.921Z	ERROR	miner	miner/miner.go:189	failed getting beacon entry: drand failed Get request: not supported
2020-09-06T12:22:40.926Z	ERROR	miner	miner/miner.go:189	failed getting beacon entry: drand failed Get request: not supported
2020-09-06T12:22:40.928Z	ERROR	miner	miner/miner.go:189	failed getting beacon entry: drand failed Get request: not supported
2020-09-06T12:22:40.942Z	ERROR	miner	miner/miner.go:189	failed getting beacon entry: drand failed Get request: not supported
2020-09-06T12:22:40.946Z	ERROR	miner	miner/miner.go:189	failed getting beacon entry: drand failed Get request: not supported
2020-09-06T12:22:40.953Z	ERROR	miner	miner/miner.go:189	failed getting beacon entry: drand failed Get request: not supported
```

**To Reproduce**
Run miner

**Expected behavior**
A single failure log at least

**Version 0.5.10**

**Comment by RobQuistNL** [comment] 2020-09-06 12:26
@whyrusleeping @magik6k you might want to get this fixed before the actual drand failure test comes along sept. 9th

**Comment by RobQuistNL** [comment] 2020-09-06 12:27
Daemon log is also cluttered:
```
2020-09-06T12:27:15.048Z	INFO	drand	drand/drand.go:136	start fetching randomness	{"round": 117286}
2020-09-06T12:27:15.049Z	INFO	drand	drand/drand.go:146	done fetching randomness	{"round": 117286, "took": 0.001072947}
2020-09-06T12:27:15.049Z	WARN	rpc	go-jsonrpc@v0.1.2-0.20200822201400-474f4fdccc52/handler.go:241	error in RPC call to 'Filecoin.BeaconGetEntry': drand failed Get request:
    github.com/filecoin-project/lotus/chain/beacon/drand.(*DrandBeacon).Entry.func1
        /home/filecoin/lotus/chain/beacon/drand/drand.go:141
  - not supported
2020-09-06T12:27:15.050Z	INFO	drand	drand/drand.go:136	start fetching randomness	{"round": 117286}
2020-09-06T12:27:15.051Z	INFO	drand	drand/drand.go:146	done fetching randomness	{"round": 117286, "took": 0.001047889}
2020-09-06T12:27:15.051Z	WARN	rpc	go-jsonrpc@v0.1.2-0.20200822201400-474f4fdccc52/handler.go:241	error in RPC call to 'Filecoin.BeaconGetEntry': drand failed Get request:
    github.com/filecoin-project/lotus/chain/beacon/drand.(*DrandBeacon).Entry.func1
        /home/filecoin/lotus/chain/beacon/drand/drand.go:141
  - not supported
2020-09-06T12:27:15.054Z	INFO	messagepool	messagepool/messagepool.go:607	message nonce has too big a gap from expected nonce (Nonce: 45249, nextNonce: 45042): unfulfilled nonce gap
```

**Comment by RobQuistNL** [comment] 2020-09-06 12:29
Restarting the daemon made the errors stop for a while (as expected) but it keeps failing after a restart

**Comment by RobQuistNL** [comment] 2020-09-06 12:33
I seemed to have a DNS issue on my miner machine: setting the nameserver to 1.1.1.1 helped fix it - I saw some short "unable to resolve drand something something .sh" message.

**Comment by jennijuju** [comment] 2020-09-07 19:46
@Kubuxu @magik6k

**Comment by Kubuxu** [comment] 2020-09-07 19:47
We need to 1. figure out if pubsub based drand client is working on wider scale
the easiest way to probably do it is to add OpenCensus metrics to drand clients.

**Comment by Reiers** [comment] 2022-04-18 17:21
Hi everyone

The issue is outdated, and it seems like the fix was merged. 

If this is a issue in the [current release](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1) - please open a new ticket and reference this ticket.

Thank you !

**Closed by Reiers** 2022-04-18 17:21 UTC
