### ISSUE TITLE
[BUG] Packing piece failed when using batch publish deal and single max wait deals sector

### ISSUE THREAD

**Issue by xinaxu** [filecoin-project/lotus#6608] opened 2021-06-27 15:28 UTC
**Describe the bug**
After batch deal publishing, the miner tries to package all deals into a single sector which do not have enough space. 
The MaxWaitDealSectors was set to 1.

**Version (run `lotus version`):**
lotus version 1.10.0+mainnet+git.764fa9dae

**To Reproduce**
Accept deals with different sizes. Batch publish deal. Set MaxWaitDealsSectors to 1.

**Expected behavior**
It should create new sectors when the existing WaitDeals sector does not have enough space.

**Logs**
`handing off deal to node: packing piece at path fstmp339820519: AddPiece failed: piece bafy2bzaceavpnkcaoyocu4jaz3m5uczdcyflqc6in2vsyzhismibjn67wmaba assigned to sector 301 with not enough space`

**Comment by f8-ptrk** [comment] 2021-06-28 13:22
no it should not create a second WaitDeals sector. it should wait until the first sector left WaitDeals and then open a new one.

the bug here seems to be that it tries to over fill a singe waitdeals sector

**Comment by xinaxu** [comment] 2021-06-28 22:28
Makes sense.
The expected behavior is also up for debate. Say the first sector only has 1GB left and there comes a 2GB deal. Should it start PC1 immediately so another sector can open up for the 2GB deal, or should it wait until it reaches max WaitDeal time and then start a new sector. I slightly prefers the 1st one.

**Comment by rjan90** [comment] 2022-05-16 10:49
Hey!

Thanks for the issue-ticket! Although I see your point that sometimes it could be ideal for it to `start PC1 immediately so another sector can open up for the 2GB deal`  - I think we can agree that the current solution to change the configuration to allow for more WaitDeals sectors is a sufficient solution.

I´m closing this issue for now. But I will happily open it if more people think is a very needed feature.

**Closed by rjan90** 2022-05-16 10:49 UTC
Labels: need/triage, kind/bug

**Comment by f8-ptrk** [comment] 2022-05-16 11:00
@rjan90 increasing `MaxWaitDealSectors` comes with side effects that might not be wanted!!!!!!!!!!!! it's a bug - fix it!!!

**Comment by rjan90** [comment] 2022-05-16 11:03
> it's a bug - fix it!!!

@f8-ptrk I do not think increasing `MaxWaitDealSectors` from 1 to 10 will come with any side effects here? Please elaborate why you actually mean that setting it at 1 should be ideal

**Comment by f8-ptrk** [comment] 2022-05-16 11:05
`MaxWaitDealSectors` is used to control parallel AP's - as there is otherwise no way to control how many APs start after batch publishing messages

**Comment by f8-ptrk** [comment] 2022-05-16 11:06
we do not discuss if the quick fix works or not! 

```
Logs
handing off deal to node: packing piece at path fstmp339820519: AddPiece failed: piece bafy2bzaceavpnkcaoyocu4jaz3m5uczdcyflqc6in2vsyzhismibjn67wmaba assigned to sector 301 with not enough space
```

if this is intended behavior - then close the issue. if not it's a bug and the issue has all rights to stay open

**Comment by rjan90** [comment] 2022-05-16 12:14
> MaxWaitDealSectors is used to control parallel AP's - as there is otherwise no way to control how many APs start after batch publishing messages

That is not the intended use of the MaxWaitDealsSectors config. Yes, we should have a better way of controlling how many APs start at the same time, but we already have multiple issues open about that.

**Comment by f8-ptrk** [comment] 2022-05-16 12:16
i know - its a "see, this is how you can prevent this and that from happening" solution too ;) we will not be able to stack those "solutions" forever
