### ISSUE TITLE
Sync picked an odd target

### ISSUE THREAD

**Issue by arajasek** [filecoin-project/lotus#3117] opened 2020-08-17 20:08 UTC
@placer14 reported that his Lotus node started syncing to a valid tipset at height [1729](https://en.wikipedia.org/wiki/Taxicab_number), when the chain height was > 11k. The tipset picked is on the main chain, I'm just not sure why you'd pick such a low target, especially given that the bootstrap peers themselves were at the right height of ~11k.

Might be hard to investigate, but worth noting it happened?

**Comment by rjan90** [comment] 2022-03-28 08:38
Hey!

I´m closing this since it seems a bit hard to investigate or reproduce. If someone else runs into this issue on newer version they hopefully get som additional logs.

**Closed by rjan90** 2022-03-28 08:38 UTC
Labels: area/chain
