### ISSUE TITLE
[Mining Issue] can't win blocks since 0 sector fault.

### ISSUE THREAD

**Issue by ncgege** [filecoin-project/lotus#6279] opened 2021-05-18 07:01 UTC
**Version**
lotus version 1.8.0+mainnet+git.5c56017db.dirty
lotus-miner version 1.8.0+mainnet+git.1e10efef9

only one sector fault ,but cant win blocks for 6 days and 10 days , each miner are above 400TB Adj Power.
f0523711 is mine and i found another form filfxo  f0111467.

**Comment by ncgege** [comment] 2021-05-20 08:27
when i change to v1.11.0 since 5.18(UTC 20:00)  ,it mined blocks again.
though it's a dev version ,but it seems work well.

**Comment by Reiers** [comment] 2022-01-02 00:10
Hi @ncgege 

Thanks for the report. With no logs, its hard to reproduce the issue or find the cause.
If you had 1 sector fault, you need to either restore it or terminate. 

Both minerIDs provided, have been able to do winningPost for the past 30 days. 

Tip:
- Make sure that you are in sync

and please upgrade Lotus to the latest release.

*Link to latest tags [here.](https://github.com/filecoin-project/lotus/tags)*

Closing ticket.

If you are still experiencing this problem, open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

**Closed by Reiers** 2022-01-02 00:10 UTC
Labels: area/mining
