### ISSUE TITLE
 Error in RPC call to 'Filecoin.SealPreCommit2' with error infomation 'failed to add columns: GPUError'

### ISSUE THREAD

**Issue by verynohair** [filecoin-project/lotus#3308] opened 2020-08-26 09:14 UTC
There is an error appeared when the miner executed the Precommit2 progress. The error message shows below:

My Graph Card is NVIDIA GTX 1070 with 8GB Memory, and it can work correctly before.

thread '<unnamed>' panicked at 'failed to add columns: GPUError("FutharkError(FutharkError { error: \"./lib/a.c:18770: OpenCL call\\n  opencl_alloc(&ctx->opencl, size, desc, &block->mem)\\nfailed with error code -5 (Out of resources)\\n\" })")', /root/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/storage-proofs-porep-5.1.1/src/stacked/vanilla/proof.rs:559:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'failed to send columns: "SendError(..)"', /root/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/storage-proofs-porep-5.1.1/src/stacked/vanilla/proof.rs:532:29
2020-08-26T14:56:01.138+0800    WARN    rpc     go-jsonrpc@v0.1.2-0.20200817153016-2ea5cbaf5ec0/handler.go:241  error in RPC call to 'Filecoin.SealPreCommit2': presealing sector 1 ():
    github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*Sealer).SealPreCommit2
        /opt/upload/lotus/extern/sector-storage/ffiwrapper/sealer_cgo.go:478
  - Rust panic: no unwind information
    github.com/filecoin-project/filecoin-ffi.SealPreCommitPhase2
        /opt/upload/lotus/extern/filecoin-ffi/proofs.go:319
    github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*Sealer).SealPreCommit2
        /opt/upload/lotus/extern/sector-storage/ffiwrapper/sealer_cgo.go:476
    github.com/filecoin-project/lotus/extern/sector-storage.(*LocalWorker).SealPreCommit2
        /opt/upload/lotus/extern/sector-storage/localworker.go:151
    reflect.Value.call
        /usr/lib/go-1.14/src/reflect/value.go:460
    reflect.Value.Call
        /usr/lib/go-1.14/src/reflect/value.go:321
    github.com/filecoin-project/go-jsonrpc/auth.PermissionedProxy.func1
        /root/go/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.2-0.20200817153016-2ea5cbaf5ec0/auth/auth.go:62
    reflect.callReflect
        /usr/lib/go-1.14/src/reflect/value.go:549
    reflect.makeFuncStub
        /usr/lib/go-1.14/src/reflect/asm_amd64.s:20
    github.com/filecoin-project/lotus/api/apistruct.(*WorkerStruct).SealPreCommit2
        /opt/upload/lotus/api/apistruct/struct.go:1194
    reflect.Value.call
        /usr/lib/go-1.14/src/reflect/value.go:460
    reflect.Value.Call
        /usr/lib/go-1.14/src/reflect/value.go:321
    github.com/filecoin-project/go-jsonrpc.doCall
        /root/go/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.2-0.20200817153016-2ea5cbaf5ec0/handler.go:130
    github.com/filecoin-project/go-jsonrpc.(*RPCServer).handle
        /root/go/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.2-0.20200817153016-2ea5cbaf5ec0/handler.go:221
    runtime.goexit
        /usr/lib/go-1.14/src/runtime/asm_amd64.s:1373

**Comment by callmestu** [comment] 2020-09-05 21:47
I am also having this issue on Miner: t016482. AMD Threadripper 1900x with Nvidia Tesla K80 GPU. command nvidia-smi shows the GPU to still be operating in good health. 

`thread '<unnamed>' panicked at 'failed to add columns: GPUError("FutharkError(FutharkError { error: \"./lib/a.c:18770: OpenCL call\\n  opencl_alloc(&ctx->opencl, size, desc, &block->mem)\\nfailed with error code -5 (Out of resources)\\n\" })")', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-5.1.1/src/stacked/vanilla/proof.rs:559:29
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1211
  14: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  15: std::panicking::try::do_call
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  17: <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute
  18: rayon_core::registry::WorkerThread::wait_until_cold
  19: rayon_core::scope::ScopeBase::steal_till_jobs_complete
  20: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  21: std::panicking::try::do_call
  22: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  23: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  24: rayon_core::registry::WorkerThread::wait_until_cold
  25: rayon_core::registry::ThreadBuilder::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'failed to send columns: "SendError(..)"', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-5.1.1/src/stacked/vanilla/proof.rs:532:29
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1211
  14: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  15: std::panicking::try::do_call
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  17: <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute
  18: rayon_core::registry::WorkerThread::wait_until_cold
  19: rayon_core::registry::ThreadBuilder::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2020-09-05T17:58:36.052Z        WARN    rpc     go-jsonrpc@v0.1.2-0.20200822201400-474f4fdccc52/handler.go:241  error in RPC call to 'Filecoin.SealPreCommit2': presealing sector 4 ():
    github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*Sealer).SealPreCommit2
        /data/lotus/extern/sector-storage/ffiwrapper/sealer_cgo.go:478
  - Rust panic: no unwind information
    github.com/filecoin-project/filecoin-ffi.SealPreCommitPhase2
        /data/lotus/extern/filecoin-ffi/proofs.go:319
    github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*Sealer).SealPreCommit2
        /data/lotus/extern/sector-storage/ffiwrapper/sealer_cgo.go:476
    github.com/filecoin-project/lotus/extern/sector-storage.(*LocalWorker).SealPreCommit2
        /data/lotus/extern/sector-storage/localworker.go:151
    reflect.Value.call
        /snap/go/6274/src/reflect/value.go:460
    reflect.Value.Call
        /snap/go/6274/src/reflect/value.go:321
    github.com/filecoin-project/go-jsonrpc/auth.PermissionedProxy.func1
        /root/go/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.2-0.20200822201400-474f4fdccc52/auth/auth.go:62
    reflect.callReflect
        /snap/go/6274/src/reflect/value.go:549
    reflect.makeFuncStub
        /snap/go/6274/src/reflect/asm_amd64.s:20
    github.com/filecoin-project/lotus/api/apistruct.(*WorkerStruct).SealPreCommit2
        /data/lotus/api/apistruct/struct.go:1200
    reflect.Value.call
        /snap/go/6274/src/reflect/value.go:460
    reflect.Value.Call
        /snap/go/6274/src/reflect/value.go:321
    github.com/filecoin-project/go-jsonrpc.doCall
        /root/go/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.2-0.20200822201400-474f4fdccc52/handler.go:130
    github.com/filecoin-project/go-jsonrpc.(*RPCServer).handle
        /root/go/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.2-0.20200822201400-474f4fdccc52/handler.go:221
    runtime.goexit
        /snap/go/6274/src/runtime/asm_amd64.s:1373
2020-09-05T17:58:52.428Z        DEBUG   stores  stores/util_unix.go:28  move sector data        {"from": "/data/lotus_seal/unsealed/fetching/s-t016482-6", "to": "/data/lotus_seal/unsealed/s-t016482-6"}`

**Comment by hxg8202** [comment] 2020-12-14 07:56
thread '<unnamed>' panicked at 'failed to add columns: GPUError("FutharkError(FutharkError { error: \"./lib/a.c:21158: OpenCL call\\n  opencl_alloc(&ctx->opencl, size, desc, &block->mem)\\nfailed with error code -4 (Memory object allocation failure)\\n\" })")', /home/lotus/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-5.4.0/src/stacked/vanilla/proof.rs:527:71
thread '<unnamed>' panicked at 'failed to send columns: "SendError(..)"', /home/lotus/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-5.4.0/src/stacked/vanilla/proof.rs:502:34

**Comment by Reiers** [comment] 2021-12-23 22:51
Hi @hxg8202 

Thanks for the report. This is not a Lotus issue.
Seems like the problem is hardware related. 

Visit our [Discussions forum](https://github.com/filecoin-project/lotus/discussions) for help and troubleshooting. 

Closing ticket.

**Closed by Reiers** 2021-12-23 22:51 UTC
