### ISSUE TITLE
Initialize storage miner failed,the previous steps performed correctly

### ISSUE THREAD

**Issue by muronglaowang** [filecoin-project/lotus#405] opened 2019-10-18 02:22 UTC
lotus-storage-miner init --owner=t3q

2019-10-18T02:06:22.540Z	INFO	main	lotus-storage-miner/init.go:52	Initializing lotus storage miner
2019-10-18T02:06:22.540Z	INFO	main	lotus-storage-miner/init.go:54	Checking proof parameters
2019-10-18T02:06:22.545Z	WARN	build	build/paramfetch.go:74	Checksum mismatch in param file v12-zigzag-proof-of-replication-6496c180c2eab89ee0638bc73879ced01daf512486eb38b9e1c9402ba578e010.params, 79b00e23c307763d2ac945eb377f1fab != e7aa73a1b06290d30f567bfac8324bf1
2019-10-18T02:06:22.546Z	INFO	build	build/paramfetch.go:81	Fetching /var/tmp/filecoin-proof-parameters/v12-zigzag-proof-of-replication-6496c180c2eab89ee0638bc73879ced01daf512486eb38b9e1c9402ba578e010.params
 544.97 KiB / 1.41 GiB [>----------------------------------------------------------------------]   0.04% 1.62 KiB/s 5m37s
2019-10-18T02:12:01.429Z	WARN	main	lotus-storage-miner/main.go:71	fetching proof parameters: read tcp 11......:53648->198.211.99.118:80: read: connection reset by peer

**Comment by whyrusleeping** [comment] 2019-10-18 12:44
It seems like you are unable to download the parameter files, I think this is a duplicate of #394

**Closed by whyrusleeping** 2019-10-18 12:44 UTC
