### ISSUE TITLE
Exit Code 1 Update Payment Channel

### ISSUE THREAD

**Issue by rllola** [filecoin-project/lotus#3145] opened 2020-08-18 15:21 UTC
**Describe the bug**
I have create a payment channel and I am trying to update it with a voucher but an exit code 1. Not sure what it means.

**To Reproduce**
1. Create a payment channel
2. Update payment channel
3. Check state wait msg

**Expected behavior**
Exit code 0 or an informative message about what is going on.

**Version (run `lotus version`):**
Lastest master branch as a local dev node

**Additional context**
I got this error showing on the log of the local dev node
```
2020-08-18T16:59:07.019+0200	ERROR	vm	vm/runtime.go:149	spec actors failure: runtime error: invalid memory address or nil pointer dereference
2020-08-18T16:59:07.021+0200	WARN	vm	vm/vm.go:405	Send actor error	{"from": "t137sjdbgunloi7couiy4l5nc7pd6k2jmq32vizpy", "to": "t01003", "nonce": 5, "method": "2", "height": "3161", "error": "spec actors failure: runtime error: invalid memory address or nil pointer dereference (RetCode=1):\n    github.com/filecoin-project/lotus/chain/vm.(*Runtime).shimCall.func1\n        /home/lola/Workspace/lotus/chain/vm/runtime.go:150"}
```

**Comment by Reiers** [comment] 2022-04-18 13:19
Hi @rllola 

Thanks for the report. The issue is outdated.
Is this an issue in [current release](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1)?

Thanks again !

**Comment by rllola** [comment] 2022-04-18 16:26
I have no idea. I guess it can be closed.

**Comment by Reiers** [comment] 2022-04-18 16:34
Cool - thanks for your fast reply.

Closing Lotus Issue ticket!

**Closed by Reiers** 2022-04-18 16:34 UTC
Labels: need/author-input
