### ISSUE TITLE
sync error: collectChain failed

### ISSUE THREAD

**Issue by vonhenry** [filecoin-project/lotus#4642] opened 2020-10-29 08:47 UTC
lotus version v1.1.2

after bellow log, the node stop sync

---------------
```
2020-10-29T16:44:52.258+0800	INFO	chain	chain/sync.go:713	block validation	{"took": 15.19516837, "height": "183581", "age": 147262.258406674}
2020-10-29T16:44:52.258+0800	ERROR	chain	chain/sync.go:1494	failed to validate tipset: validating block bafy2bzaceatmgzyb7t5sp6uappailanouaz5f4fkh7kic22zzbfjrpmn6t6zk:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateTipSet.func1
        /nvme_data/Code/filecoin-project/lotus/chain/sync.go:627
  - 1 error occurred:
	* parent state root did not match computed state (bafy2bzacecjyhj6acs47qqixguxxnz7oqgyjtitxtuzkhixhucqdgysvpb37s != bafy2bzacecr46ca727y33smhmq5s4wani3zrch7h2n4lj42x4gpgq6zjmrthg):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6
        /nvme_data/Code/filecoin-project/lotus/chain/sync.go:812


2020-10-29T16:44:52.258+0800	ERROR	chain	chain/sync_manager.go:424	sync error: collectChain failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).Sync
        /nvme_data/Code/filecoin-project/lotus/chain/sync.go:577
  - collectChain syncMessages:
    github.com/filecoin-project/lotus/chain.(*Syncer).collectChain
        /nvme_data/Code/filecoin-project/lotus/chain/sync.go:1719
  - message processing failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).syncMessagesAndCheckState.func1
        /nvme_data/Code/filecoin-project/lotus/chain/sync.go:1495
  - validating block bafy2bzaceatmgzyb7t5sp6uappailanouaz5f4fkh7kic22zzbfjrpmn6t6zk:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateTipSet.func1
        /nvme_data/Code/filecoin-project/lotus/chain/sync.go:627
  - 1 error occurred:
	* parent state root did not match computed state (bafy2bzacecjyhj6acs47qqixguxxnz7oqgyjtitxtuzkhixhucqdgysvpb37s != bafy2bzacecr46ca727y33smhmq5s4wani3zrch7h2n4lj42x4gpgq6zjmrthg):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6
        /nvme_data/Code/filecoin-project/lotus/chain/sync.go:812


2020-10-29T16:44:52.265+0800	ERROR	chain	chain/sync_manager.go:424	sync error: collectChain failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).Sync
        /nvme_data/Code/filecoin-project/lotus/chain/sync.go:577
  - chain contained block marked previously as bad ([bafy2bzaceakmwcbuk3uriuya5qxl6lrh7bxcji3rc3fckzjty5exgmvqpiggm bafy2bzacedynauzugswds3jpuvagtwg35fhfkidjdivacjacrcj666mma66zi bafy2bzacedmot3euneu2oqjhdnkswfqtc5ty7i6vq6vr7vurgrsf5y4vl5v3s bafy2bzacec3gxyxfsyosisfesjfppuxltdehfjilk7xt25x57fk4re7ozj474], bafy2bzaceatmgzyb7t5sp6uappailanouaz5f4fkh7kic22zzbfjrpmn6t6zk) (reason: 1 error occurred:
    	* parent state root did not match computed state (bafy2bzacecjyhj6acs47qqixguxxnz7oqgyjtitxtuzkhixhucqdgysvpb37s != bafy2bzacecr46ca727y33smhmq5s4wani3zrch7h2n4lj42x4gpgq6zjmrthg):
        github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6
            /nvme_data/Code/filecoin-project/lotus/chain/sync.go:812

    ):
    github.com/filecoin-project/lotus/chain.(*Syncer).collectHeaders
        /nvme_data/Code/filecoin-project/lotus/chain/sync.go:1318
2020-10-29T16:44:52.287 INFO storage_proofs_core::parameter_cache > read verifying key from cache "/nvme_data/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-559e581f022bb4e4ec6e719e563bf0e026ad6de42e56c18714a2c692b1b88d7e.vk"
2020-10-29T16:44:52.300 INFO filecoin_proofs::api::post > verify_winning_post:finish
2020-10-29T16:44:52.300 INFO filcrypto::proofs::api > verify_winning_post: finish
2020-10-29T16:44:52.300+0800	INFO	chain	chain/sync.go:713	block validation	{"took": 15.236912383, "height": "183581", "age": 147262.300145878}
2020-10-29T16:44:52.447+0800	INFO	hello	hello/hello.go:180	time offset	{"offset": -0.260835582, "peerid": "12D3KooWKj7WwTdDohJ61xEiYA6tREWPggqdkKngr5uJPqvdnYTm"}
2020-10-29T16:44:52.857+0800	ERROR	chain	chain/sync_manager.go:424	sync error: collectChain failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).Sync
        /nvme_data/Code/filecoin-project/lotus/chain/sync.go:577
  - chain contained block marked previously as bad ([bafy2bzaceddxyanydioxz26smv5otdg2ktr6ppyjdyjaaf42box34yz3lkgyw], bafy2bzacedtsdboxw5uq3hoqqvbpp4t5qilly4jupdrnj46cy5cqlsyfcrhfc) (reason: change contained bafy2bzaceatmgzyb7t5sp6uappailanouaz5f4fkh7kic22zzbfjrpmn6t6zk caused by: [bafy2bzaceatmgzyb7t5sp6uappailanouaz5f4fkh7kic22zzbfjrpmn6t6zk] 1 error occurred:
    	* parent state root did not match computed state (bafy2bzacecjyhj6acs47qqixguxxnz7oqgyjtitxtuzkhixhucqdgysvpb37s != bafy2bzacecr46ca727y33smhmq5s4wani3zrch7h2n4lj42x4gpgq6zjmrthg):
        github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6
            /nvme_data/Code/filecoin-project/lotus/chain/sync.go:812

    ):
    github.com/filecoin-project/lotus/chain.(*Syncer).collectHeaders
        /nvme_data/Code/filecoin-project/lotus/chain/sync.go:1318
2020-10-29T16:44:52.860+0800	ERROR	chain	chain/sync_manager.go:424	sync error: collectChain failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).Sync
        /nvme_data/Code/filecoin-project/lotus/chain/sync.go:577
  - chain contained block marked previously as bad ([bafy2bzaceaf73mbap5o5qlzsrcxud2a53ipe7qkscn4ka6yn6d34ol5d7pyn6 bafy2bzacedhruf2d4tpzgik5qp2m3dxghebcdfdnepkoo3qzgg3mcso6ch3b4 bafy2bzacebjiy5rfzpf4mwh4mc2xofuu7jnqqyl524s4migccjone37qk7r3u bafy2bzacecwmebxuzdzmpoqwuitb2cgnoqav5vx45p7wnwpjhp5czkzcpayfg], bafy2bzacedtsdboxw5uq3hoqqvbpp4t5qilly4jupdrnj46cy5cqlsyfcrhfc) (reason: change contained bafy2bzaceatmgzyb7t5sp6uappailanouaz5f4fkh7kic22zzbfjrpmn6t6zk caused by: [bafy2bzaceatmgzyb7t5sp6uappailanouaz5f4fkh7kic22zzbfjrpmn6t6zk] 1 error occurred:
    	* parent state root did not match computed state (bafy2bzacecjyhj6acs47qqixguxxnz7oqgyjtitxtuzkhixhucqdgysvpb37s != bafy2bzacecr46ca727y33smhmq5s4wani3zrch7h2n4lj42x4gpgq6zjmrthg):
        github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6
            /nvme_data/Code/filecoin-project/lotus/chain/sync.go:812

    ):
    github.com/filecoin-project/lotus/chain.(*Syncer).collectHeaders
        /nvme_data/Code/filecoin-project/lotus/chain/sync.go:1318
2020-10-29T16:44:53.016+0800	INFO	swarm2	go-libp2p-swarm@v0.2.8/swarm_dial.go:533	got error on dial: dial tcp4 3.129.140.89:1235: connect: connection refused
2020-10-29T16:44:53.029+0800	INFO	swarm2	go-libp2p-swarm@v0.2.8/swarm_dial.go:533	got error on dial: dial tcp4 3.129.112.217:1235: connect: connection refused
2020-10-29T16:44:54.139+0800	INFO	bs:sess	session/session.go:459	No peers - broadcasting	{"session": 1, "want-count": 2}
2020-10-29T16:44:54.160+0800	INFO	sub	sub/incoming.go:102	new block over pubsub	{"cid": "bafy2bzaceahgcg4kwvrgq42fuvkzk2qwwau74qrb2ertj2ws4pj7vpmjhg7ek", "source": "12D3KooWPGWzrJCHsFGNmMyNE659FWkofCo6t94k87dGXXynmWgX", "msgfetch": 0.024566864}
2020-10-29T16:44:54.160+0800	WARN	sub	sub/incoming.go:104	Received block with large delay 114 from miner f034707
2020-10-29T16:44:54.196+0800	INFO	bitswap	messagequeue/messagequeue.go:496	Could not open message sender to peer 12D3KooWDseNCMeqKbHQtbjbJx8RFRqQWCr9t4KiWoMbkaWb1o9u: protocol not supported
2020-10-29T16:44:54.199+0800	INFO	bitswap	messagequeue/messagequeue.go:496	Could not open message sender to peer 12D3KooWBf5oP3GiuY34owYk1YPJTdmnqWZXTrMuhMPqATH4Bhhe: protocol not supported
2020-10-29T16:44:54.205+0800	INFO	bitswap	messagequeue/messagequeue.go:496	Could not open message sender to peer 12D3KooWJC7MWWU9SUZi6eZWrDV4yB1hUR47yeHYHPpcMm74N2zt: protocol not supported
2020-10-29T16:44:54.209+0800	INFO	bitswap	messagequeue/messagequeue.go:496	Could not open message sender to peer 12D3KooWBsya7hTiDrXiysVeUTRuzTbcJWjTWFB79xfZb9kcTsEa: protocol not supported
2020-10-29T16:44:54.240+0800	INFO	bitswap	messagequeue/messagequeue.go:496	Could not open message sender to peer 12D3KooWSAH2G3QysvYVZ6KrV1QFz2hGBqdHXioEBHE5iji4XCtw: protocol not supported
2020-10-29T16:44:54.271+0800	INFO	bitswap	messagequeue/messagequeue.go:496	Could not open message sender to peer 12D3KooWLymd933ywV6dNeHGVBrKaYSuD9F6gdYCm4Q9vB7Bh2zi: protocol not supported
2020-10-29T16:44:54.276+0800	INFO	bitswap	messagequeue/messagequeue.go:496	Could not open message sender to peer 12D3KooWJQqNiCzUiwpbfCF2dzh1T2NWVS8gWF8L9KtdG1SMEVWW: protocol not supported
2020-10-29T16:44:54.280+0800	INFO	bitswap	messagequeue/messagequeue.go:496	Could not open message sender to peer 12D3KooWMLP52QcapVYDS9fVfmE2ggEgZXFvy95Fuqska3hmQ4PT: protocol not supported
2020-10-29T16:44:54.286+0800	INFO	bitswap	messagequeue/messagequeue.go:496	Could not open message sender to peer 12D3KooWAfpdzwcpqchJrRhJMY9g8i8Dr1VMiiSNB7YTfMy2rrE4: protocol not supported
2020-10-29T16:44:54.291+0800	INFO	bitswap	messagequeue/messagequeue.go:496	Could not open message sender to peer 12D3KooWK3bsNv8ZgEXBiRnzonvptkcZMkqqjXiJ4hcsQfaLkVS5: protocol not supported
2020-10-29T16:44:54.293+0800	INFO	bitswap	messagequeue/messagequeue.go:496	Could not open message sender to peer 12D3KooWSLWpmSKpmc5Prp7w76NT9nUZo4UoGq2qE1FkbyPaUoA2: protocol not supported
2020-10-29T16:44:54.296+0800	INFO	bitswap	messagequeue/messagequeue.go:496	Could not open message sender to peer 12D3KooWRkxH5TF4AYfNYvRKKKdyZ6jfrP1eyoxuQfxBrVsRNVdC: protocol not supported
2020-10-29T16:44:54.302+0800	INFO	bitswap	messagequeue/messagequeue.go:496	Could not open message sender to peer 12D3KooWDvwbbdLgBbuQ3MPPN7gos8XEXekTJxW5NX4DMCfXNUoZ: protocol not supported
2020-10-29T16:44:54.306+0800	INFO	bitswap	messagequeue/messagequeue.go:496	Could not open message sender to peer 12D3KooWL93GoHicYrNBvLLHS29Q5ZuEw6jnfaEMqqhwTvjEKGkn: protocol not supported
2020-10-29T16:44:54.306+0800	INFO	bitswap	messagequeue/messagequeue.go:496	Could not open message sender to peer 12D3KooWE99pZKP5324tZCA1rTNfi9AvoSgQsCFv8oEFRYPAPmKS: protocol not supported
```

**Comment by 3684993** [comment] 2020-11-12 00:58
me too
use snapshot  lotus daemon --import-snapshot minimal_finality_stateroots_latest...
sync status:
worker 0:
	Base:	[bafy2bzaceawswonmg2xf6bi6hflkiwirg36qhs6j5saajo6gbxlnfzp7lsqxe]
	Target:	[bafy2bzacea4f73wsbnriim4pxyo4xi2ejlhuvuxnrx4d4n7pkbbgm5vyabmbe bafy2bzacecn2fioiquk7kfq4th2d2g4yokkhsh4rpc64jvawo75y2iiqxhg6w bafy2bzaceb6bvc7qj7lsw63pm7tivuduk5ajhlx4xgrlulx7733tley5arqzq bafy2bzaceavx4dvuxjuuhvz7vrnda2wdc53r4mgjqjwarrosvtpk2v3bxevmo bafy2bzacebiv6zn7temjk6hxf5wqx6jkznnsydxkdvdiar4lyybi6pnejax4k bafy2bzacecr2oa6if5hfp7riil4poy4w2inwh22p3qv7e3q53bfjom2gnsxti] (227803)
	Height diff:	24097
	Stage: error
	Height: 203350
	Elapsed: 16.420502193s
	Error: collectChain syncMessages: message processing failed: validating block bafy2bzacebgnxtofhym3rr6ptnyalsjrm5auaibw6bagvin7ddpjprw4istbq: 1 error occurred:
	* parent state root did not match computed state (bafy2bzacebyd52mwsh3mmjqjxt3pen6egxmwzd2morlxfawas5nqgt7hz7244 != bafy2bzacearsnsorm3ieryksg57x3vm6iylqsdc3wjgltzflzzpw7zgnwkxje):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6
        /media/lotus/lotus/chain/sync.go:810


worker 1:
	Base:	[bafy2bzaceawswonmg2xf6bi6hflkiwirg36qhs6j5saajo6gbxlnfzp7lsqxe]
	Target:	[bafy2bzacedp7qbbzvdxgbgxol57tla3vbcpxuegzl7fnt5xbhvyi62h2edgse] (205927)
	Height diff:	2221
	Stage: error
	Height: 203350
	Elapsed: 1.964372935s
	Error: collectChain syncMessages: message processing failed: validating block bafy2bzacebgnxtofhym3rr6ptnyalsjrm5auaibw6bagvin7ddpjprw4istbq: 1 error occurred:
	* parent state root did not match computed state (bafy2bzacebyd52mwsh3mmjqjxt3pen6egxmwzd2morlxfawas5nqgt7hz7244 != bafy2bzacearsnsorm3ieryksg57x3vm6iylqsdc3wjgltzflzzpw7zgnwkxje):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6
        /media/lotus/lotus/chain/sync.go:810


worker 2:
	Base:	[bafy2bzaceawswonmg2xf6bi6hflkiwirg36qhs6j5saajo6gbxlnfzp7lsqxe]
	Target:	[bafy2bzacebbotwnuyambp7bhb3hvjtcv6dex2tx254hcoomn45ymnjl5jaz6e] (227804)
	Height diff:	24098
	Stage: error
	Height: 203350
	Elapsed: 18.15446676s
	Error: collectChain syncMessages: message processing failed: validating block bafy2bzacebgnxtofhym3rr6ptnyalsjrm5auaibw6bagvin7ddpjprw4istbq: 1 error occurred:
	* parent state root did not match computed state (bafy2bzacebyd52mwsh3mmjqjxt3pen6egxmwzd2morlxfawas5nqgt7hz7244 != bafy2bzacearsnsorm3ieryksg57x3vm6iylqsdc3wjgltzflzzpw7zgnwkxje):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6
        /media/lotus/lotus/chain/sync.go:810

**Comment by EmilyCaoHong** [comment] 2020-11-25 07:29
me too 
sync status:
worker 0:
        Base:   [bafy2bzaceadtdgt5ebhhhrsi4f6pnevwcgd3rqq4tjzqjnzqbv27f4r275zu6]
        Target: [bafy2bzacebyfihqpjuqw7di7ah5bshavta6pqfkjmv5q5erledwaqbor2j6km] (266098)
        Height diff:    532
        Stage: error
        Height: 0
        Elapsed: 36.296µs
        Error: chain linked to block marked previously as bad ([bafy2bzacebyfihqpjuqw7di7ah5bshavta6pqfkjmv5q5erledwaqbor2j6km], bafy2bzacec7pagck4mewwexxhd4ryhm2aj5q5iywvunukjbiy3wgb6vg5c6bm) (reason: linked to bafy2bzacedw3vdpfodfw6cdmm4jbtfohwqgbevu43kdobxt67qbbd4mtdhjdu caused by: [bafy2bzacecoxdq63inrzyv64pdnfaa5lpv36busleqfll6zr7nbnart6l4jby] 1 error occurred:
        * parent state root did not match computed state (bafy2bzacecygfpixj36tp4d7vrmfkksktk7m6adb4lt25yku3hnq3gxgeram4 != bafy2bzacednlept2c32haknb5fm7gw3tvi3bwopjwyig35esfrf4h3caqxg62):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6
        /home/circleci/project/chain/sync.go:810

)
worker 1:
        Base:   [bafy2bzaceadtdgt5ebhhhrsi4f6pnevwcgd3rqq4tjzqjnzqbv27f4r275zu6]
        Target: [bafy2bzacecgfptpk6riwwzvzxyrxyaaoxwosqgbmxjxh3plvct3cfqaq4vn72] (266098)
        Height diff:    532
        Stage: error
        Height: 0
        Elapsed: 30.26µs
        Error: chain linked to block marked previously as bad ([bafy2bzacecgfptpk6riwwzvzxyrxyaaoxwosqgbmxjxh3plvct3cfqaq4vn72], bafy2bzacec7pagck4mewwexxhd4ryhm2aj5q5iywvunukjbiy3wgb6vg5c6bm) (reason: linked to bafy2bzacedw3vdpfodfw6cdmm4jbtfohwqgbevu43kdobxt67qbbd4mtdhjdu caused by: [bafy2bzacecoxdq63inrzyv64pdnfaa5lpv36busleqfll6zr7nbnart6l4jby] 1 error occurred:
        * parent state root did not match computed state (bafy2bzacecygfpixj36tp4d7vrmfkksktk7m6adb4lt25yku3hnq3gxgeram4 != bafy2bzacednlept2c32haknb5fm7gw3tvi3bwopjwyig35esfrf4h3caqxg62):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6
        /home/circleci/project/chain/sync.go:810

)
worker 2:
        Base:   [bafy2bzaceadtdgt5ebhhhrsi4f6pnevwcgd3rqq4tjzqjnzqbv27f4r275zu6]
        Target: [bafy2bzaced2ywe7jl4rajyrbdzkkijcucncojqvvzi4ax63b5xq7dbz3kolte] (266098)
        Height diff:    532
        Stage: error
        Height: 0
        Elapsed: 63.615µs
        Error: chain linked to block marked previously as bad ([bafy2bzaced2ywe7jl4rajyrbdzkkijcucncojqvvzi4ax63b5xq7dbz3kolte], bafy2bzacec7pagck4mewwexxhd4ryhm2aj5q5iywvunukjbiy3wgb6vg5c6bm) (reason: linked to bafy2bzacedw3vdpfodfw6cdmm4jbtfohwqgbevu43kdobxt67qbbd4mtdhjdu caused by: [bafy2bzacecoxdq63inrzyv64pdnfaa5lpv36busleqfll6zr7nbnart6l4jby] 1 error occurred:
        * parent state root did not match computed state (bafy2bzacecygfpixj36tp4d7vrmfkksktk7m6adb4lt25yku3hnq3gxgeram4 != bafy2bzacednlept2c32haknb5fm7gw3tvi3bwopjwyig35esfrf4h3caqxg62):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6
        /home/circleci/project/chain/sync.go:810

**Comment by rjan90** [comment] 2022-06-08 10:31
Hey! Thanks for this issue report, I´m closing this as outdated. Please open a new ticket if you see a similar issue on newer versions of Lotus.

Thanks again!

**Closed by rjan90** 2022-06-08 10:31 UTC
Labels: area/chain
