### ISSUE TITLE
unknown actor code bafkqaetgnfwc6mrpon2g64tbm5sw22lomvza

### ISSUE THREAD

**Issue by astudnev** [filecoin-project/lotus#5371] opened 2021-01-18 17:07 UTC
rpc.state_account_key 'f03275'

returns the error:

Error response to Filecoin.StateAccountKey request: 1  failed to get account actor state for f03275: unknown actor code bafkqaetgnfwc6mrpon2g64tbm5sw22lomvza

While reverse works:

rpc.state_lookup_i_d 'f27fxgjifczreumheqdnlhm2esbt2mg5nugcfiyaq', nil

> f03275

It is unclear how to get public key. address for miner?

**Comment by donnol** [comment] 2021-05-06 10:12
Is there anything update?

**Comment by eskrano** [comment] 2021-10-30 12:48
Same issue

**Comment by AllanOricil** [comment] 2021-12-21 10:15
I get this when I run any of the  `lotus filplus` commands

**Comment by fadyanwar** [comment] 2021-12-30 20:58
Any updates on this?
I get this error during the initial sync using AMIs provided in the docs

 ⨎ lotus sync status
2021-12-30T20:57:41.259Z	WARN	cliutil	util/api.go:162	Couldn't load CLI token, capabilities may be limited: open /var/lib/lotus/token: permission denied
2021-12-30T20:57:41.260Z	WARN	cliutil	util/apiinfo.go:81	API Token not set and requested, capabilities might be limited.
sync status:
worker 4:
	Base:	[bafy2bzacecyu6bhlchulxvfbfrnzgyvxdtmbzgmzwlzkydiu4mq74ch5zcnke bafy2bzacebmo4unhmetnu5q6mhxorve44lifj33r7fppdsiwmz2fr35q5yqzc bafy2bzacea4b73tdwcdog53yrwseo7ubsvm7z7hp24w76gx2itqa75e5zq6ii]
	Target:	[bafy2bzacecqjb6e7mpyr5mxwwlkykv4ebsvykv4hrieutgs5yfw6cguv6mc6m bafy2bzacebyyqd4rfkfqfljucnfbo5qkmy7lrrgwfwnvfrt6e74e5yzeyetf2 bafy2bzacecreb2bswuae24quf4te3idtvizpkh6exurexfuy5hnmxnmsfndjk] (1419683)
	Height diff:	803
	Stage: error
	Height: 0
	Elapsed: 39.416µs
	Error: chain linked to block marked previously as bad ([bafy2bzacecqjb6e7mpyr5mxwwlkykv4ebsvykv4hrieutgs5yfw6cguv6mc6m bafy2bzacebyyqd4rfkfqfljucnfbo5qkmy7lrrgwfwnvfrt6e74e5yzeyetf2 bafy2bzacecreb2bswuae24quf4te3idtvizpkh6exurexfuy5hnmxnmsfndjk], bafy2bzaceax43ydhw5e3ll7jf2fck2rcrhsyououeinttd4c6vjfkpxbdwraw) (reason: linked to bafy2bzacecdnm4vd5fnzpgb63g53gpjr5go6hh56gdsn6ueyxdxsvvevlqqom caused by: [bafy2bzacecdjnhl3khyb7ne7i7hn3wc3ula4mlbmpilxiykxd5qdilaivciyq] getting parent weight: failed to load power actor state: unknown actor code bafkqaetgnfwc6nrpon2g64tbm5sxa33xmvza)
worker 5:
	Base:	[bafy2bzacecyu6bhlchulxvfbfrnzgyvxdtmbzgmzwlzkydiu4mq74ch5zcnke bafy2bzacebmo4unhmetnu5q6mhxorve44lifj33r7fppdsiwmz2fr35q5yqzc bafy2bzacea4b73tdwcdog53yrwseo7ubsvm7z7hp24w76gx2itqa75e5zq6ii]
	Target:	[bafy2bzacecxzsci3g7mnvbwre5rrll25655sdyn2vi45cg3lyjqab4tdm36ss] (1419684)
	Height diff:	804
	Stage: error
	Height: 0
	Elapsed: 39.257µs
	Error: chain linked to block marked previously as bad ([bafy2bzacecxzsci3g7mnvbwre5rrll25655sdyn2vi45cg3lyjqab4tdm36ss], bafy2bzacecqjb6e7mpyr5mxwwlkykv4ebsvykv4hrieutgs5yfw6cguv6mc6m) (reason: linked to bafy2bzaceax43ydhw5e3ll7jf2fck2rcrhsyououeinttd4c6vjfkpxbdwraw caused by: [bafy2bzacecdjnhl3khyb7ne7i7hn3wc3ula4mlbmpilxiykxd5qdilaivciyq] getting parent weight: failed to load power actor state: unknown actor code bafkqaetgnfwc6nrpon2g64tbm5sxa33xmvza)
worker 6:
	Base:	[bafy2bzacecyu6bhlchulxvfbfrnzgyvxdtmbzgmzwlzkydiu4mq74ch5zcnke bafy2bzacebmo4unhmetnu5q6mhxorve44lifj33r7fppdsiwmz2fr35q5yqzc bafy2bzacea4b73tdwcdog53yrwseo7ubsvm7z7hp24w76gx2itqa75e5zq6ii]
	Target:	[bafy2bzacea7d5pjuy6mwr5zee53zvnoxmrulpfocmsq7l476yvyfr7geoqlnu bafy2bzaceawa4ez6nrn7m3hpov33efrquakpmwgeyuiua2eloxzj5yjttymz2] (1419701)
	Height diff:	821
	Stage: error
	Height: 1419701
	Elapsed: 1.453486834s
	Error: chain contained block marked previously as bad ([bafy2bzacea7d5pjuy6mwr5zee53zvnoxmrulpfocmsq7l476yvyfr7geoqlnu bafy2bzaceawa4ez6nrn7m3hpov33efrquakpmwgeyuiua2eloxzj5yjttymz2], bafy2bzacecxzsci3g7mnvbwre5rrll25655sdyn2vi45cg3lyjqab4tdm36ss) (reason: linked to bafy2bzacecqjb6e7mpyr5mxwwlkykv4ebsvykv4hrieutgs5yfw6cguv6mc6m caused by: [bafy2bzacecdjnhl3khyb7ne7i7hn3wc3ula4mlbmpilxiykxd5qdilaivciyq] getting parent weight: failed to load power actor state: unknown actor code bafkqaetgnfwc6nrpon2g64tbm5sxa33xmvza)

**Comment by Schwartz10** [comment] 2022-04-05 20:02
I'm running into this same scenario with Actor Code `bafkqadtgnfwc6nzpnv2wy5djonuwo` (`fil/7/multisig`)

Interestingly enough, the `fil/7/account` actor gets resolved without an issue.

I was stack tracing the code (without actually running it), and i wonder if `snap.getActor` is a culprit? https://github.com/filecoin-project/lotus/blob/214c32d2ef858d7bea45799ee8adb447db2667ae/chain/state/statetree.go#L121

**Comment by fadyanwar** [comment] 2022-04-05 21:18
@Schwartz10 @rjan90 I resolved this by building from source

**Comment by Schwartz10** [comment] 2022-04-07 22:13
@fadyanwar thanks for the tip! I can see the scenarios when rebuilding might solve this issue, but in my scenario, I'm getting this error on the public Glif endpoint. The public Glif node gets rebuilt on every release

**Comment by arajasek** [comment] 2022-04-09 17:25
So this isn't a bug -- this endpoint is intended only to get the public key address of _accounts_ (secp or bls) from their ID addresses. It's not expected to work on multisigs / miners / payment channels / etc.

How much would people like such a method? It wouldn't be hard to write such a method, but it would definitely be slow -- we don't maintain an `ID -> Robust` map for things that aren't accounts, so the work involved would be inverting the entire Init actor state's map. Easy to implement, but slow to run.

**Comment by arajasek** [comment] 2022-04-11 14:00
@Schwartz10 indicated there's interest in having such a method -- users that need fast lookup can cache the results, so a slow impl is fine.

@geoff-vball Would you be willing to take this on? The work required is:

- Add a new API method called `StateLookupRobustAddress` that takes an ID address and a TSK.
- Implement this method by loading the init actor state **at finality** and calling [this method](https://github.com/filecoin-project/lotus/blob/1449644c343340a60d80688931cd709d85220686/chain/actors/builtin/init/init.go#L160). 
- (optional) Improve the implementation by first calling `StateAccountKey` (for a nice first lookup for accounts).

**Closed** 2022-04-19 15:37 UTC
Labels: kind/bug, need/analysis
