### ISSUE TITLE
Finalized Sectors take long time

### ISSUE THREAD

**Issue by hengic** [filecoin-project/lotus#3398] opened 2020-08-30 02:00 UTC
**Describe the bug**
I have 2 sectors in the state of FinalizeSector more than half an hour, which makes the local storage resource not released soon and slow down the process of sealing. After analysis, I guess it's because the sector A is processed by Node 1 at PC2 but processed by Node 2 at C2. So that, it opens a window for Node 1 after PC2. The sector cannot finalized immediately for missing window of Node 2.

**To Reproduce**
1. Run Node 1 and Node 2 only process type of PC2 and Commit with argument --addpiece=false --precommit1=false --precommit2=true --commit=true
2. Let node 1 takes a sector at PC2
3. Make the same sector is taken by Node 2 at C2

**Expected behavior**
The sector after C2 can be finalized in a few minutes.

**Screenshots**
<img width="645" alt="Screen Shot 2020-08-30 at 9 58 43 AM" src="https://user-images.githubusercontent.com/22890997/91649486-71ecbe00-eaa7-11ea-8290-d652bf25c723.png">
My sectors 8 and 11 are pending to finalize but there's no open windows for worker 5. see sched-diag. So, they have to wait a long time for the next open window of worker 5.

**Version (run `lotus version`):**
Daemon:  0.5.6+git.606a58bc.dirty+api0.13.0
Local: lotus version 0.5.6+git.606a58bc.dirty

**Additional context**

**Comment by Reiers** [comment] 2022-03-09 19:55
Hi @hengic 

Thanks for the report. This is should be fixed in the latest release, and Im not able to reproduce here. 
Please upgrade Lotus.

Link to latest tags [here.](https://github.com/filecoin-project/lotus/tags)

Closing Lotus issue ticket.

If you are still experiencing problems, open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

**Closed by Reiers** 2022-03-09 19:55 UTC
