### ISSUE TITLE
RPC client error AGAIN

### ISSUE THREAD

**Issue by long568** [filecoin-project/lotus#3385] opened 2020-08-29 01:27 UTC
```
Aug 29 01:22:57 m001 lotus-miner[128150]: 2020-08-29T01:22:57.553Z        ERROR        rpc        go-jsonrpc@v0.1.2-0.20200822201400-474f4fdccc52/websocket.go:497        sending ping message: write tcp 127.0.0.1:37170->127.0.0.1:1234: use of closed network connection
Aug 29 01:22:58 m001 lotus-miner[128150]: 2020-08-29T01:22:58.415Z        INFO        events        events/events.go:103        restarting listenHeadChanges
Aug 29 01:22:58 m001 lotus-miner[128150]: 2020-08-29T01:22:58.415Z        ERROR        events        events/events.go:94        listen head changes errored: listenHeadChanges ChainNotify call failed: RPC client error: sendRequest failed: websocket routine exiting
Aug 29 01:22:58 m001 lotus-miner[128150]: 2020-08-29T01:22:58.685Z        ERROR        miner        miner/miner.go:159        failed to get best mining candidate: RPC client error: sendRequest failed: websocket routine exiting
Aug 29 01:22:59 m001 lotus-miner[128150]: 2020-08-29T01:22:59.415Z        INFO        events        events/events.go:103        restarting listenHeadChanges
Aug 29 01:22:59 m001 lotus-miner[128150]: 2020-08-29T01:22:59.415Z        ERROR        events        events/events.go:94        listen head changes errored: listenHeadChanges ChainNotify call failed: RPC client error: sendRequest failed: websocket routine exiting
Aug 29 01:22:59 m001 lotus-miner[128150]: 2020-08-29T01:22:59.415Z        INFO        events        events/events.go:103        restarting listenHeadChanges
Aug 29 01:22:59 m001 lotus-miner[128150]: 2020-08-29T01:22:59.415Z        ERROR        events        events/events.go:94        listen head changes errored: listenHeadChanges ChainNotify call failed: RPC client error: sendRequest failed: websocket routine exiting
Aug 29 01:23:00 m001 lotus-miner[128150]: 2020-08-29T01:23:00.415Z        INFO        events        events/events.go:103        restarting listenHeadChanges
Aug 29 01:23:00 m001 lotus-miner[128150]: 2020-08-29T01:23:00.415Z        ERROR        events        events/events.go:94        listen head changes errored: listenHeadChanges ChainNotify call failed: RPC client error: sendRequest failed: websocket routine exiting

```

**Comment by arajasek** [comment] 2020-09-02 18:39
Duplicate of #3370

**Closed by arajasek** 2020-09-02 18:39 UTC
