### ISSUE TITLE
ProveCommitSector method failed

### ISSUE THREAD

**Issue by hfmhx** [filecoin-project/lotus#3247] opened 2020-08-22 13:24 UTC
**Describe the bug**
ProveCommitSector method failed

**To Reproduce**
1. Seal and prove normally
2. Occasional problems

**Expected behavior**
Start lotus-miner lotus-worker for PreCommit1 PreCommit2 Commit1 Commit2

**Screenshots**
 submitting sector proof failed (exit=7, msg=bafy2bzacedpkb7c6bu3xo33yazhjflzw2oz3l7ro2af6nm7ojix43lqlndpjs) 
![image](https://user-images.githubusercontent.com/44537744/90956959-92bc7e80-e4bd-11ea-8a9c-d60469232c4a.png)

**Version (run `lotus version`):**
I made some changes to ntwk-calibration, but did not include the SendMsg/Mpool part, so the git version does not exist on the ntwk-calibration branch
Daemon: 0.4.6+git.e195c86.dirty+api0.11.0
Local: lotus version 0.4.6+git.e195c86.dirty

**Additional context**
We add code to resubmit the same proof and the result is successful
![image](https://user-images.githubusercontent.com/44537744/90957004-cc8d8500-e4bd-11ea-8c8d-4ab31f92574e.png)
[event;sealing.SectorCommitted] {"User":{"Message":{"/":"bafy2bzaceccgzyi3t2cywo5vhqobv3jq6abvapim4n5zyb4d76kwmardq7dxc"}

**Comment by magik6k** [comment] 2020-10-28 19:24
Looks like gas estimation issue (exit 7 is `SysErrOutOfGas`).

Not sure if this got fixed

**Comment by Reiers** [comment] 2021-12-12 23:45
The issue is outdated.

Closing ticket.

**Closed by Reiers** 2021-12-12 23:45 UTC
