### ISSUE TITLE
when I run 2nd time, failed to load miner actor state: actor not found

### ISSUE THREAD

**Issue by Malone-Ma** [filecoin-project/lotus#668] opened 2019-11-22 08:50 UTC
The 1st time, when I run : lotus-storage-miner run, it success. but the 2nd time, actor not found...pls see the warn as below...

`2019-11-22T16:36:40.204+0800	WARN	main	lotus-storage-miner/main.go:73	could not build arguments for function "github.com/filecoin-project/lotus/node/modules".HandleDeals (/root/lotus/node/modules/storageminer.go:120): failed to build *deals.Provider: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build *storage.Miner: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build *sectorbuilder.SectorBuilder: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build *sectorbuilder.Config: function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12) returned a non-nil error: failed to load miner actor state: actor not found`

**Comment by magik6k** [comment] 2019-11-22 18:19
Is your node synced - `lotus sync wait`?

**Comment by Malone-Ma** [comment] 2019-11-22 18:20
> Is your node synced - `lotus sync wait`?

yes, synced...

**Comment by barnettshao** [comment] 2019-11-25 14:39
I got the same problem. when I use the command `lotus sync wait`, even through the response is `Done`, I still can't init my storage miner success, with the error `actor not found`.
![10-2](https://user-images.githubusercontent.com/10030218/69549557-77771e00-0fd4-11ea-975e-5e00551e9d8d.png)

**Comment by magik6k** [comment] 2019-12-06 01:41
It's very likely to have been caused by buggy mempool on a fork, which should be fixed now. Please open a new issue if this happens again

**Closed by magik6k** 2019-12-06 01:41 UTC
