### ISSUE TITLE
The lotus daemon  went down shortly after Block Sync is complete.

### ISSUE THREAD

**Issue by qkrwnsgh1288** [filecoin-project/lotus#4706] opened 2020-09-03 11:47 UTC
**Describe the bug**
I started the daemon with the lotus full node. and the lotus daemon went down shortly after Block Sync was completed.

**To Reproduce**
1. Run `nohup lotus daemon 2>&1 >> lotus.log &`
2. See error
```
2020-09-03T11:22:52.275Z        INFO    bitswap_network network/ipfs_impl.go:200        failed to open stream to 12D3KooWDiqwAMtGPh4ZyMVrxxN3Wz7jvoTCcmCBSSRQx4HKz5zH: context canceled
2020-09-03T11:22:52.275Z        INFO    bitswap_network network/ipfs_impl.go:200        failed to open stream to 12D3KooWQRGQeNocxBTRvypYzzNsee4oPApzyYfujpfPEt6Fj96A: context canceled
2020-09-03T11:22:54.839Z        INFO    bitswap_network network/ipfs_impl.go:209        failed to send message to 12D3KooWAk1U1f6MLuqteThevHCaeaLuWfVSi15nLGu9XbEKP28B: stream reset
2020-09-03T11:22:58.398Z        INFO    hello   hello/hello.go:179      time offset     {"offset": 0.047866329, "peerid": "12D3KooWPmhviDyhP3McYcEbAvUY29tH9Uci8FCfSCJF9fQHb9Gt"}
2020-09-03T11:22:58.346Z        INFO    hello   hello/hello.go:179      time offset     {"offset": 0.117946587, "peerid": "12D3KooWQYzqnLASJAabyMpPb1GcWZvNSe7JDcRuhdRqonFoiK9W"}
2020-09-03T11:22:57.882Z        INFO    drand   log/log.go:124          {"level": "error", "optimizing_client": "endpoint temporarily down", "client": "HTTP(\"https://pl-eu.incentinet.drand.sh\").(+verifier)", "err": "doing request: Get \"https://pl-eu.incentinet.drand.sh/public/1\": context deadline exceeded"}
2020-09-03T11:22:58.338Z        INFO    hello   hello/hello.go:179      time offset     {"offset": 0.063518595, "peerid": "12D3KooWMB53UKhXMuMPAYmQrcrPQpL85SoWKS8xSj8QTUrdtaBy"}
2020-09-03T11:22:59.004Z        INFO    hello   hello/hello.go:179      time offset     {"offset": -0.050913044, "peerid": "12D3KooWJvAtjvVqjBqttLSZ2XDsCQEWH86RbKLjkPXhaDMTBmfs"}
2020-09-03T11:22:58.916Z        INFO    hello   hello/hello.go:179      time offset     {"offset": -0.129084121, "peerid": "12D3KooWC4zCqKBGxbGVpfxED331vYNr57Bs9WfTiFCX21HBzrdY"}
2020-09-03T11:22:59.453Z        WARN    pubsub  go-libp2p-pubsub@v0.3.6-0.20200901174250-06a12f17b7de/pubsub.go:467     already have connection to peer: 12D3KooWQYzqnLASJAabyMpPb1GcWZvNSe7JDcRuhdRqonFoiK9W
2020-09-03T11:23:03.769Z        INFO    hello   hello/hello.go:179      time offset     {"offset": 0.052502923, "peerid": "12D3KooWEtsFuyuwzn8HxCTsReKXTACsaFn8JwrRukcAwfxhenY3"}
2020-09-03T11:23:04.853Z        INFO    drand   log/log.go:124          {"level": "error", "optimizing_client": "endpoint temporarily down", "client": "HTTP(\"https://pl-us.incentinet.drand.sh\").(+verifier)", "err": "doing request: Get \"https://pl-us.incentinet.drand.sh/public/1\": context deadline exceeded"}
2020-09-03T11:23:05.319Z        INFO    hello   hello/hello.go:179      time offset     {"offset": 0.472993769, "peerid": "12D3KooWSHyMLRhdVqLfphyfPe1JFKptUNNvhqv7Gh6cCgH8fhcr"}
2020-09-03T11:23:04.460Z        INFO    hello   hello/hello.go:179      time offset     {"offset": -0.240508895, "peerid": "12D3KooWLeSJQXC8ZDsQxYUQD3FkJ1vESyvZKhntHWL2u8wo2wXh"}
2020-09-03T11:23:04.167Z        INFO    hello   hello/hello.go:179      time offset     {"offset": -0.201983412, "peerid": "12D3KooWKgHZNLtBSDVsF9vDB6BKHhxF8BYMenvea5KUG1spfSfT"}
2020-09-03T11:23:08.012Z        WARN    pubsub  go-libp2p-pubsub@v0.3.6-0.20200901174250-06a12f17b7de/pubsub.go:467     already have connection to peer: 12D3KooWKgHZNLtBSDVsF9vDB6BKHhxF8BYMenvea5KUG1spfSfT
2020-09-03T11:23:09.232Z        INFO    hello   hello/hello.go:179      time offset     {"offset": -0.378980871, "peerid": "12D3KooWKobRHMoBTUDpZh9ReVwRwygzm4uHpXnGMYT9HTokwnoX"}
2020-09-03T11:23:09.089Z        INFO    hello   hello/hello.go:179      time offset     {"offset": 0.335160956, "peerid": "12D3KooW9yeKXha4hdrJKq74zEo99T8DhriQdWNoojWnnQbsgB3v"}
2020-09-03T11:23:11.888Z        INFO    pubsub  go-libp2p-pubsub@v0.3.6-0.20200901174250-06a12f17b7de/gossipsub.go:1490 peer 12D3KooWEdWFEsZ2i44Y2yuEciMaBnkHiBKUdKt3ehXRpNjScYyH didn't follow up in 1 IWANT requests; adding penalty
2020-09-03T11:23:12.234Z        INFO    drand   log/log.go:124          {"level": "error", "optimizing_client": "endpoint temporarily down", "client": "HTTP(\"https://pl-sin.incentinet.drand.sh\").(+verifier)", "err": "doing request: Get \"https://pl-sin.incentinet.drand.sh/public/1\": context deadline exceeded"}
2020-09-03T11:23:14.042Z        INFO    hello   hello/hello.go:179      time offset     {"offset": -0.244210961, "peerid": "12D3KooWEgY4PMUMnuWbp5vxrryrL3YQnADboaDRh7cdn3xiP1y3"}
2020-09-03T11:23:13.841Z        INFO    hello   hello/hello.go:179      time offset     {"offset": -0.342071291, "peerid": "12D3KooWEAXN9ZX2eajHQCawuDzKwkBBkn44aHBHmg2ZUPJoyzYJ"}
2020-09-03T11:23:18.884Z        INFO    drand   log/log.go:124          {"level": "error", "optimizing_client": "endpoint temporarily down", "client": "EmptyClient.(+watcher).(+verifier)", "err": "not supported"}
2020-09-03T11:23:17.105Z        INFO    bitswap_network network/ipfs_impl.go:200        failed to open stream to 12D3KooW9yeKXha4hdrJKq74zEo99T8DhriQdWNoojWnnQbsgB3v: context canceled
2020-09-03T11:23:20.376Z        INFO    drand   log/log.go:124          {"level": "error", "polling_client": "failed to watch", "err": "doing request: Get \"https://pl-sin.incentinet.drand.sh/public/108579\": net/http: TLS handshake timeout"}
2020-09-03T11:23:24.275Z        WARN    pubsub  go-libp2p-pubsub@v0.3.6-0.20200901174250-06a12f17b7de/pubsub.go:514     peer declared dead but still connected; respawning writer: 12D3KooWMB53UKhXMuMPAYmQrcrPQpL85SoWKS8xSj8QTUrdtaBy
2020-09-03T11:23:37.793Z        INFO    pubsub  go-libp2p-pubsub@v0.3.6-0.20200901174250-06a12f17b7de/gossipsub.go:1490 peer 12D3KooWN2BZbAY576apUqTSdJgPRGuX299h6ckrFTnhYDuBTsrk didn't follow up in 1 IWANT requests; adding penalty
2020-09-03T11:23:41.864Z        INFO    pubsub  go-libp2p-pubsub@v0.3.6-0.20200901174250-06a12f17b7de/gossipsub.go:1490 peer 12D3KooWHsom4KeNJDDtkPpBtuxdmTv3nQ2Be1vf3y4RbRs7ETt8 didn't follow up in 1 IWANT requests; adding penalty
2020-09-03T11:23:46.138Z        INFO    pubsub  go-libp2p-pubsub@v0.3.6-0.20200901174250-06a12f17b7de/gossipsub.go:1490 peer 12D3KooWCBoTFAXKkZvJzMhc1wFm53KGZMAJ7Aw9pPmB3RNN3BSe didn't follow up in 1 IWANT requests; adding penalty
```
This is the contents of the `lotus.log` file, and no errors were printed.

**Version (run `lotus version`):**
lotus version 0.5.10+git.38cb260

```
$ ulimit -a
open files                      (-n) 500000

$ cat /etc/*release
DISTRIB_DESCRIPTION="Ubuntu 16.04.7 LTS"
VERSION="16.04.7 LTS (Xenial Xerus)"

Ram: 16GB
vCPU: 4
ECU: 16
```

**Comment by jennijuju** [comment] 2020-11-04 22:20
Closing since it's a very old ticket.. please reopen if the issue is stilll there!

**Closed by jennijuju** 2020-11-04 22:20 UTC
