### ISSUE TITLE
flaky TestZeroPricePerByteRetrieval

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#9220] opened 2022-08-26 19:38 UTC
https://app.circleci.com/pipelines/github/filecoin-project/lotus/22785/workflows/8afdf873-afcc-493a-a2cc-2dfb3d847d06/jobs/563518

**Comment by magik6k** [comment] 2022-08-29 07:09
```
[...]
2022-08-26T19:36:37.492Z	WARN	net/identify	identify/id.go:330	failed to identify 12D3KooWFSF9g8Pma2Qo9Hoeyp6HhASz5pCF1YJqoBhhtWm1tQHT: write tcp4 127.0.0.1:34837->127.0.0.1:38715: write: connection reset by peer
panic: Fail in goroutine after TestQuotePriceForUnsealedRetrieval has completed

goroutine 1096 [running]:
testing.(*common).Fail(0xc000603860)
	/usr/local/go/src/testing/testing.go:710 +0xe5
testing.(*common).Errorf(0x40ea988, {0x3c90594, 0x670767}, {0xc001b2a3b0, 0x3822200, 0x401})
	/usr/local/go/src/testing/testing.go:818 +0x56
github.com/stretchr/testify/assert.Fail({0x7f062e007e58, 0xc000603860}, {0xc004aea600, 0x2e9}, {0x0, 0x0, 0x0})
	/home/circleci/go/pkg/mod/github.com/stretchr/testify@v1.8.0/assert/assertions.go:264 +0x384
github.com/stretchr/testify/assert.NoError({0x7f062e007e58, 0xc000603860}, {0x439e500, 0xc00995c980}, {0x0, 0x0, 0x0})
	/home/circleci/go/pkg/mod/github.com/stretchr/testify@v1.8.0/assert/assertions.go:1392 +0x105
github.com/stretchr/testify/require.NoError({0x43b48a0, 0xc000603860}, {0x439e500, 0xc00995c980}, {0x0, 0x0, 0x0})
	/home/circleci/go/pkg/mod/github.com/stretchr/testify@v1.8.0/require/require.go:1261 +0x96
github.com/filecoin-project/lotus/itests/kit.(*BlockMiner).MineBlocksMustPost.func1.1(0x0, 0x0, {0x439e500, 0xc00995c980})
	/home/circleci/project/itests/kit/blockminer.go:195 +0xc8
github.com/filecoin-project/lotus/miner.(*Miner).mine(0xc000ec01e0, {0x43e8ef0, 0xc00005a080})
	/home/circleci/project/miner/miner.go:287 +0x3ac
created by github.com/filecoin-project/lotus/miner.(*Miner).Start
	/home/circleci/project/miner/miner.go:147 +0x137
FAIL	command-line-arguments	54.314s

=== Failed
=== FAIL: command-line-arguments TestZeroPricePerByteRetrieval (unknown)
2022-08-26T19:36:36.626Z	ERROR	miner	miner/miner.go:471	completed mineOne	{"tookMilliseconds": 8, "forRound": 673, "baseEpoch": 672, "baseDeltaSeconds": 9979893, "nullRounds": 0, "lateStart": true, "beaconEpoch": 773, "lookbackEpochs": 900, "networkPowerAtLookback": "40960", "minerPowerAtLookback": "40960", "isEligible": true, "isWinner": true, "error": "failed to create block: failed to get miner worker: (get sset) failed to load miner actor state: unknown actor code bafk2bzacebucngwdhxtod2gvv52adtdssafyg43znsoy4omtfkkqe2hbhvxeu", "errorVerbose": "failed to create block:\n    github.com/filecoin-project/lotus/miner.(*Miner).mineOne\n        /home/circleci/project/miner/miner.go:559\n  - failed to get miner worker:\n    github.com/filecoin-project/lotus/chain/consensus/filcns.(*FilecoinEC).CreateBlock\n        /home/circleci/project/chain/consensus/filcns/mine.go:35\n  - (get sset) failed to load miner actor state:\n    github.com/filecoin-project/lotus/chain/stmgr.GetMinerWorkerRaw\n        /home/circleci/project/chain/stmgr/actors.go:43\n  - unknown actor code bafk2bzacebucngwdhxtod2gvv52adtdssafyg43znsoy4omtfkkqe2hbhvxeu:\n    github.com/filecoin-project/lotus/chain/actors/builtin/miner.Load\n        /home/circleci/project/chain/actors/builtin/miner/miner.go:67"}
2022-08-26T19:36:36.626Z	ERROR	miner	miner/miner.go:283	mining block failed: failed to create block:
    github.com/filecoin-project/lotus/miner.(*Miner).mineOne
        /home/circleci/project/miner/miner.go:559
  - failed to get miner worker:
    github.com/filecoin-project/lotus/chain/consensus/filcns.(*FilecoinEC).CreateBlock
        /home/circleci/project/chain/consensus/filcns/mine.go:35
  - (get sset) failed to load miner actor state:
    github.com/filecoin-project/lotus/chain/stmgr.GetMinerWorkerRaw
        /home/circleci/project/chain/stmgr/actors.go:43
  - unknown actor code bafk2bzacebucngwdhxtod2gvv52adtdssafyg43znsoy4omtfkkqe2hbhvxeu:
    github.com/filecoin-project/lotus/chain/actors/builtin/miner.Load
        /home/circleci/project/chain/actors/builtin/miner/miner.go:67
[...]
```

So duplicate of https://github.com/filecoin-project/lotus/issues/9215

**Closed by magik6k** 2022-08-29 07:09 UTC
Labels: impact/test-flakiness
