### ISSUE TITLE
Lotus computes 5 windowPoSt's, when I only have 3 deadlines

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus#5534] opened 2021-02-05 06:55 UTC
**Describe the bug**
I did some scrubbing yesterday on one of my storage-servers RAID-array, this process was running when my miner where going to do windowPoSt. The windowPoSt took longer than usual because of this, and ended up not making the time deadline. What is interesting from the logs (and thus maybe worth this issue) is that it tried to compute 5 windowPoSt's (while I only have 3 proving deadlines), and that it restarts windowPoSt on a deadline, if the previous proof is finished computing after the new window has started.

```
2021-02-05T01:52:03.483+0100	WARN	storageminer	storage/wdpost_run.go:225	Checked sectors	{"checked": 1802, "good": 1802}
2021-02-05T01:52:03.582+0100	INFO	storageminer	storage/wdpost_run.go:578	running window post	{"chain-random": "TODm4HjfD+EANw/sB27lo20wwpMZjCityHVLX/s8ipk=", "deadline": {"CurrentEpoch":472664,"PeriodStart":472684,"Index":0,"Open":472684,"Close":472744,"Challenge":472664,"FaultCutoff":472614,"WPoStPeriodDeadlines":48,"WPoStProvingPeriod":2880,"WPoStChallengeWindow":60,"WPoStChallengeLookback":20,"FaultDeclarationCutoff":70}, "height": "472664", "skipped": 0}
2021-02-05T02:32:00.378+0100	WARN	storageminer	storage/wdpost_run.go:225	Checked sectors	{"checked": 13, "good": 13}
2021-02-05T02:32:00.381+0100	INFO	storageminer	storage/wdpost_run.go:578	running window post	{"chain-random": "7JqKjHDy4ZIcwkkH7hnrDTSYN3tM/FU9R48nmdMSflQ=", "deadline": {"CurrentEpoch":472744,"PeriodStart":472684,"Index":1,"Open":472744,"Close":472804,"Challenge":472724,"FaultCutoff":472674,"WPoStPeriodDeadlines":48,"WPoStProvingPeriod":2880,"WPoStChallengeWindow":60,"WPoStChallengeLookback":20,"FaultDeclarationCutoff":70}, "height": "472744", "skipped": 0}
2021-02-05T02:37:57.640+0100	INFO	storageminer	storage/wdpost_run.go:594	computing window post	{"batch": 0, "elapsed": 2754.057839028}
2021-02-05T02:38:00.319+0100	WARN	storageminer	storage/wdpost_run.go:225	Checked sectors	{"checked": 13, "good": 13}
2021-02-05T02:38:00.346+0100	INFO	storageminer	storage/wdpost_run.go:578	running window post	{"chain-random": "7JqKjHDy4ZIcwkkH7hnrDTSYN3tM/FU9R48nmdMSflQ=", "deadline": {"CurrentEpoch":472756,"PeriodStart":472684,"Index":1,"Open":472744,"Close":472804,"Challenge":472724,"FaultCutoff":472674,"WPoStPeriodDeadlines":48,"WPoStProvingPeriod":2880,"WPoStChallengeWindow":60,"WPoStChallengeLookback":20,"FaultDeclarationCutoff":70}, "height": "472756", "skipped": 0}
2021-02-05T02:59:36.696+0100	INFO	storageminer	storage/wdpost_run.go:594	computing window post	{"batch": 0, "elapsed": 1656.315124424}
2021-02-05T02:59:37.072+0100	INFO	storageminer	storage/wdpost_run.go:750	Submitted window post: bafy2bzaceaa32ikzpgoak54waw4gwo5bb74g7z5ulhi4hl5vz72ppbk54yio4
2021-02-05T02:59:59.926+0100	WARN	storageminer	storage/wdpost_run.go:225	Checked sectors	{"checked": 42, "good": 42}
2021-02-05T02:59:59.939+0100	INFO	storageminer	storage/wdpost_run.go:578	running window post	{"chain-random": "5olfbEo1IVn8HKttHPxDTTpOD8lMe/WrPKgXKTnEcyw=", "deadline": {"CurrentEpoch":472800,"PeriodStart":472684,"Index":2,"Open":472804,"Close":472864,"Challenge":472784,"FaultCutoff":472734,"WPoStPeriodDeadlines":48,"WPoStProvingPeriod":2880,"WPoStChallengeWindow":60,"WPoStChallengeLookback":20,"FaultDeclarationCutoff":70}, "height": "472800", "skipped": 0}
2021-02-05T03:20:53.366+0100	INFO	storageminer	storage/wdpost_run.go:594	computing window post	{"batch": 0, "elapsed": 2573.019802618}
2021-02-05T03:21:00.409+0100	WARN	storageminer	storage/wdpost_run.go:225	Checked sectors	{"checked": 42, "good": 42}
2021-02-05T03:21:00.418+0100	INFO	storageminer	storage/wdpost_run.go:578	running window post	{"chain-random": "5olfbEo1IVn8HKttHPxDTTpOD8lMe/WrPKgXKTnEcyw=", "deadline": {"CurrentEpoch":472842,"PeriodStart":472684,"Index":2,"Open":472804,"Close":472864,"Challenge":472784,"FaultCutoff":472734,"WPoStPeriodDeadlines":48,"WPoStProvingPeriod":2880,"WPoStChallengeWindow":60,"WPoStChallengeLookback":20,"FaultDeclarationCutoff":70}, "height": "472842", "skipped": 0}
2021-02-05T03:42:24.165+0100	INFO	storageminer	storage/wdpost_run.go:594	computing window post	{"batch": 0, "elapsed": 2544.225575705}
2021-02-05T04:01:46.575+0100	INFO	storageminer	storage/wdpost_run.go:594	computing window post	{"batch": 0, "elapsed": 2446.156413789}
```
So why does it compute 5 window post's when I only have 3 deadlines?

**_Proving deadlines_**
```
deadline  partitions  sectors (faults)  proven partitions
0         1           1808 (1802)       0
1         1           13 (0)            0
2         1           42 (42)           0

```

**To Reproduce**
1. Run raid-maintenance
2. Computing windowPoSt is submitted after a new deadline has started, restarts computing windowPoSt on the second process.
3. Ended up computing 5 window post's, when I only have 3 deadlines.

**Version (run `lotus version`):**
Daemon:  1.4.0+git.e9989d0e4+api1.0.0
Local: lotus version 1.4.0+git.e9989d0e4

**Additional context**
Running windowPoSt on CPU

**Comment by PatrickDeuse** [comment] 2021-02-09 15:45
douplicate https://github.com/filecoin-project/lotus/issues/5560

didn't see that this is actually doing duplicates too here!

@rjan90 maybe add that the posts calculated are actually duplicates. calculating the same partition more than once.

**Comment by PatrickDeuse** [comment] 2021-02-09 15:48
maybe even a duplicate of

https://github.com/filecoin-project/lotus/issues/5186

this issue seems to be a long time favorite...

**Comment by rjan90** [comment] 2021-12-17 08:06
Adding a partial #stale and partial #outdated for this one @Reiers. 

From my standpoint this has not happened again since this observation. This is partially because windowPoSt has become faster, and that I also have been more aware of not doing storage-maintenance during windowPoSt. So that is the #outdated part.

The #stale part: I consider this behaviour as not ideal as the the consequences for doing what seems to be multiple windowPoSt at the same time are unknown. If every deadline was full and needed proving, I can see that restarting an already started windowPoSt, if the previous windowPoSt if one is late, might cause cascading failures.

**Closed** 2022-01-14 00:36 UTC
Labels: area/proving
