### ISSUE TITLE
StorageDealError ClientGetDealInfo:error in deal activation: handling applied event: deal wasn't active

### ISSUE THREAD

**Issue by hfmhx** [filecoin-project/lotus#3343] opened 2020-08-27 08:02 UTC
**Describe the bug**
We encountered this error when storing the sector, but it seems abnormal：
`StorageDealError ClientGetDealInfo: {"jsonrpc":"2.0","result":{"ProposalCid":{"/":"bafyreifbus5tnzt3p7u7skuk76u43rm2x6oypil5w3v6lj2ocyy5fhs2mu"},"State":26,"Message":"error in deal activation: handling applied event: deal wasn't active: deal=9090, parentState=bafy2bzacediy6kmibh3lrjsyebst6ult2zxw5ksgsbkw7ktrnwjwjqy7kdh5q, h=4249","Provider":"t01xxx","DataRef":null,"PieceCID":{"/":"baga6ea4seaqphvc2cyoky4rc3hpbtvia6njuypqxyv7l7hyjmrjybxdol2acyii"},"Size":133169152,"PricePerEpoch":"62500000","D..`

**the log**
`2020-08-26T09:27:33.876Z#011ERROR#011events#011events/events_called.go:252#011chain trigger (@H 4249, triggered @ 4255) failed: deal wasn't active: deal=9090, parentState=bafy2bzacediy6kmibh3lrjsyebst6ult2zxw5ksgsbkw7ktrnwjwjqy7kdh5q, h=4249
Aug 26 09:27:33 ubuntu lotus-miner[647942]: 2020-08-26T09:27:33.877Z#011INFO#011markets#011loggers/loggers.go:19#011storage event#011{"name": "ProviderEventDealActivationFailed", "proposal CID": "bafyreifbus5tnzt3p7u7skuk76u43rm2x6oypil5w3v6lj2ocyy5fhs2mu", "state": "StorageDealFailing", "message": "error activating deal: handling applied event: deal wasn't active: deal=9090, parentState=bafy2bzacediy6kmibh3lrjsyebst6ult2zxw5ksgsbkw7ktrnwjwjqy7kdh5q, h=4249"}
Aug 26 09:27:33 ubuntu lotus-miner[647942]: 2020-08-26T09:27:33.877Z#011WARN#011providerstates#011providerstates/provider_states.go:442#011deal bafyreifbus5tnzt3p7u7skuk76u43rm2x6oypil5w3v6lj2ocyy5fhs2mu failed: error activating deal: handling applied event: deal wasn't active: deal=9090, parentState=bafy2bzacediy6kmibh3lrjsyebst6ult2zxw5ksgsbkw7ktrnwjwjqy7kdh5q, h=4249
Aug 26 09:27:33 ubuntu lotus-miner[647942]: 2020-08-26T09:27:33.893Z#011INFO#011markets#011loggers/loggers.go:19#011storage event#011{"name": "ProviderEventFailed", "proposal CID": "bafyreifbus5tnzt3p7u7skuk76u43rm2x6oypil5w3v6lj2ocyy5fhs2mu", "state": "StorageDealError", "message": "error activating deal: handling applied event: deal wasn't active: deal=9090, parentState=bafy2bzacediy6kmibh3lrjsyebst6ult2zxw5ksgsbkw7ktrnwjwjqy7kdh5q, h=4249"}
Aug 26 09:27:33 ubuntu lotus-miner[647942]: 2020-08-26T09:27:33.961Z#011ERROR#011events#011events/events_called.go:252#011chain trigger (@H 4249, triggered @ 4255) failed: deal wasn't active: deal=9090, parentState=bafy2bzacediy6kmibh3lrjsyebst6ult2zxw5ksgsbkw7ktrnwjwjqy7kdh5q, h=4249
Aug 26 09:27:40 ubuntu lotus-miner[647942]: 2020-08-26T09:27:40.446Z#011ERROR#011events#011events/events_called.go:252#011chain trigger (@H 4249, triggered @ 4255) failed: deal wasn't active: deal=9090, parentState=bafy2bzacediy6kmibh3lrjsyebst6ult2zxw5ksgsbkw7ktrnwjwjqy7kdh5q, h=4249
Aug 26 09:27:54 ubuntu lotus-miner[647942]: 2020-08-26T09:27:54.272Z#011ERROR#011events#011events/events_called.go:252#011chain trigger (@H 4249, triggered @ 4255) failed: deal wasn't active: deal=9090, parentState=bafy2bzacediy6kmibh3lrjsyebst6ult2zxw5ksgsbkw7ktrnwjwjqy7kdh5q, h=4249
Aug 26 09:28:03 ubuntu lotus-miner[647942]: 2020-08-26T09:28:03.521Z#011ERROR#011events#011events/events_called.go:252#011chain trigger (@H 4249, triggered @ 4255) failed: deal wasn't active: deal=9090, parentState=bafy2bzacediy6kmibh3lrjsyebst6ult2zxw5ksgsbkw7ktrnwjwjqy7kdh5q, h=4249
Aug 26 09:28:04 ubuntu lotus-miner[647942]: 2020-08-26T09:28:04.727Z#011ERROR#011events#011events/events_called.go:252#011chain trigger (@H 4249, triggered @ 4255) failed: deal wasn't active: deal=9090, parentState=bafy2bzacediy6kmibh3lrjsyebst6ult2zxw5ksgsbkw7ktrnwjwjqy7kdh5q, h=4249
Aug 26 09:28:06 ubuntu lotus-miner[647942]: 2020-08-26T09:28:06.437Z#011ERROR#011events#011events/events_called.go:252#011chain trigger (@H 4249, triggered @ 4255) failed: deal wasn't active: deal=9090, parentState=bafy2bzacediy6kmibh3lrjsyebst6ult2zxw5ksgsbkw7ktrnwjwjqy7kdh5q, h=4249
Aug 26 09:30:30 ubuntu lotus-miner[647942]: 2020-08-26T09:30:30.422Z#011INFO#011advmgr#011sector-storage/sched.go:418#011assignWorker on worker:198 sectorID:35431 deals:{[9090] false}
Aug 26 09:31:01 ubuntu lotus-miner[647942]: 2020-08-26T09:31:01.966Z#011INFO#011storageadapter#011storageadapter/provider.go:292#011Storage deal 9090 activated at epoch 4255
`

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**
Does the chain trigger (@H 4249, triggered @ 4255)  should call at epoch: 4255  ?  But the log show that it was call at 4249, And then trigger  the event: "ProviderEventDealActivationFailed",  Finally activated at 4255 height， Is this a bug？

**Screenshots**

**Version (run `lotus version`):**
Daemon:  0.5.4+git.ceef149.dirty+api0.12.0
Local: lotus version 0.5.4+git.ceef149.dirty

**Additional context**

**Comment by Reiers** [comment] 2022-04-18 17:15
`deal 9090 activated at epoch 4255`

The deal didnt make on time, it should have been activated before epoch 4249.
 its not a bug.

Closing lotus issue ticket.

**Closed by Reiers** 2022-04-18 17:15 UTC
