### ISSUE TITLE
Calibration: memory leak

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/lotus#2946] opened 2020-08-10 14:31 UTC
**Describe the bug**

Needs investigation ... there's a pretty severe memory leak. This is the EC2 node that I'm using for deal/retrieval testing on calibration net ... there's no miner, but I've made hundreds of deals with it. It ran out of memory 16GB last night - I couldn't log in, so I rebooted the box from the AWS console, then added 10GB of swap. This morning, I couldn't log in again. I left `htop` running, so this is the state before it became unresponsive. So there's definitely something going crazy and using up all the memory.

<img width="816" alt="Screen Shot 2020-08-10 at 7 24 24 AM" src="https://user-images.githubusercontent.com/20886/89793451-bbff0700-dada-11ea-9266-95aaa2a0f568.png">

**Version (run `lotus version`):**

```
$ lotus version
Daemon:  0.4.3+git.2340742e.dirty+api0.9.0
Local: lotus version 0.4.3+git.2340742e.dirty
```

**Comment by jimpick** [comment] 2020-08-10 14:35
Possibly it might be retrieval related ... I had stored a small version of wikipedia (3GiB spread across 13 files) with 10 replicas each, and I was testing retrieval against every active deal that was stored... that's up to 30GiB of raw data potentially.

**Comment by jimpick** [comment] 2020-08-10 18:08
In a few hours, I'll re-try the retrievals and I'll watch it to see if it's related. I'm not doing retrievals currently and memory usage seems steady.

**Comment by jimpick** [comment] 2020-08-11 03:34
I did set up a test run and the memory started to increase, but then my retrievals stopped working and the memory plateaued. Here's the files:

```
$ ls -al
total 1549292
drwxrwxr-x 3 ubuntu ubuntu      4096 Aug 11 03:05 .
drwxrwxr-x 4 ubuntu ubuntu     12288 Aug 10 20:59 ..
drwxrwxr-x 2 ubuntu ubuntu      4096 Aug 10 15:23 2020-08-10-a
-rw-rw-r-- 1 ubuntu ubuntu    857629 Aug 11 03:14 profile.log
-rw-rw-r-- 1 ubuntu ubuntu 264241152 Aug 10 21:10 wiki.zip.aa-t01314-15465-1597093607.bin
-rw-rw-r-- 1 ubuntu ubuntu       140 Aug 10 21:10 wiki.zip.aa-t01314-15465-1597093607.log
-rw-rw-r-- 1 ubuntu ubuntu 264241152 Aug 10 21:06 wiki.zip.aa-t01701-13078-1597093293.bin
-rw-rw-r-- 1 ubuntu ubuntu       140 Aug 10 21:06 wiki.zip.aa-t01701-13078-1597093293.log
-rw-rw-r-- 1 ubuntu ubuntu       745 Aug 10 21:10 wiki.zip.aa-t02265-13343-1597093836.log
-rw-rw-r-- 1 ubuntu ubuntu 264241152 Aug 10 21:15 wiki.zip.ab-t01314-15498-1597093851.bin
-rw-rw-r-- 1 ubuntu ubuntu       140 Aug 10 21:15 wiki.zip.ab-t01314-15498-1597093851.log
-rw-rw-r-- 1 ubuntu ubuntu 264241152 Aug 10 21:19 wiki.zip.ab-t01937-12269-1597094106.bin
-rw-rw-r-- 1 ubuntu ubuntu       140 Aug 10 21:19 wiki.zip.ab-t01937-12269-1597094106.log
-rw-rw-r-- 1 ubuntu ubuntu       355 Aug 10 21:19 wiki.zip.ab-t01998-13209-1597094358.log
-rw-rw-r-- 1 ubuntu ubuntu 264241152 Aug 10 21:23 wiki.zip.ab-t02262-13218-1597094363.bin
-rw-rw-r-- 1 ubuntu ubuntu       140 Aug 10 21:23 wiki.zip.ab-t02262-13218-1597094363.log
-rw-rw-r-- 1 ubuntu ubuntu       219 Aug 10 21:33 wiki.zip.ac-t01371-13331-1597094621.log
-rw-rw-r-- 1 ubuntu ubuntu 264241152 Aug 10 21:38 wiki.zip.ac-t01857-13077-1597095231.bin
-rw-rw-r-- 1 ubuntu ubuntu       140 Aug 10 21:38 wiki.zip.ac-t01857-13077-1597095231.log
-rw-rw-r-- 1 ubuntu ubuntu       219 Aug 10 21:48 wiki.zip.ac-t01937-15461-1597095488.log
-rw-rw-r-- 1 ubuntu ubuntu       355 Aug 10 21:33 wiki.zip.ac-t01998-12968-1597095226.log
-rw-rw-r-- 1 ubuntu ubuntu       162 Aug 10 22:30 wiki.zip.ad-t01701-15404-1597097362.log
-rw-rw-r-- 1 ubuntu ubuntu       162 Aug 10 22:51 wiki.zip.ad-t01857-15410-1597098627.log
-rw-rw-r-- 1 ubuntu ubuntu      1195 Aug 10 23:13 wiki.zip.ad-t01998-13220-1597101157.log
-rw-rw-r-- 1 ubuntu ubuntu       162 Aug 10 23:12 wiki.zip.ad-t02261-15481-1597099892.log
-rw-rw-r-- 1 ubuntu ubuntu       162 Aug 10 22:09 wiki.zip.ad-t02275-13350-1597096097.log
-rw-rw-r-- 1 ubuntu ubuntu       162 Aug 10 23:34 wiki.zip.ae-t01701-13348-1597101195.log
-rw-rw-r-- 1 ubuntu ubuntu       162 Aug 11 00:37 wiki.zip.ae-t01857-13230-1597104990.log
-rw-rw-r-- 1 ubuntu ubuntu       162 Aug 10 23:55 wiki.zip.ae-t01937-13079-1597102460.log
-rw-rw-r-- 1 ubuntu ubuntu       162 Aug 11 00:16 wiki.zip.ae-t02275-13211-1597103725.log
-rw-rw-r-- 1 ubuntu ubuntu       162 Aug 11 02:01 wiki.zip.af-t01701-13222-1597110052.log
-rw-rw-r-- 1 ubuntu ubuntu       162 Aug 11 01:40 wiki.zip.af-t01857-13345-1597108787.log
-rw-rw-r-- 1 ubuntu ubuntu       162 Aug 11 01:19 wiki.zip.af-t01937-13325-1597107522.log
-rw-rw-r-- 1 ubuntu ubuntu       747 Aug 11 02:02 wiki.zip.af-t01998-13076-1597111317.log
-rw-rw-r-- 1 ubuntu ubuntu       162 Aug 11 00:58 wiki.zip.af-t02275-15868-1597106257.log
-rw-rw-r-- 1 ubuntu ubuntu       162 Aug 11 03:05 wiki.zip.ag-t01638-12268-1597113862.log
-rw-rw-r-- 1 ubuntu ubuntu       162 Aug 11 02:44 wiki.zip.ag-t01701-15493-1597112597.log
-rw-rw-r-- 1 ubuntu ubuntu       162 Aug 11 02:23 wiki.zip.ag-t01857-13333-1597111332.log
-rw-rw-r-- 1 ubuntu ubuntu         0 Aug 11 03:05 wiki.zip.ah-t02262-13322-1597115142.log
-rw-rw-r-- 1 ubuntu ubuntu       747 Aug 11 03:05 wiki.zip.ah-t02265-13214-1597115132.log
```

I also had a script that dumped the process output from `ps auwx` ... when it started, at 21:06:15 UTC, it was:

```
ubuntu   14947  101 59.1 25964508 9554204 pts/1 SLl+ 16:50 259:03 ./lotus daemon
```

... roughly 26GB of virtual mem, 9.5 GB RSS.

By 21:48:16 UTC, it had downloaded 1.5GB of retrievals (6 successful 252MiB files).

```
ubuntu   14947 96.3 75.3 29073864 12166892 pts/1 SLl+ 16:50 286:33 ./lotus daemon
```

... the VSZ is now roughly 29GB, RSS is 12GB.

So it grew quite a bit... more than the amount retrieved, so possibly the downloaded data is bound in memory.

When I ran the retrieval script last night, it downloaded much more data, and the system ran out of memory. I was expecting more retrievals to succeed, but they all seemed to start failing at a certain point... that might be due to my client daemon having problems or perhaps network-wide gas issues.

I'll try restarting my daemon and downloading again to get some more data.

Here is the [raw data](https://github.com/jimpick/filecoin-wiki-test/tree/master/wiki-large-blocks/retrievals/2020-08-10-b) from the test run.

**Comment by Reiers** [comment] 2021-12-12 23:34
**The issue is outdated and solved in newer versions of Lotus.** 

Closing ticket.

**Closed by Reiers** 2021-12-12 23:34 UTC
