### ISSUE TITLE
Cannot faucet FIL coin from https://faucet.calibration.fildev.network/ 

### ISSUE THREAD

**Issue by bruce1ee** [filecoin-project/lotus#5302] opened 2021-01-07 07:07 UTC
**Describe the bug**
Cannot faucet FIL coin from https://faucet.calibration.fildev.network/ 

**To Reproduce**
1. Go 'https://faucet.calibration.fildev.network/'
2. Input 't1ud2nqntqdhgp4smamkpekh62srtz2f5en6p4cny' and click the button [Send Funds]
3. Error msg: GasEstimateMessageGas error: estimating gas used: message execution failed: exit SysErrInsufficientFunds(6), reason: failed to transfer funds (RetCode=6): transfer failed when deducting funds (5 FIL): not enough funds (RetCode=6)

**Expected behavior**
get test FIL coin

**Screenshots**

**Version (run `lotus version`):**

**Additional context**

**Comment by PatrickDeuse** [comment] 2021-01-08 01:24
the faucet is kind of down these days.

the calibration net got a bit in trouble at the end of the year and will, most likely, be reset in the coming weeks to fix the flaws it had (not enough miners leading to an unbalanced baseline etc.)

please join the filecoin slack workspace and join the #fil-net-calibration-discuss and #fil-net-calibration-announcements chans to get updates and find someone nice enough to give you some testnet FILs

**Comment by bruce1ee** [comment] 2021-01-13 07:30
Hi @PatrickDeuse  cannot join this channel. Is it public channel. Or can you send me a invitation link to join it?

**Comment by bruce1ee** [comment] 2021-01-13 10:43
my email: bruce.li#poloniex.com

**Comment by PatrickDeuse** [comment] 2021-01-13 14:37
invited you, someone with admin priv's need to approve - no idea why the links do not work

**Comment by mehmetozcan-zz** [comment] 2021-06-16 10:58
Hello, 

Faucet is not working. Could you please urgently help? We are in the middle of integration test but not able to send funds from faucet.

**Comment by f8-ptrk** [comment] 2021-06-16 23:48
the faucet is working @mehmetozcan-zz

**Comment by inevity** [comment] 2021-07-03 06:08
@f8-ptrk can you invite me #fil-net-calibration-discuss ?

**Comment by f8-ptrk** [comment] 2021-07-04 01:06
@inevity you can joining the slack at https://filecoin.io/slack and join the chan yourself

**Comment by lhpustc** [comment] 2022-01-25 04:22
Describe the bug
Cannot faucet FIL coin from https://faucet.calibration.fildev.network/

To Reproduce
Steps to reproduce the behavior:
1. Go 'https://faucet.calibration.fildev.network/'
    Input 't3szqfydn7j7u3ajwj4ys6eewr4plqb7vup2grxvvws3kbiqwkwvqdp42n4dxmusfggwq7swant7uhdsqxbiaq' in the 'destination address‘ and click the button [Send Funds]
2. Redirected to page 'https://faucet.calibration.fildev.network/send' which shows “baf.." (message id?)
3. Check my wallet after a few hours, and it shows 0 FIL.

Expected behavior
get test FIL coin

Screenshots
![Screen Shot 2022-01-24 at 8 03 21 PM](https://user-images.githubusercontent.com/12083458/150910438-0ca86b58-6227-4a31-8834-0881a8f9fc93.png)
![Screen Shot 2022-01-24 at 8 05 38 PM](https://user-images.githubusercontent.com/12083458/150910455-4378b9f1-6e3d-432e-9b79-c244866981f3.png)
![Screen Shot 2022-01-24 at 8 06 00 PM](https://user-images.githubusercontent.com/12083458/150910466-761d0745-9a09-4f88-85a9-429fdb595734.png)


Version (run lotus version):

**Comment by rjan90** [comment] 2022-04-19 11:20
Hey!

The faucet for the Calibration-network is currently working so closing this ticket now.

@lhpustc the reason why you did not see any FIL in your wallet was most likely because you where still syncing the chain when looking at your wallet.

If there is some new issues with the faucet, please open a new ticket.

Thanks again 😄

**Closed by rjan90** 2022-04-19 11:20 UTC
