### ISSUE TITLE
[Feature Request] Ability to set own path for fstmp and /staging-folder

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/lotus#5591] opened 2021-02-15 08:28 UTC
Many smaller/medium-scaled miners are not set-up to handle larger amount of deals when deals go through the LOTUS_MINER_PATH as their disk size might not be large enough. High flow of files and IO on one of the most critical disks is not ideal as well.

It would be really great to have the possibility to set your own variable to where both the fstmp-files and the /staging-folder is located, so that you can locate it on a different drive than _.lotusminer_.

**Comment by PatrickDeuse** [comment] 2021-02-15 11:01
half duplicate of https://github.com/filecoin-project/lotus/issues/5291

**Comment by s0nik42** [comment] 2021-04-21 06:21
Definitely, we should be able to isolate the fstmp files to a dedicated location/mountpoint to avoid datastore corruption due to Filesystem full.

**Closed** 2021-08-17 07:27 UTC
Labels: x/ignite
