### ISSUE TITLE
[BUG] SubmittedPoST reject by node when out of sync

### ISSUE THREAD

**Issue by s0nik42** [filecoin-project/lotus#6727] opened 2021-07-10 15:44 UTC
**Describe the bug**
 The miner send the SubmitPost message on time but was rejected by the node that was temporary out of sync for (10min)

**History :**
1/ Node onsync
2/ challenge received for Deadline 2 (Deadline2)
```
2021-07-08T23:13:30.493+0200	INFO	storageminer	storage/wdpost_run.go:589	running window post	{"chain-random": "rxxoYuRKj7Z84cNHeL/7vZnzd+wusYXrJutXewQxhUM=", "deadline": {"CurrentEpoch":915747,"PeriodStart":915637,"Index":2,"Open":915757,"Close":915817,"Challenge":915737,"FaultCutoff":915687,"WPoStPeriodDeadlines":48,"WPoStProvingPeriod":2880,"WPoStChallengeWindow":60,"WPoStChallengeLookback":20,"FaultDeclarationCutoff":70}, "height": "915747", "skipped": 0}
```

3/ Node loose sync
```
2021-07-08T23:16:34.416+0200    ERROR   chainstore      store/store.go:376      reorg channel is heavily backlogged, waiting a bit before trying to take process new tipsets
2021-07-08T23:16:34.494+0200    ERROR   chainstore      store/store.go:376      reorg channel is heavily backlogged, waiting a bit before trying to take process new tipsets```

4/ Miner compute and send  SubmitPoST
5/ Node rejects the message because still before Deadline2 start time so still expecting deadline 1

```2021-07-08T23:26:39.261+0200    ERROR   storageminer    storage/wdpost_run.go:826       estimating gas  {"error": "estimating gas used: message execution failed: exit 16, reason: invalid deadline 2 at epoch 915751, expected 1 (RetCode=16)"}
2021-07-08T23:26:39.280+0200    ERROR   storageminer    storage/wdpost_run.go:185       submit window post failed: pushing message to mpool:
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).submitPost
        /usr/src/lotus/storage/wdpost_run.go:794
  - GasEstimateMessageGas error: estimating gas used: message execution failed: exit 16, reason: invalid deadline 2 at epoch 915751, expected 1 (RetCode=16)
  ```

6/ Node back onsync
7/ The miner never tried to resend the message even if it has still 20min to do it 

**Version (run `lotus version`):**
```
Daemon:  1.10.0+mainnet+git.764fa9dae+api1.3.0
Local: lotus version 1.10.0+mainnet+git.764fa9dae
```
**Expected behavior**
2 options : 
1.  The miner try to resend the SubmitPost before deadline ends
2. The node accepts the message knowing it is out of sync

**Comment by s0nik42** [comment] 2021-07-10 15:45
Slack thread : https://filecoinproject.slack.com/archives/C022ZR4JA1M/p1625815990471100

**Comment by Reiers** [comment] 2022-01-14 00:01
Hi @s0nik42 

Thanks for this feature request. I will add labels and will assign it to the right team for analysis.

**Comment by Reiers** [comment] 2022-01-18 00:59
**Hi @s0nik42** 

Thanks for the report. 

Closing ticket, because this happen because of a out of sync node, and its not a bug. 
My suggestion is that, you restart the miner _(when you are back in sync)_ - if you are in the same deadline it will try to send the message right away after it started up again.  

If you are still experiencing problems, open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

**Closed by Reiers** 2022-01-18 00:59 UTC
Labels: kind/feature, kind/bug, area/chain, area/mining
