### ISSUE TITLE
window post and winning post

### ISSUE THREAD

**Issue by leviok** [filecoin-project/lotus#2799] opened 2020-08-04 02:05 UTC
**Describe the bug**
first of all, apology for my poor english.

as we know, the miners have to post window post to keep their power up, or they will be slashed. so, make this behavior stable is more important.

a miner who can make winning post and produce block on time have already proved their sectors are online. but missing window post is a common phenomenon on recent several test net. I think it's harmful for the net. some of the reasons is following. 

1. miner is busy. several heavy jobs on one machine. such as winning post, creating bolck, doing window post, handleing deals and visiting on-sealing storage which is very busy. I think separate these jobs on diffrent computer make more sense. these can do from way of different node type or workers.

2. weird select message logic make throughput of message on a low level. it can't reach the limit which designed. and other reson make mpool traffic blocked, too. the mpool traffic must be smooth for window post. there was only about half an hour for making post and commtting.

**To Reproduce**
no need

**Expected behavior**
slashing power isn't so frequently.

**Screenshots**
no need

**Version (run `lotus version`):**
ntwk-calibration

**Additional context**

who can explain me why the winning post is necessary now? if there was no winning post, the chain can be smooth much more.

**Comment by arajasek** [comment] 2020-08-04 05:48
I don't think winning post is the cause of the problems you're describing. Recent networks have seen various issues with messages going into blocks, which leads to missed PoSts, and slashing as you said. This should be fixed in the latest network.

**Closed by arajasek** 2020-08-04 05:48 UTC
