### ISSUE TITLE
[Sealing Issue]  not enough threads

### ISSUE THREAD

**Issue by bzhubs** [filecoin-project/lotus#6778] opened 2021-07-17 22:56 UTC
miner log:

2021-07-18T03:42:02.586+0800    DEBUG   advmgr  sector-storage/sched_resources.go:64    sched: not scheduling on worker 23919ec5-8e3d-4f63-940e-54f72b81e349 for schedAssign; not enough threads, need 117, 117 in use, target 128
2021-07-18T03:42:02.586+0800    DEBUG   advmgr  sector-storage/sched.go:465     SCHED try assign sqi:6 sector 8 to window 5
2021-07-18T03:42:02.586+0800    DEBUG   advmgr  sector-storage/sched_resources.go:64    sched: not scheduling on worker 23919ec5-8e3d-4f63-940e-54f72b81e349 for schedAssign; not enough threads, need 117, 117 in use, target 128
2021-07-18T03:42:02.586+0800    DEBUG   advmgr  sector-storage/sched.go:465     SCHED try assign sqi:7 sector 9 to window 4
2021-07-18T03:42:02.586+0800    DEBUG   advmgr  sector-storage/sched_resources.go:64    sched: not scheduling on worker 23919ec5-8e3d-4f63-940e-54f72b81e349 for schedAssign; not enough threads, need 117, 117 in use, target 128
2021-07-18T03:42:02.586+0800    DEBUG   advmgr  sector-storage/sched.go:465     SCHED try assign sqi:7 sector 9 to window 5
2021-07-18T03:42:02.586+0800    DEBUG   advmgr  sector-storage/sched_resources.go:64    sched: not scheduling on worker 23919ec5-8e3d-4f63-940e-54f72b81e349 for schedAssign; not enough threads, need 117, 117 in use, target 128
2021-07-18T03:42:02.586+0800    DEBUG   advmgr  sector-storage/sched.go:465     SCHED try assign sqi:8 sector 10 to window 4
2021-07-18T03:42:02.586+0800    DEBUG   advmgr  sector-storage/sched_resources.go:64    sched: not scheduling on worker 23919ec5-8e3d-4f63-940e-54f72b81e349 for schedAssign; not enough threads, need 117, 117 in use, target 128
2021-07-18T03:42:02.586+0800    DEBUG   advmgr  sector-storage/sched.go:465     SCHED try assign sqi:8 sector 10 to window 5
2021-07-18T03:42:02.586+0800    DEBUG   advmgr  sector-storage/sched_resources.go:64    sched: not scheduling on worker 23919ec5-8e3d-4f63-940e-54f72b81e349 for schedAssign; not enough threads, need 117, 117 in use, target 128
2021-07-18T03:42:02.586+0800    DEBUG   advmgr  sector-storage/sched_resources.go:64    sched: not scheduling on worker 23919ec5-8e3d-4f63-940e-54f72b81e349 for startPreparing; not enough threads, need 117, 117 in use, target 128
2021-07-18T03:42:02.586+0800    DEBUG   advmgr  sector-storage/sched_resources.go:64    sched: not scheduling on worker 23919ec5-8e3d-4f63-940e-54f72b81e349 for compactWindows; not enough threads, need 117, 117 in use, target 128
2021-07-18T03:42:02.586+0800    DEBUG   advmgr  sector-storage/sched_resources.go:64    sched: not scheduling on worker 23919ec5-8e3d-4f63-940e-54f72b81e349 for startPreparing; not enough threads, need 117, 117 in use, target 128

root@miner2:/data/miner# lotus-miner sealing workers
Worker 23919ec5-8e3d-4f63-940e-54f72b81e349, host worker1
        CPU:  [                                                                ] 0/128 core(s) in use
        RAM:  [|                                                               ] 1% 39.2 GiB/1.957 TiB
        VMEM: [|                                                               ] 1% 39.2 GiB/1.965 TiB
        GPU: GeForce RTX 3080, not used
        GPU: GeForce RTX 3080, not used
Worker 24954b0c-8b26-4da0-9aa6-bb21ff0ec180, host miner2
        CPU:  [                                                                ] 0/64 core(s) in use
        RAM:  [                                                                ] 0% 6.394 GiB/1007 GiB
        VMEM: [                                                                ] 0% 6.394 GiB/1015 GiB
        GPU: GeForce RTX 3080, not used
        GPU: GeForce RTX 3080, not used
Worker 95dadf94-d93a-4b7e-9be5-f4f4d79aea51, host worker2
        CPU:  [                                                                ] 0/128 core(s) in use
        RAM:  [                                                                ] 0% 10.89 GiB/1.957 TiB
        VMEM: [                                                                ] 0% 10.89 GiB/2.215 TiB

root@miner2:/data/miner# lotus-miner sealing jobs
ID        Sector  Worker    Hostname  Task  State        Time
c5ee3378  1       23919ec5  worker1   GET   running      4h44m3.6s
00000000  2       23919ec5  worker1   PC2   assigned(0)  4h38m40.3s
00000000  3       23919ec5  worker1   PC2   assigned(1)  4h39m7.9s

Completed the pc1 stage, migrating from host B to host A, very slow,202G copied in 6 hours， and the miner will report an error
But my environment is 10G optical fiber network card and 10G optical port switch

miner 
AMD EPYC 7302 *2
Memory 1TB 
Disk  nvme 6.78T *1
Nvidia 3080 *2

worker 1 (host A)
AMD EPYC 7542 *2
Memory 2TB
Disk nvme 4T *8  soft RAID0
Nvidia 3082 *2
Task: PC2 C1  C2

worker 2(host B)
AMD EPYC 7542 *2
Memory 2TB
Disk nvme 4T *8 soft RAID0
Task: AP PC1

lotus version
Daemon:  1.10.1+calibnet+git.d920b47e7+api1.3.0

**Comment by Reiers** [comment] 2022-04-25 13:34
Hi @bzhubs 

Thanks for the report. Im unable to reproduce the issue here.
Closing issue ticket - if you encounter the issue again in [current release](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1), please open a new ticket and provide new logs and repro steps. 
Thanks !

**Closed by Reiers** 2022-04-25 13:34 UTC
Labels: area/sealing
