### ISSUE TITLE
Mining with confiscated sectors

### ISSUE THREAD

**Issue by skm-cike** [filecoin-project/lotus#4454] opened 2020-10-17 09:29 UTC
For sectors that have been lost for more than 14 days and whose mortgage has been fully deducted, what if miner is still mining in those sectors?

**Comment by jennijuju** [comment] 2020-10-20 05:58
what do you mean by miner continue to miner those sectors? Do you mean by proving, if so, nope, terminated sectors are no longer being verified.

**Comment by skm-cike** [comment] 2020-10-20 07:00
Hi:
   How to terminated sectors?

   This is my sector 10998

    The mining log is as follows: 
====================================================================================================
2020-10-20T01:20:40.746+0800 INFO storageminer storage/miner.go:246 Computing WinningPoSt ;[{SealProof:3 SectorNumber:10998 SealedCID:bagboea4b5abcbpw6dedclihci4dcqw7qa3utle36nu7yyk3dfrc2goxeufxos7bn}]; [88 214 247 163 162 214 177 25 220 27 152 76 83 64 93 255 125 236 236 35 14 66 207 152 125 177 95 240 124 55 10 82]
2020-10-20T01:20:40.746 INFO filcrypto::proofs::api > generate_winning_post: start
2020-10-20T01:20:40.746 INFO filcrypto::proofs::api > generate_winning_post: finish
2020-10-20T01:20:40.746+0800 ERROR miner miner/miner.go:228 mining block failed: failed to compute winning post proof:
    github.com/filecoin-project/lotus/miner.(*Miner).mineOne
        /home/fil/app/lotus-v0.10.0/miner/miner.go:421
  - could not read from path="p_aux"
    Caused by:
====================================================================================================
    

    The state of the sector is:
 ----------------------------------------------------------------------------------------------
 SectorID: 10998
 Status: FaultReported
 CIDcommD: baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq
 CIDcommR: bagboea4b5abcbpw6dedclihci4dcqw7qa3utle36nu7yyk3dfrc2goxeufxos7bn
 Ticket: 094815861050c7f066a98529a86dfc1afeb6de4c6f43f353132669dee78337b2
 TicketH: 31663
 Seed: 35890a1a7a8df65a02c1553dbcd4c42c0b3fa56e271da1c8d24f596063321793
........
 8. 2020-09-05 21:23:49 +0800 CST: [event;sealing.SectorCommitSubmitted] {"User":{"Message":{"/":"bafy2bzacedv5rqfges2yjdr3dwonlt2gat6ydj444htzgcjordmh6jvxn3pfa"}}}
 9. 2020-09-05 21:28:02 +0800 CST: [event;sealing.SectorProving] {"User":{}}
10. 2020-09-05 21:29:48 +0800 CST: [event;sealing.SectorFinalized] {"User":{}}
........
 26. 2020-10-04 14:58:26 +0800 CST: [event;sealing.SectorRestart] {"User":{}}
 27. 2020-10-06 01:19:16 +0800 CST: [event;sealing.SectorForceState] {"User":{"State":"FaultReported"}}
 
 ----------------------------------------------------------------------------------------------
    
     Find sector 10998:
   ----------------------------------------------------------------------------------------------
  fil@109-3:~/app/lotus$ ./lotus-miner storage find 10998
  fil@109-3:~/app/lotus$ ./lotus-miner storage find 10998
  fil@109-3:~/app/lotus$ ./lotus-miner storage find 10998
  fil@109-3:~/app/lotus$
   ----------------------------------------------------------------------------------------------
   
     How to terminate it?
    ----------------------------------------------------------------------------------------------
    fil@109-3:~/app/lotus$ ./lotus-miner sectors remove --really-do-it 10998
    ERROR: normal shutdown of state machine

    fil@109-3:~/app/lotus$ ./lotus-miner sectors update-state --really-do-it 10998 Removing
    ERROR: normal shutdown of state machine

    fil@109-3:~/app/lotus$ ./lotus-miner sectors update-state --really-do-it 10998 FaultedFinal
    ERROR: normal shutdown of state machine

    fil@109-3:~/app/lotus$ ./lotus-miner sectors mark-for-upgrade 10998
    ERROR: can't mark sectors not in the 'Proving' state for upgrade
    ----------------------------------------------------------------------------------------------

    The partition where this sector is located has been lost for more than a month. The amount of money to be deducted and the pledge have been deducted. But mining still uses these missing sectors. The rest of my effective computing power is completely unable to mine.
    


lhk523@163.com
 
From: Jennifer
Date: 2020-10-20 13:59
To: filecoin-project/lotus
CC: skm-cike; Author
Subject: Re: [filecoin-project/lotus] Mining with confiscated sectors (#4454)
what do you mean by miner continue to miner those sectors? Do you mean by proving, if so, nope, terminated sectors are no longer being verified.

**Comment by magik6k** [comment] 2020-11-05 17:18
Duplicate of https://github.com/filecoin-project/lotus/issues/4027

**Closed by magik6k** 2020-11-05 17:18 UTC
