### ISSUE TITLE
Can't submit PoSt 

### ISSUE THREAD

**Issue by Dengminer** [filecoin-project/lotus#914] opened 2019-12-14 09:15 UTC
The following error report caused me to fail to submit post normally. Will it recover automatically ?

2019-12-14T03:47:27.001+0800    ERROR   storageminer    storage/fpost_run.go:39 runPost failed: running post failed:
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
        /usr/local/lotus/storage/fpost_run.go:79
  - could not load private replica (id = 71) from cache (path = "/data/.lotusstorage/cache/s-t01243-71"): No such file or directory (os error 2)
    
    Stack backtrace:
       0: <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::try_fold
       1: filecoin::proofs::helpers::to_private_replica_info_map
       2: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
       3: std::panicking::try::do_call
       4: __rust_maybe_catch_panic
                 at src/libpanic_unwind/lib.rs:78
       5: ffi_toolkit::catch_panic_response
       6: generate_candidates
       7: _cgo_f815959cf24d_Cfunc_generate_candidates
                 at /tmp/go-build/cgo-gcc-prolog:231
       8: runtime.asmcgocall
                 at /usr/lib/go-1.13/src/runtime/asm_amd64.s:655
    github.com/filecoin-project/filecoin-ffi.GenerateCandidates
        /usr/local/lotus/extern/filecoin-ffi/proofs.go:640
    github.com/filecoin-project/lotus/lib/sectorbuilder.(*SectorBuilder).GenerateFallbackPoSt
        /usr/local/lotus/lib/sectorbuilder/sectorbuilder.go:673
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).runPost
        /usr/local/lotus/storage/fpost_run.go:77
    github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
        /usr/local/lotus/storage/fpost_run.go:37
    runtime.goexit
        /usr/lib/go-1.13/src/runtime/asm_amd64.s:1357
github.com/filecoin-project/lotus/storage.(*fpostScheduler).doPost.func1
    /usr/local/lotus/storage/fpost_run.go:39

**Comment by magik6k** [comment] 2019-12-14 11:16
Hmm, we should detect missing sectors and report faults automatically

**Comment by magik6k** [comment] 2019-12-14 11:35
Duplicate of https://github.com/filecoin-project/lotus/issues/897

**Closed** 2020-01-20 15:47 UTC
