### ISSUE TITLE
lotus-seal-worker restart failure

### ISSUE THREAD

**Issue by cwhiggins** [filecoin-project/lotus#3394] opened 2020-08-29 13:52 UTC
Had a lotus worker only for PC2 & Commit.  was stuck on a get task for over an hour.  shut it down, restarted
sat waiting for tasks for an hour then checked worker see output below

chris@chris-Aorus:~$ lotus-miner sealing workers
Worker 0, host chris-Aorus
	CPU:  [                                                                ] 0 core(s) in use
	RAM:  [|                                                               ] 2% 7.344 GiB/251.7 GiB
	VMEM: [                                                                ] 1% 7.344 GiB/507.7 GiB
	GPU: GeForce RTX 2080 Ti, not used
	GPU: GeForce GTX 1070, not used
Worker 1, host chris-Aorus
	CPU:  [||                                                              ] 2 core(s) in use
	RAM:  [|||||||||||||||||||||||||||||                                   ] 47% 119.4 GiB/251.7 GiB
	VMEM: [||||||||||||||||                                                ] 26% 135.4 GiB/507.7 GiB
Worker 2, host chris-Aorus
	CPU:  [||||                                                            ] 3 core(s) in use
	RAM:  [|||||||||||||||||||||||||||||||||||||||||||                     ] 69% 175.4 GiB/251.7 GiB
	VMEM: [||||||||||||||||||||||||                                        ] 39% 199.4 GiB/507.7 GiB
Worker 5, host chris-Aorus
	CPU:  [                                                                ] 0 core(s) in use
panic: strings: negative Repeat count

goroutine 1 [running]:
strings.Repeat(0x29deaa7, 0x1, 0xfffffffffffffff8, 0x0, 0x0)
	/usr/local/go/src/strings/strings.go:533 +0x5a9
main.glob..func34(0xc0000f4f00, 0x0, 0x0)
	/home/chris/lotus/cmd/lotus-storage-miner/sealing.go:89 +0x903
github.com/urfave/cli/v2.(*Command).Run(0x5097d40, 0xc0000f4d80, 0x0, 0x0)
	/home/chris/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4e0
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc000682600, 0xc0000f4a40, 0x0, 0x0)
	/home/chris/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:427 +0xa68
github.com/urfave/cli/v2.(*Command).startApp(0x50980a0, 0xc0000f4a40, 0x7ffeacd5d30c, 0x7)
	/home/chris/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:279 +0x68c
github.com/urfave/cli/v2.(*Command).Run(0x50980a0, 0xc0000f4a40, 0x0, 0x0)
	/home/chris/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:94 +0xa12
github.com/urfave/cli/v2.(*App).RunContext(0xc000682480, 0x2dfd3c0, 0xc000130030, 0xc00011a150, 0x3, 0x3, 0x0, 0x0)
	/home/chris/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x814
github.com/urfave/cli/v2.(*App).Run(...)
	/home/chris/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
github.com/filecoin-project/lotus/cli.RunApp(0xc000682480)
	/home/chris/lotus/cli/helper.go:34 +0x7c
main.main()
	/home/chris/lotus/cmd/lotus-storage-miner/main.go:103 +0xa1b

seems like the miner needs to shut down as well as the worker

Daemon:  0.5.6+git.606a58bc+api0.13.0
Local: lotus version 0.5.6+git.606a58bc

**Comment by magik6k** [comment] 2020-10-28 19:45
Duplicate of https://github.com/filecoin-project/lotus/issues/3931

**Closed by magik6k** 2020-10-28 19:45 UTC
