### ISSUE TITLE
Add ProofReplicaUpgrade2

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#9250] opened 2022-09-02 06:15 UTC
introduced by https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0041.md

lotus should start to call PreCommitSectorBatch2 instead of PreCommitSectorBatch1. 

Local sector precommit info might need to be migrated to the new param.

**Comment by arajasek** [comment] 2022-09-10 16:52
I don't think this should be scoped as part of nv17. Doing so means we would have to switch on network version to start using the new `PreCommitSectorBatch2` method only after the network upgrade.

I would propose delaying this issue until _after_ the nv17 upgrade, at which point we simply always call `PreCommitSectorBatch2` (and `ProveReplicaUpdates2`).

@Kubuxu please chime in with thoughts.

**Comment by jennijuju** [comment] 2022-09-10 21:43
If we don’t do it in this release, then it will at least take 3 upgrades for us to fully drop batch 1 function. Doing it now we can drop it in next upgrade.

**Comment by Kubuxu** [comment] 2022-09-16 15:19
It would be preferred if it could be removed in the next upgrade (but probably won't happen, FEVM) or one after that.
This also affects ProofReplicaUpgrade2.

**Comment by arajasek** [comment] 2022-09-16 15:37
> Agree we don’t HAVE to. If we don’t do it in this release, then it will at least take 3 upgrades for us to fully drop batch 1 function in actir. Doing it now we can drop it in next upgrade.

Yeah, the problem is just that doing it now is strictly harder than doing it after (because after the upgrade we can just switch without nv guards).

**Comment by jennijuju** [comment] 2022-09-20 01:46
I am convinced this is not mandatory for t his upgrade (for now 😉 ), moving this to opportunistic for now.

**Comment by anorth** [comment] 2022-09-20 02:35
I concur you don't need to implement these before nv17, but disagree that this means it'll take 3 upgrades to drop the old ones.

The old methods will be dropped in nv18, if I have anything to say about it. Lotus will have implemented the new methods then, and your nv18 release will be mandatory.

**Comment by jennijuju** [comment] 2022-09-20 02:49
@anorth i think we will need 
-  one upgrade to introduce the new method - nv17
- lotus introduce the new method in a feature release, feature release is optional
- before nv18 upgrade
  - it is possible to have users send out PCSB message using nv17 lotus release 
  - these message will fail if we drop PCSB & PRU on v10 actor

1.  -  it's much safer/less error prune for lotus users  if we drop these methods in nv19, after we get everyone users nv18 lotus release, which sends PCSB&PRU2

**Comment by anorth** [comment] 2022-09-20 20:41
> it is possible to have users send out PCSB message using nv17 lotus release

It's extremely unlikely this is done within hours of the upgrade and sit around in the message pool for that long. There are not terrible effects if these message fail. It's not worth the complexity to handle these messages. You should not implement any special retry/recovery above whatever general methods exist for retrying a failed high-level operation. Just declare the upgrade mandatory X hours before the network upgrade.

**Comment by Kubuxu** [comment] 2022-09-21 15:41
Thanks @arajasek, the ability to do this staggered deployment is why I have decided to pursue this FIP. Because we have one upgrade buffer (nv18) it isn't critical for us to support the new methods in this lotus stable version.

**Comment by arajasek** [comment] 2022-10-05 15:14
Yeah, this FIP is great for allowing such changes to happen!

We don't have great data on the update % leading up to the network upgrade (we could get some in a month as we lead into v17). Anecdotally, it does appear that a majority of users upgrade in the 24 hours before the upgrade.

**Comment by arajasek** [comment] 2022-10-05 15:14
Descoping from v17 since it's a no-op for the upgrade.

**Comment by rjan90** [comment] 2023-08-19 11:06
The switch to using PreCommitSectorBatch2 has been merged here: https://github.com/filecoin-project/lotus/pull/11142.

**Comment by rjan90** [comment] 2024-04-14 16:08
Closing this issue as ProveReplicaUpdates2 is being removed in the coming network upgrade (nv22), and ProveReplicaUpdates3 (method 35) has been introduced and implemented: https://github.com/filecoin-project/lotus/pull/11831

**Closed by rjan90** 2024-04-14 16:08 UTC
Labels: effort/hours, FIP-0041, LM-tech-debt
