### ISSUE TITLE
Retry AddPiece if it fails

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#5687] opened 2021-02-26 01:40 UTC
Currently, if AddPiece failed the deal will fail, a retry or manual restart AddPiece mechanism is useful

**Comment by rjan90** [comment] 2021-02-26 07:25
Related issue #5326

**Comment by PatrickDeuse** [comment] 2021-02-26 15:06
not to mention that the same is true for every part of the sealing process

**Comment by William8Work** [comment] 2021-09-04 00:43
I have just ran into this.

A worker crashed during AddPiece when sealing a verified deal from offline deals. This error now is caused deal getting error and I have no way to recover it from storage provider point of view. I have to contact the client to ask for a new deal proposal.

The AddPieceFailed on top of a deal is making things much worst because we have to reach back out to client to re-propose a new deal. 

Could we bump up the priority on this issue?

**Comment by neondragon** [comment] 2021-09-04 01:19
About 20% of my deals result in AddPieceFailed. I haven't narrowed down the cause. It doesn't happen to CC sectors, it just seems to happen during transferring piece data to the AP worker over the network. It seems to happen less when the lotus-miner markets process is less busy, but it still happens, and causes the deal to move into an Error state when it should be trivial to retry AddPiece instead.

Example sector log

> SectorID:       466
> Status:         Removed
> CIDcommD:       <nil>
> CIDcommR:       <nil>
> Ticket:
> TicketH:        0
> Seed:
> SeedH:          0
> Precommit:      <nil>
> Commit:         <nil>
> Proof:
> Deals:          []
> Retries:        0
> --------
> Event Log:
> 0.      2021-09-03 18:25:00 +0000 UTC:  [event;sealing.SectorStart]     {"User":{"ID":466,"SectorType":9}}
> 1.      2021-09-03 18:25:00 +0000 UTC:  [event;sealing.SectorAddPiece]  {"User":{}}
> 2.      2021-09-03 18:43:28 +0000 UTC:  [event;sealing.SectorAddPiece]  {"User":{}}
> 3.      2021-09-03 18:43:28 +0000 UTC:  [event;sealing.SectorAddPieceFailed]    {"User":{}}
>         writing piece: storage call error 0: pr read error: read tcp 10.5.12.34:3456->185.37.2.3:57504: read: connection timed out
> 4.      2021-09-04 01:10:13 +0000 UTC:  [event;sealing.SectorRemove]    {"User":{}}
> 5.      2021-09-04 01:10:14 +0000 UTC:  [event;sealing.SectorRemoved]   {"User":{}}
>

**Comment by gh3990** [comment] 2021-09-29 20:27
Please add a way to also limit the retry limit to how many parallel add-piece processes run. To provide a process not to overload the worker or ddos it when a lot of add-piece retry processes kick in.

**Comment by TippyFlitsUK** [comment] 2022-12-25 23:36
Closing due to legacy markets EOL.

**Closed by TippyFlitsUK** 2022-12-25 23:36 UTC
Labels: P2, area/sealing, area/markets/provider
