### ISSUE TITLE
	WARN	vm	vm/vm.go:449	Send actor error	{"from": "t3wqd7457mjqyzel4d6inqdbmfrhsxxxtuvdeq4muobcwpkj5w2wocst6ltzqwkf7aqchssrvwydvbavofkl5q", "to": "t010257", "nonce": 1030, "method": "0", "height": "38976", "error": "not enough gas for method invocation (RetCode=7)

### ISSUE THREAD

**Issue by jack815943555** [filecoin-project/lotus#3607] opened 2020-09-07 10:50 UTC
2020-09-07T18:47:45.407+0800	WARN	vm	vm/vm.go:449	Send actor error	{"from": "t3wqd7457mjqyzel4d6inqdbmfrhsxxxtuvdeq4muobcwpkj5w2wocst6ltzqwkf7aqchssrvwydvbavofkl5q", "to": "t010257", "nonce": 1030, "method": "0", "height": "38976", "error": "not enough gas for method invocation (RetCode=7):\n    github.com/filecoin-project/lotus/chain/vm.(*VM).send.func2\n        /home/jack/go_workspace/v0510/lotus/chain/vm/vm.go:254\n  - not enough gas: used=474085, available=474085 (RetCode=7):\n    github.com/filecoin-project/lotus/chain/vm.(*Runtime).chargeGasInternal\n        /home/jack/go_workspace/v0510/lotus/chain/vm/runtime.go:544"}
2020-09-07T18:47:45.408+0800	WARN	vm	vm/vm.go:449	Send actor error	{"from": "t3wqd7457mjqyzel4d6inqdbmfrhsxxxtuvdeq4muobcwpkj5w2wocst6ltzqwkf7aqchssrvwydvbavofkl5q", "to": "t010257", "nonce": 1031, "method": "0", "height": "38976", "error": "not enough gas for method invocation (RetCode=7):\n    github.com/filecoin-project/lotus/chain/vm.(*VM).send.func2\n        /home/jack/go_workspace/v0510/lotus/chain/vm/vm.go:254\n  - not enough gas: used=474085, available=474085 (RetCode=7):\n    github.com/filecoin-project/lotus/chain/vm.(*Runtime).chargeGasInternal\n        /home/jack/go_workspace/v0510/lotus/chain/vm/runtime.go:544"}
2020-09-07T18:47:45.408+0800	WARN	vm	vm/runtime.go:302	Abortf: failed to allocate sector id 653: sector number 653 has already been allocated
2020-09-07T18:47:45.409+0800	WARN	vm	vm/runtime.go:115	VM.Call failure: failed to allocate sector id 653: sector number 653 has already been allocated (RetCode=16):

**Comment by jennijuju** [comment] 2020-10-02 17:52
Can you provide more info like your miner id, lotus version, what happened and how can we reproduce this issue.

**Comment by 90hacker** [comment] 2020-11-02 12:13
I also encountered this problem。
lotus version  1.1.0

**Comment by Reiers** [comment] 2022-03-09 13:35
Hi @jack815943555 

Thanks for the report. The issue is outdated, and no more information was provided.

Closing lotus issue ticket.

If you are still experiencing problems, open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

**Comment by jack815943555** [comment] 2022-03-09 13:35
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Closed by Reiers** 2022-03-09 13:35 UTC
