### ISSUE TITLE
lotus daemon crashed

### ISSUE THREAD

**Issue by carryon** [filecoin-project/lotus#1444] opened 2020-03-24 03:12 UTC
**Describe the bug**

lotus daemon crashed when this error happens.

**To Reproduce**
1. Run '...'
2. See error

```
2020-03-24T08:48:45.063+0800	INFO	blocksync	blocksync/blocksync.go:101	block sync request	{"start": [{"/":"bafy2bzaceb5t72l22ivbdh5ifps66opbll32ljpjog4fwu7rxwpomj3n7lu6i"}], "len": 500}
2020-03-24T08:48:45.063+0800	WARN	blocksync	blocksync/blocksync.go:143	encountered error while responding to block sync request: failed loading tipset {bafy2bzaceb5t72l22ivbdh5ifps66opbll32ljpjog4fwu7rxwpomj3n7lu6i}: get block bafy2bzaceb5t72l22ivbdh5ifps66opbll32ljpjog4fwu7rxwpomj3n7lu6i: blockstore: block not found
2020-03-24T08:48:45.135+0800	INFO	sub	sub/incoming.go:43	New block over pubsub: bafy2bzaceblxyvbnogpsckb6zit5wvkqbclqfkh7bmkifprwlcqqujedk7ad4
2020-03-24T08:48:45.136+0800	INFO	sub	sub/incoming.go:60	new block over pubsub	{"cid": "bafy2bzaceblxyvbnogpsckb6zit5wvkqbclqfkh7bmkifprwlcqqujedk7ad4", "source": "12D3KooWFpoUmvpwLWoMM3sHkg1HHNK4iA7A23by5vJwP1E2ZDA8", "msgfetch": 0.000415779}
2020-03-24T08:48:45.163+0800	INFO	chain	chain/sync_manager.go:283	scheduling incoming tipset sync: [bafy2bzaceblxyvbnogpsckb6zit5wvkqbclqfkh7bmkifprwlcqqujedk7ad4]
2020-03-24T08:48:45.320+0800	INFO	sub	sub/incoming.go:43	New block over pubsub: bafy2bzacedzscmxzsgl6gxpqsadhp6iuglwtgz2klsnpum4a4yxldwumifvqc
2020-03-24T08:48:45.320+0800	INFO	sub	sub/incoming.go:60	new block over pubsub	{"cid": "bafy2bzacedzscmxzsgl6gxpqsadhp6iuglwtgz2klsnpum4a4yxldwumifvqcunexpected fault address 0x7f79135b9ad7
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f79135b9ad7 pc=0x54e9c5]

goroutine 19589579 [running]:
runtime.throw(0x1c976fd, 0x5)
	/usr/lib/golang/src/runtime/panic.go:774 +0x72 fp=0xc019e8f458 sp=0xc019e8f428 pc=0x51d152
runtime.sigpanic()
	/usr/lib/golang/src/runtime/signal_unix.go:391 +0x455 fp=0xc019e8f488 sp=0xc019e8f458 pc=0x532c55
runtime.memmove(0xc056edc000, 0x7f791342da54, 0x18c103)
	/usr/lib/golang/src/runtime/memmove_amd64.s:390 +0x485 fp=0xc019e8f490 sp=0xc019e8f488 pc=0x54e9c5
github.com/dgraph-io/badger/v2/y.SafeCopy(...)
	/root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200120142413-c3333a5a830e/y/y.go:101
github.com/dgraph-io/badger/v2.(*Item).ValueCopy(0xc028cefe40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200120142413-c3333a5a830e/iterator.go:129 +0x227 fp=0xc019e8f568 sp=0xc019e8f490 pc=0xd12237
github.com/ipfs/go-ds-badger2.(*txn).get(0xc019e8f688, 0xc03bb437c0, 0x4c, 0xc03bb437c0, 0xc03bb437c7, 0xc019e8f680, 0x45, 0x45)
	/root/go/pkg/mod/github.com/ipfs/go-ds-badger2@v0.0.0-20200123200730-d75eb2678a5d/datastore.go:484 +0xe1 fp=0xc019e8f5d8 sp=0xc019e8f568 pc=0xd50531
github.com/ipfs/go-ds-badger2.(*Datastore).Get(0xc03fd53620, 0xc03bb437c0, 0x4c, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/ipfs/go-ds-badger2@v0.0.0-20200123200730-d75eb2678a5d/datastore.go:277 +0x163 fp=0xc019e8f6b0 sp=0xc019e8f5d8 pc=0xd4e753
github.com/ipfs/go-datastore/keytransform.(*Datastore).Get(0xc00000ed00, 0xc03bb43770, 0x45, 0xc03bb43770, 0x45, 0x3d, 0x3e, 0xc01d0414c0)
	/root/go/pkg/mod/github.com/ipfs/go-datastore@v0.3.1/keytransform/keytransform.go:47 +0x76 fp=0xc019e8f700 sp=0xc019e8f6b0 pc=0x9dddf6
github.com/ipfs/go-datastore/keytransform.(*Datastore).Get(0xc00000ed20, 0xc01d041500, 0x3e, 0xc01d041500, 0x3e, 0x30, 0x20, 0x2a)
	/root/go/pkg/mod/github.com/ipfs/go-datastore@v0.3.1/keytransform/keytransform.go:47 +0x76 fp=0xc019e8f750 sp=0xc019e8f700 pc=0x9dddf6
github.com/ipfs/go-ipfs-blockstore.(*blockstore).Get(0xc00000ed40, 0xc0547b05d0, 0x26, 0x0, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/ipfs/go-ipfs-blockstore@v0.1.1/blockstore.go:123 +0xaf fp=0xc019e8f820 sp=0xc019e8f750 pc=0x9e07ef
github.com/ipfs/go-ipfs-blockstore.(*idstore).Get(0xc03fdce1e0, 0xc0547b05d0, 0x26, 0x2e58f20, 0x51befa, 0xc044aeea20, 0xc0474a57c0)
	/root/go/pkg/mod/github.com/ipfs/go-ipfs-blockstore@v0.1.1/idstore.go:57 +0xd7 fp=0xc019e8f870 sp=0xc019e8f820 pc=0x9e1ad7
github.com/ipfs/go-hamt-ipld.(*bswrapper).GetBlock(0xc0474a57a0, 0x1fbab20, 0xc044aeea20, 0xc0547b05d0, 0x26, 0xc0474a57c0, 0x1b98720, 0x72, 0xc019e8fad8)
	/root/go/pkg/mod/github.com/ipfs/go-hamt-ipld@v0.0.14-0.20191218031521-b2c774a54db1/ipld.go:89 +0x47 fp=0xc019e8f8b8 sp=0xc019e8f870 pc=0xa69707
github.com/ipfs/go-hamt-ipld.(*CborIpldStore).Get(0xc05488a800, 0x1fbab20, 0xc044aeea20, 0xc0547b05d0, 0x26, 0x1c30a60, 0xc046ac4e10, 0x0, 0x0)
	/root/go/pkg/mod/github.com/ipfs/go-hamt-ipld@v0.0.14-0.20191218031521-b2c774a54db1/ipld.go:131 +0xf9 fp=0xc019e8f9a0 sp=0xc019e8f8b8 pc=0xa698b9
github.com/ipfs/go-hamt-ipld.LoadNode(0x1fbaae0, 0xc00003e0a8, 0xc05488a800, 0xc0547b05d0, 0x26, 0x0, 0x0, 0x0, 0x7f8ec71b7008, 0x0, ...)
	/root/go/pkg/mod/github.com/ipfs/go-hamt-ipld@v0.0.14-0.20191218031521-b2c774a54db1/hamt.go:143 +0x88 fp=0xc019e8fa08 sp=0xc019e8f9a0 pc=0xa66eb8
github.com/filecoin-project/lotus/chain/state.LoadStateTree(0xc05488a800, 0xc0547b05d0, 0x26, 0x7f8e3429b3c0, 0xc03fdce1e0, 0x26)
	/root/maxiaoping/lotus/chain/state/statetree.go:37 +0x83 fp=0xc019e8fab8 sp=0xc019e8fa08 pc=0xad5493
github.com/filecoin-project/lotus/chain.(*Syncer).checkBlockMessages(0xc03fdb93e0, 0x1fbab60, 0xc0541201b0, 0xc02aa844c0, 0xc031cf2800, 0x55d984, 0x51befa)
	/root/maxiaoping/lotus/chain/sync.go:742 +0x6da fp=0xc019e8ff18 sp=0xc019e8fab8 pc=0xd8bf2a
github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func2(0xc01e3a5780, 0x8)
	/root/maxiaoping/lotus/chain/sync.go:570 +0x52 fp=0xc019e8ff70 sp=0xc019e8ff18 pc=0xd95ca2
github.com/Gurpartap/async.Err.func1(0xc027a106c0, 0xc054120240, 0xc06c69d630)
	/root/go/pkg/mod/github.com/!gurpartap/async@v0.0.0-20180927173644-4f7f499dd9ee/error.go:29 +0x5b fp=0xc019e8ffc8 sp=0xc019e8ff70 pc=0xc2311b
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc019e8ffd0 sp=0xc019e8ffc8 pc=0x54d391
created by github.com/Gurpartap/async.Err
	/root/go/pkg/mod/github.com/!gurpartap/async@v0.0.0-20180927173644-4f7f499dd9ee/error.go:27 +0x8a

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7f8e18151be0, 0x72, 0x0)
	/usr/lib/golang/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc03e08d798, 0x72, 0x0, 0x0, 0x1c99d78)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc03e08d780, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/internal/poll/fd_unix.go:384 +0x1f8
net.(*netFD).accept(0xc03e08d780, 0xb41924, 0x1c65900, 0xc054108540)
	/usr/lib/golang/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc01f2c6dc0, 0x1fd1680, 0x20300c, 0x20300c)
	/usr/lib/golang/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc01f2c6dc0, 0x1e213b0, 0xc046077668, 0x6b5f630c, 0xc3d015ad583c97c2)
	/usr/lib/golang/src/net/tcpsock.go:261 +0x47
github.com/multiformats/go-multiaddr-net.(*maListener).Accept(0xc01f2c6e40, 0x182b03bf46077668, 0x5e7958ed, 0xc0460776c8, 0x575b06)
	/root/go/pkg/mod/github.com/multiformats/go-multiaddr-net@v0.1.1/net.go:243 +0x37
github.com/multiformats/go-multiaddr-net.(*netListenerAdapter).Accept(0xc000101390, 0xc046077718, 0x18, 0xc000000180, 0x80c7ee)
	/root/go/pkg/mod/github.com/multiformats/go-multiaddr-net@v0.1.1/net.go:222 +0x33
net/http.(*Server).Serve(0xc0497e3c00, 0x1fb3ae0, 0xc000101390, 0x0, 0x0)
	/usr/lib/golang/src/net/http/server.go:2896 +0x286
main.serveRPC(0x1fe2ac0, 0xc0004d0700, 0xc039d85350, 0x1fd1680, 0xc01d7014a0, 0xc039d85350, 0x0)
	/root/maxiaoping/lotus/cmd/lotus/rpc.go:77 +0x5af
main.glob..func1(0xc0005a8f90, 0x0, 0x0)
	/root/maxiaoping/lotus/cmd/lotus/daemon.go:194 +0xe21
gopkg.in/urfave/cli%2ev2.(*Command).Run(0x2d5f0c0, 0xc0005a8f30, 0x0, 0x0)
	/root/go/pkg/mod/gopkg.in/urfave/cli.v2@v2.0.0-20180128182452-d3ae77c26ac8/command.go:167 +0x6cf
gopkg.in/urfave/cli%2ev2.(*App).Run(0xc000580480, 0xc00000e080, 0x2, 0x2, 0x0, 0x0)
	/root/go/pkg/mod/gopkg.in/urfave/cli.v2@v2.0.0-20180128182452-d3ae77c26ac8/app.go:261 +0x68c
main.main()
	/root/maxiaoping/lotus/cmd/lotus/main.go:71 +0x632

goroutine 6 [select, 3384 minutes]:
github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine(0xc000138e40)
	/root/go/pkg/mod/github.com/ipfs/go-log@v1.0.1/writer/writer.go:76 +0x144
created by github.com/ipfs/go-log/writer.NewMirrorWriter
	/root/go/pkg/mod/github.com/ipfs/go-log@v1.0.1/writer/writer.go:41 +0xb9

goroutine 7 [syscall, 3384 minutes]:
os/signal.signal_recv(0x0)
	/usr/lib/golang/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/lib/golang/src/os/signal/signal_unix.go:29 +0x41

goroutine 9 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0001585f0)
	/root/go/pkg/mod/go.opencensus.io@v0.22.2/stats/view/worker.go:154 +0x100
created by go.opencensus.io/stats/view.init.0
	/root/go/pkg/mod/go.opencensus.io@v0.22.2/stats/view/worker.go:32 +0x57

goroutine 60 [select, 2 minutes]:
github.com/libp2p/go-libp2p-connmgr.(*BasicConnMgr).background(0xc000497b00)
	/root/go/pkg/mod/github.com/libp2p/go-libp2p-connmgr@v0.1.0/connmgr.go:196 +0x11c
created by github.com/libp2p/go-libp2p-connmgr.NewConnManager
	/root/go/pkg/mod/github.com/libp2p/go-libp2p-connmgr@v0.1.0/connmgr.go:114 +0x1e5

goroutine 105 [select]:
github.com/filecoin-project/lotus/chain/store.(*ChainStore).reorgWorker.func1(0xc03fdb8120, 0xc03fde0000, 0x1fbaae0, 0xc00003e0c0)
	/root/maxiaoping/lotus/chain/store/store.go:275 +0x361
```

**Version (run `lotus --version`):**
lotus version 0.2.8+git628a598.dirty

OS:
CentOS Linux release 7.7.1908 (Core)
4.14.35-1902.9.2.el7uek.x86_64

**Comment by magik6k** [comment] 2020-04-22 16:32
Duplicate of #1437

**Closed by magik6k** 2020-04-22 16:32 UTC
