### ISSUE TITLE
[BUG] Sometimes C1 starts by lotus-miner instead of separate worker.

### ISSUE THREAD

**Issue by mrworkdev** [filecoin-project/lotus#6257] opened 2021-05-14 18:16 UTC
$ lotus version
```
Daemon:  1.9.0-rc1+mainnet+git.95e0c3df1+api1.2.0
Local: lotus version 1.9.0-rc1+mainnet+git.95e0c3df1
```

Miner config.toml:
```
[Storage]
  ParallelFetchLimit = 10
  AllowAddPiece = false
  AllowPreCommit1 = false
  AllowPreCommit2 = false
  AllowCommit = false
  AllowUnseal = false
```

Most of times C1 starts on workers on separate servers but sometimes it starts directly on miner server (lotus-miner itself).
And lasts few minutes insted on few seconds. Found by hostname in "lotus-miner sealing jons".

**Comment by Reiers** [comment] 2022-01-04 22:09
Hi @mrworkdev 

I'm not able to reproduce this issue on:
```
Daemon:  1.13.2-rc4+mainnet+git.e05fdf892+api1.4.0
Local: lotus version 1.13.2-rc4+mainnet+git.e05fdf892
```

Remember to restart the miner if you edit anything in `config.toml`.
_And double check that you don't have attached a sealing path to your miner._ 

Closing the Lotus issue ticket. 

If you are still experiencing this issue, open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

**Closed by Reiers** 2022-01-04 22:09 UTC
Labels: kind/bug
