### ISSUE TITLE
calibration net: deals fail if miner has no peers, even if `lotus-miner actor set-addr` is set

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/lotus#2724] opened 2020-07-30 23:46 UTC
**Describe the bug**

I was making a test deal against @ribasushi's miner at `t023515`. His machine was discoverable via the on-chain information because he set `lotus-miner actor set-addr /ip4/34.223.52.127/tcp/28003/p2p/12D3KooWC59Ap2nhWMdSKbat6rErhNCgeNR1z8i8ZqaxxEav7HuZ`

<img width="645" alt="Screen Shot 2020-07-30 at 3 19 20 PM" src="https://user-images.githubusercontent.com/20886/88984710-2f0ab100-d283-11ea-8c7c-88956f2c0a29.png">

However, we discovered that `lotus-miner net peers` was only listed one peer (the node) ... seems like issue #2267 again.

When I tried to make a deal, it failed with "sending proposal to storage provider failed: routing: not found":

<img width="607" alt="Screen Shot 2020-07-30 at 4 37 52 PM" src="https://user-images.githubusercontent.com/20886/88984673-14d0d300-d283-11ea-94de-45844b09cc3e.png">

Subsequently, we added peers using `lotus-miner net connect ...` and afterwards he was discoverable via the DHT and subsequent deals are now in the sealing state.

**To Reproduce**
1. Set up a new miner
2. If bug #2267 is happening, it will show only one peer for `lotus-miner net peers` and won't be shown in the DHT when trying to discover using `lotus net findpeer ...`.
3. Use `lotus-miner actor set-addrs ...` and confirm that it's on chain
4. Try to make a deal, wait for error.

**Version (run `lotus version`):**

```
Daemon:  0.4.1+git.4c7cdd1a+api0.8.1
Local: lotus version 0.4.1+git.4c7cdd1a
```

**Comment by Shekelme** [comment] 2020-08-04 05:43
Right now I was forced to connect my lotus-miner to bootstrap peers manyally. `lotus-miner net peers` was only listed one peer (the host itself with it's LAN IP).

**Comment by Reiers** [comment] 2021-12-12 15:52
**was not able to reproduce the issue.**
So its most likely solved in newer versions of Lotus. 
I'm running: 
`lotus version 1.13.2-rc4+mainnet+git.e05fdf892`

Closing the ticket.
_Please open a new ticket if the issue persist._

**Closed by Reiers** 2021-12-12 15:52 UTC
