### ISSUE TITLE
Message block, cannot execute windowPost

### ISSUE THREAD

**Issue by verynohair** [filecoin-project/lotus#5308] opened 2021-01-08 11:16 UTC
Help me. It makes me lose power.

There are 12 blocked message.

The daemon log shows 
**2021-01-08T19:13:20.005+0800    INFO    messagepool     messagepool/repub.go:128        republishing 12 messages**
2021-01-08T19:13:30.456+0800    INFO    bs:sess session/session.go:459  No peers - broadcasting {"session": 18, "want-count": 5}
2021-01-08T19:13:30.485+0800    INFO    chain   chain/sync_manager.go:232       selected sync target: [bafy2bzaceb3545vner5fotoxh6kyfazxg2tfjs2blde4ytdspeezthshctssc]
2021-01-08T19:13:30.485+0800    INFO    chain   chain/sync_manager.go:314       worker 51 syncing in [bafy2bzaceb3545vner5fotoxh6kyfazxg2tfjs2blde4ytdspeezthshctssc]
2021-01-08T19:13:30.628+0800    INFO    chain   chain/sync.go:718       block validation        {"took": 0.139552888, "height": "393267", "age": 0.62853753}
2021-01-08T19:13:30.628+0800    INFO    chainstore      store/store.go:513      New heaviest tipset! [bafy2bzaceb3545vner5fotoxh6kyfazxg2tfjs2blde4ytdspeezthshctssc] (height=393267)
2021-01-08T19:13:30.629+0800    INFO    chain   chain/sync_manager.go:322       worker 51 done; took 143.978173ms

**Error log:**
**2021-01-08T19:14:35.729+0800    WARN    vm      vm/runtime.go:145       VM.Call failure: failed to submit proof for bulk verification (RetCode=7):
    github.com/filecoin-project/specs-actors/v2/actors/builtin.RequireSuccess
        /root/go/pkg/mod/github.com/filecoin-project/specs-actors/v2@v2.3.3/actors/builtin/shared.go:49**
2021-01-08T19:14:35.729+0800    WARN    vm      vm/vm.go:529    Send actor error        {"from": "f3ro3i54tule2vtdcsjdkzjkf6djx3wwe5znv5h4kwxprxjyojvgyqtyvxus5bj73dy64x4paiqriwupmei3va", "to": "f09652", "nonce": 3766989, "method": "7", "height": "393269", "error": "failed to submit proof for bulk verification (RetCode=7):\n    github.com/filecoin-project/specs-actors/v2/actors/builtin.RequireSuccess\n        /root/go/pkg/mod/github.com/filecoin-project/specs-actors/v2@v2.3.3/actors/builtin/shared.go:49"}
2021-01-08T19:14:35.730+0800    WARN    vm      vm/runtime.go:145       VM.Call failure: not enough gas: used=62555451, available=62924560, use=716340 (RetCode=7):
    github.com/filecoin-project/lotus/chain/vm.(*Runtime).chargeGasInternal
        /opt/upload/all/lotus_bk/chain/vm/runtime.go:575
2021-01-08T19:14:35.730+0800    WARN    vm      vm/runtime.go:376       vmctx send failed: to: f04, method: 8: ret: [], err: not enough gas: used=62555451, available=62924560, use=716340 (RetCode=7)
2021-01-08T19:14:35.730+0800    WARN    vm      vm/runtime.go:332       Abortf: failed to submit proof for bulk verification
2021-01-08T19:14:35.730+0800    WARN    vm      vm/runtime.go:145       VM.Call failure: failed to submit proof for bulk verification (RetCode=7):
    github.com/filecoin-project/specs-actors/v2/actors/builtin.RequireSuccess
        /root/go/pkg/mod/github.com/filecoin-project/specs-actors/v2@v2.3.3/actors/builtin/shared.go:49
2021-01-08T19:14:35.730+0800    WARN    vm      vm/vm.go:529    Send actor error        {"from": "f3ro3i54tule2vtdcsjdkzjkf6djx3wwe5znv5h4kwxprxjyojvgyqtyvxus5bj73dy64x4paiqriwupmei3va", "to": "f09652", "nonce": 3766990, "method": "7", "height": "393269", "error": "failed to submit proof for bulk verification (RetCode=7):\n    github.com/filecoin-project/specs-actors/v2/actors/builtin.RequireSuccess\n        /root/go/pkg/mod/github.com/filecoin-project/specs-actors/v2@v2.3.3/actors/builtin/shared.go:49"}

The lotus version: lotus version 1.4.0+git.858994a63.dirty

Please help me.!!!!!!

**Comment by verynohair** [comment] 2021-01-08 12:04
How to solve, it makes all my power lose and cannot be restore

**Comment by PatrickDeuse** [comment] 2021-01-12 14:15
is this solved? then please close it. did raising the gas-limit solved it?

**Comment by Fatman13** [comment] 2021-03-24 05:13
Anyone looked into this yet? Getting same error.

**Comment by Reiers** [comment] 2022-04-21 21:54
Hi @verynohair 

Thanks for the report. The issue is outdated.

If you are still experiencing problems - please open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

**Closed by Reiers** 2022-04-21 21:54 UTC
