### ISSUE TITLE
Sector has been waiting for commit

### ISSUE THREAD

**Issue by alingb** [filecoin-project/lotus#4935] opened 2020-11-20 03:28 UTC
**Describe the problem**

Sector has been waiting for commit

**Sectors status**

The output of `lotus-miner sectors status --log <sectorId>` for the failed sector(s).

**Lotus miner logs**

root@lotus-master:~# lotus-miner sectors list
…………
125  CommitWait            NO       NO      n/a                           CC
126  CommitWait            NO       NO      n/a                           CC
127  CommitWait            NO       NO      n/a                           CC
128  CommitWait            NO       NO      n/a                           CC
129  Proving               YES      YES     1800878 (in 1 year 24 weeks)  CC
130  CommitWait            NO       NO      n/a                           CC
131  Proving               YES      NO      830318 (in 28 weeks 5 days)   1      127.1KiB
132  PreCommitWait         NO       NO      n/a                           CC
133  PreCommitWait         NO       NO      n/a                           CC
134  PreCommitWait         NO       NO      n/a                           CC
135  PreCommit2            NO       NO      n/a                           CC
136  PreCommitWait         NO       NO      n/a                           CC
142  PreCommitWait         NO       NO      n/a                           CC
143  PreCommitWait         NO       NO      n/a                           CC
144  PreCommit1            NO       NO      n/a                           CC
145  PreCommit1            NO       NO      n/a                           CC
146  PreCommit2            NO       NO      n/a                           CC
147  PreCommit1            NO       NO      n/a                           CC
…………

root@lotus-master:~# lotus-miner sectors status -log 125
SectorID:	125
Status:		CommitWait
CIDcommD:	baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq
CIDcommR:	bagboea4b5abcazcuh3xt6mjsnlk5sjms7g4gz7qe4f6xtxwwtzwutdwecomue6ri
Ticket:		2d9133dc4804c46177a0c82518a1aa1bf3539269503b66e21cebbb9d66049a12
TicketH:	245149
Seed:		f30b3a97862003bd996915ef286a95c72f78904870136840acf54f78398c8a77
SeedH:		248812
Precommit:	bafy2bzacedx3k6ofaouzdlg6smuayr7svzsvutbveemvz3imndjg27soc5uao
Commit:		bafy2bzacebhmkse2gsu3vddqvjktfvidemibtvjc6dlifmahijg6le3zrloii
Proof:		b0389104195b80b4c7749aef9dfe04775fc932cfe8284b38ba1a0dd2ce8b7c82594cb16d57958c32982e1fb134d9ec6b857735ba64027c8fe103d79e416d71701bf87a4a5f15f55394ddb68c2854024d65cbcc48beecceeb824927882073d9d30e35a2cbef38c2d63aadfcc5fb0ec33d90af3995ec704591c5fb5b65621a6fd0d5cda0f2c6cde180fb25125eb328f0d683b0bf5300c424f26cc052461353aa8893d6a012645b9f39e593c8ceee9d05a7c6e3d2bee80baefa327297190d91e16289b95472ed24aa25492ecfbfa5997228b2cc3eb091e31261b605436c603f633ef396418cc582073456368b44de2edb3083917220ad70d781ea581332bb15c04e8592c0a3026627e96354cc4b5375f49f0d762225c715254a4a1664a89458e2641937c61c8faa9aa167ed924c0f95492d7bab3a27dd984c155a20a1d4212af14c46b989f790b9654f14a03b96317de10ea9741c910a557fb86172ddd97782ea56f8bbc0b4e823fa5cdb08d69935b7eb9877e580f30905f3d6e11300581fb8f842b7cba6ed3306fcb2153ecae345b1eb9f8cc951ee1d758b32e4473e84534cbaa41f865360b74b30dc1ec126c8bc7c7e8291dd30105cf5da2a322b480f3033fb1281096fa691541a9b2d5a1a2ee886ee72aec9e95f1c6b3fdd063a65da6f8ef89c180a40e996dfb5a85f5adab7e494dda9961414e43d7325cf6eaaa8707ec00dbe1f236e5ceb26364ba1e921cff5997aadaa8417504f79268fd241ddfcaf132589342356bcb66c458fef431b9cd98d1244df90d63a2c429e746d4f871b4fcae63e94f4458fb221963a03675028d06d28c8bf40952e800af5b76785cc631e5986bb1505707b6165653bea82ebbb7dbd3460a5e2030c37de77ff30ddd349267bf25d141d9201cca510722f8ef52a2e131ae2eca86ba133cdf2d65a7889406086cb13112a1793d0587216bccdb36eab6db4b51089925c6457a6bb714aeeff46a99a911f54a859290f019d63b57e74dc416499a45be122add4906fbaa328b7f339990ceae3b3df94419cd36af6839ee42cdf3e5c91c74ba072b2f3092e844f1ef4f12ba8ed2f51d71a5a13694067650ff0da15dfddfd69183f57b303df5089d99397593e1078e8b9458c370007bcdefde72cecb3f9e4e74b70cafb6cedcc4438a2982c60fe1d2a94fa807ecf652e67e867d56716b288db7de3d0d0675fa2b55402d14e10c6686edbd910b6e4c9cea0a7df299ffab43c8bf689fc1d3d9e114c1b4418998b4ed181d6bf138132000a304c5b145f98276f840be08195036bbdc2cb519d48fb8b016e8c6625b356c8328554005b6c8ef1f5de873cd318bd489cdfce51f77c8cdc45862560047cb78fa436360afee4e5ede921a4ede656a6df900e76996dd184092ff1b5af160aff57304b62353652a64ddf70a3a4b463929561376d9e0b47f11a6082b0c2f1d32a09c94c42ee8082c32cce522aaf2c6ea9fbccfcbcbdc8f10da728775bafa346ae1d2e1adf65db9198c1b3b6984ccc156de5446e8c3b0acf18877afe559e322882fee40c6c0f28ee959a1c132aef9594839b56b4324f775dab15f00bdb34f269f2f8339058c6d161f5a39a2d9f3cc8ab70fdbc5c9c1b2b8c93a19c9dc7ecfb6ddc8dac2c551b96b50d2097db6fd9203162f51935f1e6ec0b56b547e7d9ee2da249327809e42207ea894ed795354b21d93179c6821daf1d80f532885e0c631eda3c4fdcaddef04e2a83042f795dcfc052cbf6447507b3db090cd09bf4ac86a66743d0adfe42bd570b4a08db7cf630ae390dde0b23492806d9ef675055af44ec66177a0cb14ea625e681e89a12787ca8e3b75ef064d121385dbcf8d8ac7549cf9303d6e8b2f4666f28abe7683dc41d672ff7e45f206b3e419a9876cfc13df27382cfab2789e610e29b7856d78492e33b801ae20eb95738a6dc0cb6a5ddd01ac6b6a3d4f25cdaffd1258a40e74cb1625a415c26acc15f01d52594007639e9ed63762f60f5b2a66d823d95b99a675331ab64e12b082e469e029b0bfd8d9b1faa548e8aacd20cdf625acd5a5bb0dc6d0a9459f88d82c6b7d56e795cd85e05489b61520b370d0afbf49feaad7ea21345beb871557aca743bbcc39193975ca72af730e32d56ab8e62b464fb43893a9f9df6d16a291d98fe8b6d651fa957675abb470e93d87228b87167f1982f42bec565152631dd73539c3d463bcf58a33a58f6b422c5fae3ba201fa912518dcc9b119810951c55e54af376bfdd67e99ac75a9c8ae60d51908c1f291258c3f00fe000da21e4244eff2f53c4a9c23a100c24a4171250e9d9145a4077583dbdf498685207112920bf9f714790a25cd1c239a25de250d9e2675e79d42f68b5aaa56a88a37ea46c03be0f85db6c2046a45dcfcc36663a4c10256b9ead0fb717ea2a9534907e229b1d437ebd819743285685ba613bd1352bb7770349d0fe997ffc413d68dea62c333f1b9c61349eabdea55ae1543e0045dd04af4f06f8dcf052bf8a3a368657cf75ae46b49b478c425de55c9c0e971330cf46b971e23e3ee58b8d5bd14310f79aabad43e58fcda4c85d630d98674e588f0cc7d2182053eda8481aa4981db5dcfaf8bd2a209505bc23e4a4361389655df5af10606378bd3a3ca8eaaa9aef1d8aa65d81777a1f78fd3ce79d10e3f9179303f106299791a1f197e91df71c26a6d8b535dd3d7c463b21f10c8d
Deals:		[0]
Retries:	0
--------
Event Log:
0.	2020-11-18 16:24:46 +0800 CST:	[event;sealing.SectorStartCC]	{"User":{"ID":125,"SectorType":3,"Pieces":[{"Piece":{"Size":34359738368,"PieceCID":{"/":"baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq"}},"DealInfo":null}]}}
1.	2020-11-18 16:24:46 +0800 CST:	[event;sealing.SectorPacked]	{"User":{"FillerPieces":null}}
2.	2020-11-18 16:24:46 +0800 CST:	[event;sealing.SectorTicket]	{"User":{"TicketValue":"LZEz3EgExGF3oMglGKGqG/NTkmlQO2biHOu7nWYEmhI=","TicketEpoch":245149}}
3.	2020-11-18 21:27:47 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
4.	2020-11-18 21:27:47 +0800 CST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	seal pre commit(1) failed: worker restarted
5.	2020-11-18 21:28:47 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
6.	2020-11-18 21:39:13 +0800 CST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	seal pre commit(1) failed: acquiring sector paths: local acquire error: couldn't find a suitable path for a sector
7.	2020-11-18 21:40:13 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
8.	2020-11-19 11:16:02 +0800 CST:	[event;sealing.SectorPreCommit1]	{"User":{"PreCommit1Out":"eyJyZWdpc3RlcmVkX3Byb29mIjoiU3RhY2tlZERyZzMyR2lCVjEiLCJsYWJlbHMiOnsiU3RhY2tlZERyZzMyR2lCVjEiOnsibGFiZWxzIjpbeyJwYXRoIjoiL2RhdGEzL0xPVFVTX1dPUktFUl9QQVRIL2NhY2hlL3MtdDA1NzQ2Ni0xMjUiLCJpZCI6ImxheWVyLTEiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhMy9MT1RVU19XT1JLRVJfUEFUSC9jYWNoZS9zLXQwNTc0NjYtMTI1IiwiaWQiOiJsYXllci0yIiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvZGF0YTMvTE9UVVNfV09SS0VSX1BBVEgvY2FjaGUvcy10MDU3NDY2LTEyNSIsImlkIjoibGF5ZXItMyIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2RhdGEzL0xPVFVTX1dPUktFUl9QQVRIL2NhY2hlL3MtdDA1NzQ2Ni0xMjUiLCJpZCI6ImxheWVyLTQiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhMy9MT1RVU19XT1JLRVJfUEFUSC9jYWNoZS9zLXQwNTc0NjYtMTI1IiwiaWQiOiJsYXllci01Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvZGF0YTMvTE9UVVNfV09SS0VSX1BBVEgvY2FjaGUvcy10MDU3NDY2LTEyNSIsImlkIjoibGF5ZXItNiIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2RhdGEzL0xPVFVTX1dPUktFUl9QQVRIL2NhY2hlL3MtdDA1NzQ2Ni0xMjUiLCJpZCI6ImxheWVyLTciLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhMy9MT1RVU19XT1JLRVJfUEFUSC9jYWNoZS9zLXQwNTc0NjYtMTI1IiwiaWQiOiJsYXllci04Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvZGF0YTMvTE9UVVNfV09SS0VSX1BBVEgvY2FjaGUvcy10MDU3NDY2LTEyNSIsImlkIjoibGF5ZXItOSIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2RhdGEzL0xPVFVTX1dPUktFUl9QQVRIL2NhY2hlL3MtdDA1NzQ2Ni0xMjUiLCJpZCI6ImxheWVyLTEwIiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvZGF0YTMvTE9UVVNfV09SS0VSX1BBVEgvY2FjaGUvcy10MDU3NDY2LTEyNSIsImlkIjoibGF5ZXItMTEiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9XSwiX2giOm51bGx9fSwiY29uZmlnIjp7InBhdGgiOiIvZGF0YTMvTE9UVVNfV09SS0VSX1BBVEgvY2FjaGUvcy10MDU3NDY2LTEyNSIsImlkIjoidHJlZS1kIiwic2l6ZSI6MjE0NzQ4MzY0Nywicm93c190b19kaXNjYXJkIjo3fSwiY29tbV9kIjpbNywxMjYsOTUsMjIyLDUzLDE5NywxMCwxNDcsMywxNjUsODAsOSwyMjcsNzMsMTM4LDc4LDE5MCwyMjMsMjQzLDE1Niw2NiwxODMsMTYsMTgzLDQ4LDIxNiwyMzYsMTIyLDE5OSwxNzUsMTY2LDYyXX0="}}
9.	2020-11-19 11:49:32 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
10.	2020-11-19 14:10:43 +0800 CST:	[event;sealing.SectorPreCommit2]	{"User":{"Sealed":{"/":"bagboea4b5abcazcuh3xt6mjsnlk5sjms7g4gz7qe4f6xtxwwtzwutdwecomue6ri"},"Unsealed":{"/":"baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq"}}}
11.	2020-11-19 14:10:43 +0800 CST:	[event;sealing.SectorPreCommitted]	{"User":{"Message":{"/":"bafy2bzacedx3k6ofaouzdlg6smuayr7svzsvutbveemvz3imndjg27soc5uao"},"PreCommitDeposit":"120490551431432202","PreCommitInfo":{"SealProof":3,"SectorNumber":125,"SealedCID":{"/":"bagboea4b5abcazcuh3xt6mjsnlk5sjms7g4gz7qe4f6xtxwwtzwutdwecomue6ri"},"SealRandEpoch":245149,"DealIDs":[],"Expiration":1800878,"ReplaceCapacity":false,"ReplaceSectorDeadline":0,"ReplaceSectorPartition":0,"ReplaceSectorNumber":0}}}
12.	2020-11-19 14:14:00 +0800 CST:	[event;sealing.SectorPreCommitLanded]	{"User":{"TipSet":"AXGg5AIg1EWwY3wP887+uQ14YHo/Qc1GGA8W6+qdrhtIRCYKbAEBcaDkAiBams0h8ozjpqldyk/sZQVLeouhdSLaYzHOf6go26b3/gFxoOQCIMH3M5dOmuuTSZECoiKhMenQXhbafOdVS8/Fi8pl425lAXGg5AIgIFhp1xoev3QciLFvoFOaPDu7NuiiybaNWLpkIl/6EBABcaDkAiDNV8oBuBS83VQPE1yYMVGcf58yorbPh2ALIF/aDQv8Sw=="}}
13.	2020-11-19 15:29:00 +0800 CST:	[event;sealing.SectorSeedReady]	{"User":{"SeedValue":"8ws6l4YgA72ZaRXvKGqVxy94kEhwE2hArPVPeDmMinc=","SeedEpoch":248812}}
14.	2020-11-19 17:09:13 +0800 CST:	[event;sealing.SectorCommitted]	{"User":{"Proof":"sDiRBBlbgLTHdJrvnf4Ed1/JMs/oKEs4uhoN0s6LfIJZTLFtV5WMMpguH7E02exrhXc1umQCfI/hA9eeQW1xcBv4ekpfFfVTlN22jChUAk1ly8xIvuzO64JJJ4ggc9nTDjWiy+84wtY6rfzF+w7DPZCvOZXscEWRxftbZWIab9DVzaDyxs3hgPslEl6zKPDWg7C/UwDEJPJswFJGE1OqiJPWoBJkW5855ZPIzu6dBafG49K+6Auu+jJylxkNkeFiiblUcu0kqiVJLs+/pZlyKLLMPrCR4xJhtgVDbGA/Yz7zlkGMxYIHNFY2i0TeLtswg5FyIK1w14HqWBMyuxXAToWSwKMCZifpY1TMS1N19J8NdiIlxxUlSkoWZKiUWOJkGTfGHI+qmqFn7ZJMD5VJLXurOifdmEwVWiCh1CEq8UxGuYn3kLllTxSgO5YxfeEOqXQckQpVf7hhct3Zd4LqVvi7wLToI/pc2wjWmTW365h35YDzCQXz1uETAFgfuPhCt8um7TMG/LIVPsrjRbHrn4zJUe4ddYsy5Ec+hFNMuqQfhlNgt0sw3B7BJsi8fH6Ckd0wEFz12ioyK0gPMDP7EoEJb6aRVBqbLVoaLuiG7nKuyelfHGs/3QY6ZdpvjvicGApA6ZbftahfWtq35JTdqZYUFOQ9cyXPbqqocH7ADb4fI25c6yY2S6HpIc/1mXqtqoQXUE95Jo/SQd38rxMliTQjVry2bEWP70MbnNmNEkTfkNY6LEKedG1PhxtPyuY+lPRFj7IhljoDZ1Ao0G0oyL9AlS6ACvW3Z4XMYx5ZhrsVBXB7YWVlO+qC67t9vTRgpeIDDDfed/8w3dNJJnvyXRQdkgHMpRByL471Ki4TGuLsqGuhM83y1lp4iUBghssTESoXk9BYcha8zbNuq220tRCJklxkV6a7cUru/0apmpEfVKhZKQ8BnWO1fnTcQWSZpFvhIq3UkG+6oyi38zmZDOrjs9+UQZzTavaDnuQs3z5ckcdLoHKy8wkuhE8e9PErqO0vUdcaWhNpQGdlD/DaFd/d/WkYP1ezA99QidmTl1k+EHjouUWMNwAHvN795yzss/nk50twyvts7cxEOKKYLGD+HSqU+oB+z2UuZ+hn1WcWsojbfePQ0GdforVUAtFOEMZobtvZELbkyc6gp98pn/q0PIv2ifwdPZ4RTBtEGJmLTtGB1r8TgTIACjBMWxRfmCdvhAvggZUDa73Cy1GdSPuLAW6MZiWzVsgyhVQAW2yO8fXehzzTGL1InN/OUfd8jNxFhiVgBHy3j6Q2Ngr+5OXt6SGk7eZWpt+QDnaZbdGECS/xta8WCv9XMEtiNTZSpk3fcKOktGOSlWE3bZ4LR/EaYIKwwvHTKgnJTELugILDLM5SKq8sbqn7zPy8vcjxDacod1uvo0auHS4a32XbkZjBs7aYTMwVbeVEbow7Cs8Yh3r+VZ4yKIL+5AxsDyjulZocEyrvlZSDm1a0Mk93XasV8AvbNPJp8vgzkFjG0WH1o5otnzzIq3D9vFycGyuMk6Gcncfs+23cjawsVRuWtQ0gl9tv2SAxYvUZNfHm7AtWtUfn2e4tokkyeAnkIgfqiU7XlTVLIdkxecaCHa8dgPUyiF4MYx7aPE/crd7wTiqDBC95Xc/AUsv2RHUHs9sJDNCb9KyGpmdD0K3+Qr1XC0oI23z2MK45Dd4LI0koBtnvZ1BVr0TsZhd6DLFOpiXmgeiaEnh8qOO3XvBk0SE4Xbz42Kx1Sc+TA9bosvRmbyir52g9xB1nL/fkXyBrPkGamHbPwT3yc4LPqyeJ5hDim3hW14SS4zuAGuIOuVc4ptwMtqXd0BrGtqPU8lza/9ElikDnTLFiWkFcJqzBXwHVJZQAdjnp7WN2L2D1sqZtgj2VuZpnUzGrZOErCC5GngKbC/2Nmx+qVI6KrNIM32JazVpbsNxtCpRZ+I2CxrfVbnlc2F4FSJthUgs3DQr79J/qrX6iE0W+uHFVesp0O7zDkZOXXKcq9zDjLVarjmK0ZPtDiTqfnfbRaikdmP6LbWUfqVdnWrtHDpPYcii4cWfxmC9CvsVlFSYx3XNTnD1GO89YozpY9rQixfrjuiAfqRJRjcybEZgQlRxV5Urzdr/dZ+max1qciuYNUZCMHykSWMPwD+AA2iHkJE7/L1PEqcI6EAwkpBcSUOnZFFpAd1g9vfSYaFIHESkgv59xR5CiXNHCOaJd4lDZ4mdeedQvaLWqpWqIo36kbAO+D4XbbCBGpF3PzDZmOkwQJWuerQ+3F+oqlTSQfiKbHUN+vYGXQyhWhbphO9E1K7d3A0nQ/pl//EE9aN6mLDM/G5xhNJ6r3qVa4VQ+AEXdBK9PBvjc8FK/ijo2hlfPda5GtJtHjEJd5VycDpcTMM9GuXHiPj7li41b0UMQ95qrrUPlj82kyF1jDZhnTliPDMfSGCBT7ahIGqSYHbXc+vi9KiCVBbwj5KQ2E4llXfWvEGBjeL06PKjqqprvHYqmXYF3eh94/TznnRDj+ReTA/EGKZeRofGX6R33HCam2LU13T18Rjsh8QyN"}}
15.	2020-11-19 17:09:13 +0800 CST:	[event;sealing.SectorCommitSubmitted]	{"User":{"Message":{"/":"bafy2bzacebhmkse2gsu3vddqvjktfvidemibtvjc6dlifmahijg6le3zrloii"}}}
16.	2020-11-20 10:24:11 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
17.	2020-11-20 10:42:07 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
18.	2020-11-20 10:45:48 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}

**Lotus miner diagnostic info**

Please collect the following diagnostic information, and share a link here

* lotus-miner diagnostic info `lotus-miner info all > allinfo`

** Code modifications **

No

**Version**

root@lotus-master:~# lotus --version
lotus version 1.2.0+git.648f02cbd.dirty

**Comment by jennijuju** [comment] 2020-11-23 20:12
was your mempool stuck or you restarted the miner? have you tried to update the status to `SubmitCommit`?

**Comment by alingb** [comment] 2020-11-24 02:11
Now after I restart the harvester, the status changes to "sealprecommit1failed"[https://github.com/filecoin-project/lotus/issues/4968](url)

**Comment by alingb** [comment] 2020-11-24 02:13
> 内存池卡住了还是重启了矿机？您是否尝试将状态更新为`SubmitCommit`？

现在，在我重启收割机之后，状态更改为“ sealprecommit1failed” #4968

**Comment by alingb** [comment] 2020-11-24 02:14
> was your mempool stuck or you restarted the miner? have you tried to update the status to `SubmitCommit`?

Now after I restart the harvester, the status changes to "seal precommit1 failed" #4968

**Comment by Reiers** [comment] 2021-12-18 22:39
Hi 

Thanks for the report. I'm unable to reproduce this issue on the latest tag. 
Please upgrade Lotus: https://github.com/filecoin-project/lotus/releases/tag/v1.13.1

If you are still experiencing problems, open a new ticket or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)

Closing ticket.

**Closed by Reiers** 2021-12-18 22:39 UTC
Labels: support
