### ISSUE TITLE
Can not mine new block because "Received block with large delay  from miner "

### ISSUE THREAD

**Issue by mostcute** [filecoin-project/lotus#4434] opened 2020-10-16 04:36 UTC
**Describe the bug**
my miner  mined a new block,but it is not on chain and daemon log shows  like `"Received block with large delay  from miner "`

version v0.10.2
**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**

**Additional context**

**Comment by rjan90** [comment] 2021-07-31 06:28
This issue can be closed as it's a duplicate of #5128. #rengjøring

**Closed** 2021-08-16 06:53 UTC
