### ISSUE TITLE
StateAccountKey: failed to get account actor state for t017880: unknown actor code bafkqadtgnfwc6njpnv2wy5djonuwo

### ISSUE THREAD

**Issue by rickiey** [filecoin-project/lotus#7340] opened 2021-09-17 01:54 UTC
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the lotus forum](https://github.com/filecoin-project/lotus/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [X] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

RPC ERROR: 
"method": "Filecoin.StateAccountKey",
failed to get account actor state for t017880: unknown actor code bafkqadtgnfwc6njpnv2wy5djonuwo

when actor is Multi-signature address, This error occurred

### Describe the solution you'd like

should return t2... or f2... address

### Additional context

RPC request for calibrationNet 

```json
{
    "jsonrpc": "2.0",
    "method": "Filecoin.StateAccountKey",
    "id": 1,
    "params":["t017880", null]
}
```

response:

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": 1,
    "message": "failed to get account actor state for t017880: unknown actor code bafkqadtgnfwc6njpnv2wy5djonuwo"
  }
}
```

**Comment by wangyancun** [comment] 2021-09-17 08:30
don't support f2 now

**Comment by TippyFlitsUK** [comment] 2022-03-31 16:07
Hi @rickiey 

Thanks for your report! I have also managed to reproduced the error in 1.15.1-rc4.

I will add labels and will assign it to the right team for analysis.
We might tag you again for more information

**Comment by geoff-vball** [comment] 2022-04-19 15:44
Duplicate of https://github.com/filecoin-project/lotus/issues/5371

**Closed by geoff-vball** 2022-04-19 15:44 UTC
Labels: need/triage, kind/enhancement, area/api
