### ISSUE TITLE
Lotus cannot shutdown

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/lotus#5102] opened 2020-12-02 17:08 UTC
I am participating slingshot competition so I make a lot of deals with my lotus daemon. Lotus always eventually hung and cannot perform any command like "sync wait" and cannot be shutdown with "daemon stop" command. When I look at the logs it shows something like this. At this point lotus can only be killed by "kill -9" and delete chain/reimport can make it work but later on it will hung again.

2020-12-02T08:40:02.031Z        INFO    engine  decision/engine.go:464  aborting message processingshutting down
2020-12-02T08:40:02.032Z        INFO    engine  decision/engine.go:464  aborting message processingshutting down
2020-12-02T08:40:02.090Z        INFO    engine  decision/engine.go:464  aborting message processingshutting down
2020-12-02T08:40:02.118Z        INFO    engine  decision/engine.go:464  aborting message processingshutting down
2020-12-02T08:40:02.169Z        INFO    engine  decision/engine.go:464  aborting message processingshutting down
2020-12-02T08:40:02.186Z        INFO    engine  decision/engine.go:464  aborting message processingshutting down
2020-12-02T08:40:02.200Z        INFO    engine  decision/engine.go:464  aborting message processingshutting down

**Comment by kernelogic** [comment] 2020-12-02 18:47
@vyzo

**Comment by keyceshi02** [comment] 2020-12-25 01:46
I got the same bug on my lotus node

**Comment by Reiers** [comment] 2021-12-25 17:28
**Hi @kernelogic** 

Thanks for the report. I think the issue you are experiencing lies elsewhere.

**I'm unable to reproduce the issue on latest tag.** 

If you are still experiencing problems, open a new ticket or ask for help in our Discussions forum.

Closing ticket.

**Closed by Reiers** 2021-12-25 17:28 UTC
