### ISSUE TITLE
  Worker cause ComputeProofFailed

### ISSUE THREAD

**Issue by gavin-ygy** [filecoin-project/lotus#1686] opened 2020-05-07 03:53 UTC
**Describe the bug**
interopnet 0.3.0'+git799f5e5b'.
1. run ./lotus-storage sectors list,  showing many sectors ComputeProofFailed. 
2. the hardware 3960x + 256G memory + SSD. 
3.  1miner + 1 worker
4. send a sector pledge every 4 minutes 
5. after  stoping the worker and copy the failed sector's files at worker : sealed/s-t01533-xxx , cache/s-t01533-xxx  ---> to miner's  corresponding directory.
6. after a while , the sector will become proving.

**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**

**Version (run `lotus --version`):**

**Additional context**

**Comment by vipally** [comment] 2020-05-13 00:52
**Almost all sectors falling into ComputeProofFailed：**
![image](https://user-images.githubusercontent.com/6396077/81758917-c585cc80-94f5-11ea-8047-f3459277f5e5.png)
![image](https://user-images.githubusercontent.com/6396077/81759369-15b15e80-94f7-11ea-9f48-4873244baf23.png)

**Comment by vipally** [comment] 2020-05-13 01:15
This bug caused by follow message：
commit1: maybeSchedRequest didn't find any good workers

It was caused by following commit：
Revision: 8c4dc60e75fca85210de42c95523656915453ccf
Author: Łukasz Magiera magik6k@gmail.com
Date: 2020/4/28 2:37:31
Message:
move scheduling logic to a separate struct
filecoin-project/sector-storage@8c4dc60#diff-4539540c8184ee5eccb973e7db8911e7L357

**Comment by vipally** [comment] 2020-05-13 01:23
The error code is：
https://github.com/filecoin-project/sector-storage/blob/master/manager.go#L257

The ExistingSelector will make sure worker has config Commit1 task and has output file of PreCommit2. 
But Commit1 task is only setup on local-worker. So the sectors that do PreCommit
2 from remote-workers will always cause **ComputeProofFailed** error.

**Comment by mxz9102** [comment] 2020-05-19 06:12
I got the same error in my miners. I used 1 miner and 2 workers set up.

**Comment by magik6k** [comment] 2020-06-17 14:18
Addressed in #1924

**Closed by magik6k** 2020-06-17 14:18 UTC
