### ISSUE TITLE
deduct so many FILs with no reason

### ISSUE THREAD

**Issue by ffteng46** [filecoin-project/lotus#5021] opened 2020-11-26 15:23 UTC
**Describe the bug**
There is a transaction costs me 53.55Fil which is sent to Burn Acount with no message about what happen to this.There are no correspond message both in miner and daemon logs.
I don't think i trigger any penalty rules.I what to know what happend and how can i get back my lose FILs?
**To Reproduce**
1. Run '...'
2. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/17234469/100365786-e699af00-303a-11eb-9c29-fa5be7e745f5.png)
![image](https://user-images.githubusercontent.com/17234469/100366014-41330b00-303b-11eb-9572-9ecc17742054.png)

**Version (run `lotus version`):**
lotus version
Daemon:  1.2.0+git.dc3d17c9e+api1.0.0
Local: lotus version 1.2.0+git.dc3d17c9e
lotus-miner version
Daemon:  1.2.0+git.dc3d17c9e+api1.0.0
Local: lotus-miner version 1.2.0+git.dc3d17c9e
**Additional context**
miner and daemon are in different server.
miner config.yoml
[Sealing]
  MaxWaitDealsSectors = 0
  MaxSealingSectors = 0
  MaxSealingSectorsForDeals = 0
  WaitDealsDelay = "6h30m0s"

[Storage]
  ParallelFetchLimit = 3 
  AllowAddPiece = false
  AllowPreCommit1 = false
  AllowPreCommit2 = false
  AllowCommit = false
  AllowUnseal = true

[Fees]
  MaxPreCommitGasFee = "0.4 FIL"
  MaxCommitGasFee = "0.4 FIL"
  MaxWindowPoStGasFee = "1.0 FIL"

**Comment by ffteng46** [comment] 2020-11-26 16:42
miner id is t04443
I startup tow lotus daemons in different servers.This is lotus config.toml,no other modification on lotus or miner.
![Uploading image.png…]()

**Comment by jennijuju** [comment] 2020-12-01 21:43
Was resolved in https://filecoinproject.slack.com/archives/C0179RNEMU4/p1606408092263500

The cause was termination penalty

**Closed by jennijuju** 2020-12-01 21:43 UTC
