### ISSUE TITLE
Error "block had invalid message" on shutdown

### ISSUE THREAD

**Issue by willscott** [filecoin-project/lotus#4135] opened 2020-10-01 19:14 UTC
**Describe the bug**
When closing the lotus daemon with ctrl-c while in the process of sync, the output is scary.

**To Reproduce**
1. Run 'lotus daemon'
2. While in message sync, hit 'ctrl-c'
2. See error

**Expected behavior**
No errors while shutting down

**Observed behavior**
```
2020-10-01T12:03:02.099-0700    ERROR   chain   chain/sync_manager.go:421       sync error: collectChain failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).Sync
        /home/user/Documents/github/lotus/chain/sync.go:570
  - collectChain syncMessages:
    github.com/filecoin-project/lotus/chain.(*Syncer).collectChain
        /home/user/Documents/github/lotus/chain/sync.go:1695
  - message processing failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).syncMessagesAndCheckState.func1
        /home/user/Documents/github/lotus/chain/sync.go:1471
  - validating block bafy2bzacecom45v46sq5aopo4ddhdbjtcv2gbv2cihuochl2a2bac4ek4nvy4:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateTipSet.func1
        /home/user/Documents/github/lotus/chain/sync.go:620
  - 2 errors occurred:
        * block had invalid messages:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func3
        /home/user/Documents/github/lotus/chain/sync.go:754
  - getting parent block:
    github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).computeTipSetState
        /home/user/Documents/github/lotus/chain/stmgr/stmgr.go:359
  - datastore closed
        * get tipsetstate(15975, [bafy2bzaceakb6lgbxqr5kekujn3gmzo3tfvedozuxitfocwl4pbjxzculnmcw bafy2bzacedwuzlu6z6rdkfdj5dfexst52sukifykwx3r2ozki26grgfw3zcte bafy2bzaceaq7a5erwktq6yid5asmpu3ebyvalo274ctoj4dro3rtqm7oxx7h6]) failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6
        /home/user/Documents/github/lotus/chain/sync.go:790
  - getting parent block:
    github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).computeTipSetState
        /home/user/Documents/github/lotus/chain/stmgr/stmgr.go:359
  - datastore closed
```

**Version (run `lotus version`):**
Daemon:  0.8.0+git.954d80636.dirty+api0.16.0
Local: lotus version 0.8.0+git.954d80636.dirty

**Comment by TippyFlitsUK** [comment] 2022-04-29 12:57
Hi @willscott 

Thanks for the report. Im unable to reproduce the issue here.

Closing issue ticket - if you encounter the issue again in current release, please open a new ticket and provide new logs. 
Thanks

**Closed by TippyFlitsUK** 2022-04-29 12:57 UTC
Labels: kind/enhancement, area/chain
