### ISSUE TITLE
[lotus-seal-worker] worker doesn't reconnect if miner restarts

### ISSUE THREAD

**Issue by lanzafame** [filecoin-project/lotus#1224] opened 2020-02-05 03:01 UTC
**Describe the bug**
The connection between the seal worker and the miner is not recreated if the miner is restarted.

**To Reproduce**
1. Run 'lotus-storage-miner run'
2. Run 'lotus-seal-worker run'
3. Restart 'lotus-storage-miner'
4. `lotus-storage-miner info' won't show any remote workers 

**Expected behavior**
The connection should be reestablished regardless if either worker or miner are restarted.

**Version (run `lotus --version`):**
master

**Comment by IPFS-grandhelmsman** [comment] 2020-02-05 04:59
I also think developers should consider this priority. the miner node is often restart to upgrade, reconnection is convenient for current deployment.

**Comment by leon-one** [comment] 2020-02-05 09:23
Yes, if you can achieve this function, you can save a lot of time in actual work, especially in the environment with a large number of nodes. Suggested priority solution!

**Comment by whyrusleeping** [comment] 2020-05-29 22:53
@magik6k does this work properly now?

**Comment by mostcute** [comment] 2020-06-02 08:59
> @magik6k does this work properly now?

i don't think so

**Comment by magik6k** [comment] 2020-06-17 15:48
Duplicate of https://github.com/filecoin-project/lotus/issues/771

**Closed by magik6k** 2020-06-17 15:48 UTC
Labels: sealing
