### ISSUE TITLE
RPC sockets are leaked out

### ISSUE THREAD

**Issue by karalabe** [filecoin-project/lotus#3950] opened 2020-09-22 06:33 UTC
This morning I've found my miner stuck looping "no more file descriptors" errors. I've only seen this starting with 0.7.1. Checking the currently used FDs, lotus was hanging on to

```
$ netstat -n | grep WAIT | wc -l
1156
```

```
$ netstat -n | grep WAIT
[...]
tcp      352      0 127.0.0.1:2345          127.0.0.1:51854         CLOSE_WAIT 
tcp      352      0 127.0.0.1:2345          127.0.0.1:38576         CLOSE_WAIT 
tcp      352      0 127.0.0.1:2345          127.0.0.1:59372         CLOSE_WAIT 
tcp      352      0 127.0.0.1:2345          127.0.0.1:56750         CLOSE_WAIT 
tcp      352      0 127.0.0.1:2345          127.0.0.1:53784         CLOSE_WAIT 
tcp      352      0 127.0.0.1:2345          127.0.0.1:54730         CLOSE_WAIT 
tcp      352      0 127.0.0.1:2345          127.0.0.1:56482         CLOSE_WAIT
```

I'm doing 3 RPC requests / second via `watch` to check th sealing jobs, storage lists and sealing workers. My guess is that these RPC request sockets don't get cleaned up properly.

**Comment by karalabe** [comment] 2020-09-22 11:26
Maybe it's some IPC leak. Currently I have 16K+ sockets stuck like this:

```
$ lsof -a -p 1328428
[...]
lotus-min 1328428 karalabe *423u     sock       0,9         0t0 196914180 protocol: TCP
lotus-min 1328428 karalabe *424u     sock       0,9         0t0 196694299 protocol: TCP
lotus-min 1328428 karalabe *425u     sock       0,9         0t0 195762432 protocol: TCP
lotus-min 1328428 karalabe *426u     sock       0,9         0t0 196858526 protocol: TCP
lotus-min 1328428 karalabe *427u     sock       0,9         0t0 196813877 protocol: TCP
lotus-min 1328428 karalabe *428u     sock       0,9         0t0 195996577 protocol: TCP
[...]
```

**Comment by karalabe** [comment] 2020-09-22 11:28
It is definitely an RPC socket leak. Printing `$ lsof -a -p 1328428 | grep lotus | wc -l` in a loop kept increasing the open file descriptors, but when I stopped the `3` watch processes the numbers also stopped increasing.

**Comment by raulk** [comment] 2020-09-22 12:00
@karalabe a goroutine dump from lotus during the `CLOSE_WAIT` conn build-up would be great, to quickly pinpoint the source of the leakage. I quickly took a look and I have a suspicion I'd like to confirm.

**Comment by raulk** [comment] 2020-09-22 12:12
Is your monitoring script closing the WS connections gracefully? If not, a connection reestablishment loop could be kicking off here. If this was the case, it's possible that this problem may not be seen with `lotus` CLI client commands.

**Comment by karalabe** [comment] 2020-09-22 12:19
Any lotus-miner command that retrieves info from the miner leaks out a FD on the miner. I'm just running them in loop.

**Comment by karalabe** [comment] 2020-09-22 12:23
Btw, the CLOSE_WAIT is probably just a symptom after which everything went sour. Today I caught it before it blew up and there were no TCP connections in CLOSE_WAIT, only a metric ton of `lotus-min 1328428 karalabe *428u     sock       0,9         0t0 195996577 protocol: TCP` fd-s dangling in the air.

**Comment by TippyFlitsUK** [comment] 2022-04-29 12:22
Hi @karalabe 

Thanks for the report. The issue is outdated. 

If this is an issue in the current release - please open a new ticket.

Thank you !

**Closed by TippyFlitsUK** 2022-04-29 12:22 UTC
Labels: kind/enhancement, area/networking
