### ISSUE TITLE
head parents equal error!!!

### ISSUE THREAD

**Issue by zgfzgf** [filecoin-project/lotus#4441] opened 2020-10-16 12:42 UTC
One has no order
The other has an order
https://github.com/filecoin-project/lotus/blob/0775c6c9d5a07e340f42668b7cd2068cdfff3a9d/chain/store/store.go#L736-L744
https://github.com/filecoin-project/lotus/blob/0775c6c9d5a07e340f42668b7cd2068cdfff3a9d/chain/types/blockheader.go#L174-L191
https://github.com/filecoin-project/lotus/blob/0775c6c9d5a07e340f42668b7cd2068cdfff3a9d/chain/types/tipset.go#L125-L129

**Comment by schomatis** [comment] 2020-10-26 11:48
Duplicate of https://github.com/filecoin-project/lotus/issues/2857.

**Closed by schomatis** 2020-10-26 11:48 UTC

**Comment by zgfzgf** [comment] 2020-10-26 12:07
@schomatis Please check it again
store.go [A B C] [B A C] ok
tipset [A B C] [B A C] fail 
store.go L744 types.NewTipSet(all)

**Comment by zgfzgf** [comment] 2020-10-26 12:08
### One has no order
### The other has an order

**Comment by schomatis** [comment] 2020-10-26 12:59
@zgfzgf I agree with your assessment, I'm just closing this because it is already covered in the discussion of the issue linked.
