### ISSUE TITLE
Lotus-miner sectors list display inaccurate

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/lotus#5124] opened 2020-12-04 20:03 UTC
**Describe the bug**
Running lotus-miner sectors list displays inaccurate total deal weight value

**To Reproduce**
1. lotus-miner sectors list
2. Sector 349 shows 0 bytes despite having 6GiB of deals

**Expected behavior**
Sector 349 should display 6 GiB of deals not zero.

**Screenshots**
`lotus-miner sectors list |grep  349`
> ID   State       OnChain  Active  Expiration                      Deals  DealWeight
> 349  Proving     YES      YES     1341228 (in 51 weeks 6 days)    3      0B 

`lotus-miner sectors status 349`

> SectorID:	349
> Status:		Proving
> CIDcommD:	baga6ea4seaqlywpzxptyjayqx2fq67ylqhu5jxzg24ecmbyyf3r2kximjvxl2nq
> CIDcommR:	bagboea4b5abcbkvy4d4es4o2rx3wreyp424ig5t6lqdkhdiuqfaiuwhm4eue4kzs
> Ticket:		41af9bbfa9cf7eebcf66dde354411595b4ccfbfce88a72df89bba131347afd28
> TicketH:	290546
> Seed:		acc35cd05cc9e1e7deead6615d8c3318afbfd1c5bd8656b59bb71c8a50e04029
> SeedH:		292444
> Precommit:	bafy2bzaceccitb3zlvfd3ennt5scgkr6wg5j5gwbbcbve3l6v2wdqciuhlxye
> Commit:		bafy2bzacedtwdoax3ekeui7clvite27fmbrkckpch3xamhdoxrlssthsms5q6
> Proof:		... (removed to shorten display)
> Deals:		[1412181 1412372 1412752 0 0 0]
> Retries:	0

`lotus-miner storage-deals list |grep 1412181`

> ...7rk2ljay  1412181  StorageDealActive                   f3ufzpudvsjqyiholpxiqoomsd2svy26jvy4z4pzodikgovkhkp6ioxf5p4jbpnf7tgyg67dny4j75e7og7zeq  2GiB    0.000208303 FIL                  1041515

`lotus-miner storage-deals list |grep 1412372`

> ...525zdhcq  1412372  StorageDealActive                   f3ufzpudvsjqyiholpxiqoomsd2svy26jvy4z4pzodikgovkhkp6ioxf5p4jbpnf7tgyg67dny4j75e7og7zeq  2GiB    0.0002082386 FIL                 1041193

`lotus-miner storage-deals list |grep 1412752`

> ...fy6jnpsq  1412752  StorageDealActive                   f3ufzpudvsjqyiholpxiqoomsd2svy26jvy4z4pzodikgovkhkp6ioxf5p4jbpnf7tgyg67dny4j75e7og7zeq  2GiB    0.000208212 FIL                  1041060

**Version (run `lotus version`):**

`lotus-miner version`
> Daemon:  1.2.2+git.b13226bc2+api1.0.0
> Local: lotus-miner version 1.2.2+git.b13226bc2

**Additional context**

Noticed after most recent commits
Also next sector 350 should have 6 GiB but shows 510.6MiB

> 350  Proving     YES      NO      1341228 (in 51 weeks 6 days)    3      510.6MiB

**Comment by stuberman** [comment] 2020-12-04 20:04
Duplicate of Issue 5116

**Comment by rjan90** [comment] 2020-12-07 09:19
Adding link to the duplicate-issue #5116

**Comment by magik6k** [comment] 2021-01-28 11:21
Duplicate of #5116

**Closed by magik6k** 2021-01-28 11:21 UTC
