### ISSUE TITLE
[arm64 server]GPU FFT failed! Falling back to CPU... Error: Ocl

### ISSUE THREAD

**Issue by billy-chen-2019** [filecoin-project/lotus#3282] opened 2020-08-25 06:56 UTC
**Describe the bug**
[arm64 server]  GPU FFT failed! Falling back to CPU... Error: Ocl Error:  OPENCL ERROR

**[arm64 server] To Reproduce( )**
1. Run './bench sealing --sector-size=512M'
2. See error

2020-08-05T15:51:53.202 INFO filecoin_proofs::api::seal > got groth params (536870912) while sealing
2020-08-05T15:51:53.202 INFO filecoin_proofs::api::seal > snark_proof:start
2020-08-05T15:51:53.284 INFO bellperson::groth16::prover > Bellperson 0.9.2 is being used!
2020-08-05T15:52:00.144 INFO bellperson::gpu::locks > GPU is available for FFT!
2020-08-05T15:52:07.081 INFO bellperson::domain > GPU FFT kernel instantiated!
2020-08-05T15:52:07.167 WARN bellperson::gpu::locks > GPU FFT failed! Falling back to CPU... Error: Ocl Error: 

################################ OPENCL ERROR ############################### 

Error executing function: clCreateKernel("radix_fft")  

Status error code: CL_INVALID_PROGRAM_EXECUTABLE (-45)  

Please visit the following url for more information: 

https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clCreateKernel.html#errors  

############################################################################# 

2020-08-05T15:52:08.535 WARN bellperson::gpu::locks > GPU FFT failed! Falling back to CPU... Error: Ocl Error: 

################################ OPENCL ERROR ############################### 

Error executing function: clCreateKernel("radix_fft")  

Status error code: CL_INVALID_PROGRAM_EXECUTABLE (-45)  

Please visit the following url for more information: 

https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clCreateKernel.html#errors  

############################################################################# 

2020-08-05T15:52:09.839 WARN bellperson::gpu::locks > GPU FFT failed! Falling back to CPU... Error: Ocl Error: 

################################ OPENCL ERROR ############################### 

Error executing function: clCreateKernel("radix_fft")  

Status error code: CL_INVALID_PROGRAM_EXECUTABLE (-45)  

Please visit the following url for more information: .

**Comment by stuberman** [comment] 2020-08-25 20:29
Seems like a duplicate of https://github.com/filecoin-project/lotus/issues/2913

**Comment by ribasushi** [comment] 2020-11-24 08:58
Closing as dupe of #2913

**Closed by ribasushi** 2020-11-24 08:58 UTC
