### ISSUE TITLE
Integrate v5 actor

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#6022] opened 2021-04-12 16:11 UTC

**Comment by magik6k** [comment] 2021-04-12 16:30
Related -> https://github.com/filecoin-project/lotus/pull/5769

**Comment by jennijuju** [comment] 2021-04-13 17:30
https://github.com/filecoin-project/specs-actors/pull/1392

**Comment by BigLep** [comment] 2021-04-29 00:21
@jennijuju : is this a duplicate of https://github.com/filecoin-project/lotus/issues/5985 ?  Can one of them be closed?  They both reference https://github.com/filecoin-project/lotus/pull/5769

**Comment by magik6k** [comment] 2021-05-28 10:23
Done now

**Closed by magik6k** 2021-05-28 10:23 UTC
Labels: impact/consensus
